#!/bin/bash
#
echo ====================================================
echo "CTRL a CTRL ] to exit"
echo
echo ====================================================
miniterm.py --parity N -e --rts 0 --dtr 0 /dev/ttyUSB0 115200
