adf4351/adf4351.h File Reference
#include <stdint.h>
*
#include <stdarg.h>
*
#include <string.h>
*
#include <math.h>
*
#include `adf4351_hal.h`
*
Data Structures
struct r0_t
ADF4351 R0.
struct r1_t
ADF4351 R1 Phase Adjust bit [DB28] [DB28] = 1, Adjust output Do not perform VCO band selection or phase resync when R0 updated. Only use when frequency adjustments will be under 1MHz! [DB28] = 0, Perform VCO band selection and phase resync when R0 updated. (only if phase resync is enabled in R3 [DB16:DB15])
struct r2_t
ADF4351 R2 structure Noise Mode 2bits [DB30:DB29] (NoiseSpureMode) The noise mode optimizes either improved spurious or improved phase noise.
struct r3_t
ADF4351 R3 structure Band Select Clock Mode [DB23] (BSCM) [DB23] = 1, use if you need fast band selection Suitable for PFD frequencies > 125kHz. Keep band select clock divider <= 254. [DB23] = 0, use if PFD frequencies are < 125kHz.
struct r4_t
ADF4351 R4 structure.
struct r5_t
ADF4351 R5 structure Lock Detect Pin Operation [DB23:22] (LDPinMode) [DB23:22] 00 = LOW [DB23:22] 01 = Digital Lock Detect [DB23:22] 10 = LOW [DB23:22] 11 = HIGH.
struct adf4351_regs_t
ADF4351 all registers type.
struct adf4351_err_t
ADF4351 Error structure.
Macros
#define ADF4351_RFOUT_MAX 4400000000.0
#define ADF4351_RFOUT_MIN 34375000.0
#define ADF4351_VCO_MIN 2200000000.0
#define ADF4351_MAX_FREQ_45PRE 3000000000.0
#define ADF4351_PFD_MAX 32000000.0
#define ADF4351_REFIN_MAX 250000000.0
#define ADF4351_BANDSEL_MAX 125000
Enumerations
enum {
*
ADF4351_NOERROR,
ADF4351_RFout_RANGE,
ADF4351_RFoutDIV_RANGE,
ADF4351_RFout_MISMATCH,
*
ADF4351_REFin_RANGE,
ADF4351_BandSelectClockFrequency_RANGE,
ADF4351_R_RANGE,
ADF4351_PFD_RANGE,
*
ADF4351_N_RANGE,
ADF4351_INT_RANGE,
ADF4351_MOD_RANGE,
ADF4351_FRAC_RANGE,
*
ADF4351_ERROR_END
 }
Error numbers.
enum { ADF4351_DISABLE,
ADF4351_ENABLE
 }
Disable/Enable.
enum { ADF4351_PRESCALER_4_5,
ADF4351_PRESCALER_8_9
 }
dual-modulus prescaler (P/P + 1)
enum { ADF4351_LOW_NOISE_MODE,
ADF4351_LOW_SPUR_MODE = 3
 }
Low Noise and Low Spur Modes.
enum {
*
ADF4351_MUX_THREESTATE,
ADF4351_MUX_DVDD,
ADF4351_MUX_DGND,
ADF4351_MUX_RCOUNTER,
*
ADF4351_MUX_NDIVIDER,
ADF4351_MUX_ANALOGLOCK,
ADF4351_MUX_DIGITALLOCK
 }
MUXOUT multiplexer.
enum { ADF4351_LDF_FRAC_N,
ADF4351_LDF_INT_N
 }
Lock Detect Function FRAC or INT mode.
enum { ADF4351_LDP_10NS,
ADF4351_LDP_6NS
 }
The lock detect window time for lock detect circuit.
enum { ADF4351_POLARITY_NEG,
ADF4351_POLARITY_POS
 }
Phase Detector Polarity.
enum { ADF4351_ABP_6NS,
ADF4351_ABP_3NS
 }
Antibacklash Pulse Width.
enum { ADF4351_CLKDIVMODE_OFF,
ADF4351_CLKDIVMODE_FAST_LOCK,
ADF4351_CLKDIVMODE_RESYNC
 }
Clock Divider PLL lock mode.
enum { ADF4351_LD_PIN_LOW,
ADF4351_LD_PIN_DIGITAL_LOCK,
ADF4351_LD_PIN_LOW_,
ADF4351_LD_PIN_HIGH
 }
Lock Detect Pin Operation type.
enum { ADF4351_POWER_N4DB,
ADF4351_POWER_N1DB,
ADF4351_POWER_2DB,
ADF4351_POWER_5DB
 }
Output Power.
enum { ADF4351_AUXOUT_FROM_RF_DIVIDERS,
ADF4351_AUXOUT_FROM_VCO
 }
AUXout from VCO or dividers.
Functions
MEMSPACE void ADF4351_sync (int all)
Sync settings to ADF4351 registers.
MEMSPACE uint32_t ADF4351_GetReg32 (int addr)
Returns 32bit register value from register buffer.
MEMSPACE int ADF4351_CHARGE_PUMP_uA (int32_t x)
Convert charge pump current in uA to R2 register value.
MEMSPACE void ADF4351_Init (void)
Init all ADF4351 registers to default values.
MEMSPACE void ADF_dump_registers (void)
MEMSPACE uint32_t ADF4351_status (uint8_t mode)
Read ADF4351 status Only of value if spi bus input is tied to mux out This function has not been tested!
MEMSPACE uint32_t ADF4351_GCD (uint32_t u, uint32_t v)
MEMSPACE double ADF4351_PFD (double REFin, int R)
Compute PFD.
MEMSPACE void ADF4351_display_error (int error)
Verbose Error messages.
MEMSPACE int ADF4351_Config (double RFout, double REFin, double ChannelSpacing, double *RFoutCalc)
Calculate register values for ADF4351.
Macro Definition Documentation
#define ADF4351_BANDSEL_MAX 125000
Definition at line 51 of file adf4351.h.
#define ADF4351_MAX_FREQ_45PRE 3000000000.0
Definition at line 48 of file adf4351.h.
Referenced by ADF4351_Config().
#define ADF4351_PFD_MAX 32000000.0
Definition at line 49 of file adf4351.h.
Referenced by ADF4351_Config().
#define ADF4351_REFIN_MAX 250000000.0
Definition at line 50 of file adf4351.h.
Referenced by ADF4351_Config().
#define ADF4351_RFOUT_MAX 4400000000.0
Definition at line 45 of file adf4351.h.
Referenced by ADF4351_Config().
#define ADF4351_RFOUT_MIN 34375000.0
Definition at line 46 of file adf4351.h.
Referenced by ADF4351_Config().
#define ADF4351_VCO_MIN 2200000000.0
Definition at line 47 of file adf4351.h.
Referenced by ADF4351_Config().
Enumeration Type Documentation
anonymous enum
The lock detect window time for lock detect circuit.
Enumerator
ADF4351_LDP_10NS
ADF4351_LDP_6NS
Definition at line 406 of file adf4351.h.
anonymous enum
Phase Detector Polarity.
Enumerator
ADF4351_POLARITY_NEG
 inverting loop filter
ADF4351_POLARITY_POS
 noninverting loop filter
Definition at line 414 of file adf4351.h.
anonymous enum
Antibacklash Pulse Width.
Enumerator
ADF4351_ABP_6NS
ADF4351_ABP_3NS
Definition at line 424 of file adf4351.h.
anonymous enum
Clock Divider PLL lock mode.
Enumerator
ADF4351_CLKDIVMODE_OFF
ADF4351_CLKDIVMODE_FAST_LOCK
ADF4351_CLKDIVMODE_RESYNC
Definition at line 433 of file adf4351.h.
anonymous enum
Lock Detect Pin Operation type.
Enumerator
ADF4351_LD_PIN_LOW
ADF4351_LD_PIN_DIGITAL_LOCK
ADF4351_LD_PIN_LOW_
ADF4351_LD_PIN_HIGH
Definition at line 443 of file adf4351.h.
anonymous enum
Output Power.
Enumerator
ADF4351_POWER_N4DB
ADF4351_POWER_N1DB
ADF4351_POWER_2DB
ADF4351_POWER_5DB
Definition at line 455 of file adf4351.h.
anonymous enum
AUXout from VCO or dividers.
Enumerator
ADF4351_AUXOUT_FROM_RF_DIVIDERS
 RFout is VCO after RF dividers
ADF4351_AUXOUT_FROM_VCO
 RFout direct from VCO
Definition at line 466 of file adf4351.h.
anonymous enum
Error numbers.
Enumerator
ADF4351_NOERROR
ADF4351_RFout_RANGE
ADF4351_RFoutDIV_RANGE
ADF4351_RFout_MISMATCH
ADF4351_REFin_RANGE
ADF4351_BandSelectClockFrequency_RANGE
ADF4351_R_RANGE
ADF4351_PFD_RANGE
ADF4351_N_RANGE
ADF4351_INT_RANGE
ADF4351_MOD_RANGE
ADF4351_FRAC_RANGE
ADF4351_ERROR_END
Definition at line 340 of file adf4351.h.
anonymous enum
Disable/Enable.
Enumerator
ADF4351_DISABLE
ADF4351_ENABLE
Definition at line 359 of file adf4351.h.
anonymous enum
dual-modulus prescaler (P/P + 1)
Enumerator
ADF4351_PRESCALER_4_5
 Prescaler = 4/5: NMIN = 23
ADF4351_PRESCALER_8_9
 Prescaler = 8/9: NMIN = 75
Definition at line 368 of file adf4351.h.
anonymous enum
Low Noise and Low Spur Modes.
Enumerator
ADF4351_LOW_NOISE_MODE
ADF4351_LOW_SPUR_MODE
Definition at line 376 of file adf4351.h.
anonymous enum
MUXOUT multiplexer.
Enumerator
ADF4351_MUX_THREESTATE
ADF4351_MUX_DVDD
ADF4351_MUX_DGND
ADF4351_MUX_RCOUNTER
ADF4351_MUX_NDIVIDER
ADF4351_MUX_ANALOGLOCK
ADF4351_MUX_DIGITALLOCK
Definition at line 384 of file adf4351.h.
anonymous enum
Lock Detect Function FRAC or INT mode.
Enumerator
ADF4351_LDF_FRAC_N
ADF4351_LDF_INT_N
Definition at line 398 of file adf4351.h.
Function Documentation
MEMSPACE int ADF4351_CHARGE_PUMP_uA (int32_t x)
Convert charge pump current in uA to R2 register value.
Parameters
none
Definition at line 145 of file adf4351.c.
Referenced by ADF4351_Init().
MEMSPACE int ADF4351_Config (double RFout, double REFin, double ChannelSpacing, double * RFoutCalc)
Calculate register values for ADF4351.
Parameters
RFout Required output frequency in Hz
REFin Reference clock in Hz
Spacing Output channel spacing in Hz RFoutCalc: Calculated actual output frequency in Hz
Return values
0=OK,or Error code
RFoutVCO = [r0_INT + (r0_FRAC/r1_MOD)] (PFD) RFout = [r0_INT + (r0_FRAC/r1_MOD)] (PFD /RFoutDIV) RFout is the RF frequency output. r0_INT is the integer division factor. r0_FRAC is the numerator of the fractional division (0 to MOD 1). r1_MOD is the preset fractional modulus (2 to 4095). RFoutDIV is the VCO output divider. PFD = REFin [(1 + REFinMUL2)/(R (1 + REFinDIV2))] REFin is the reference frequency input. REFinMUL2 is the REFin doubler bit (0 or 1). r2_R is REFin division factor (1 to 1023). REFinDIV2 is the reference divide-by-2 bit (0 or 1). Fres = ChannelSpacing * RFoutDIV r1_MOD=REFin / Fres
Definition at line 422 of file adf4351.c.
Referenced by user_tests().
MEMSPACE void ADF4351_display_error (int error)
Verbose Error messages.
Display ADF4351 error return code
Parameters
error error code
Definition at line 390 of file adf4351.c.
Referenced by user_tests().
MEMSPACE uint32_t ADF4351_GCD (uint32_t u, uint32_t v)
MEMSPACE uint32_t ADF4351_GetReg32 (int addr)
Returns 32bit register value from register buffer.
=============================================================
Parameters
addr Register address
Return values
register value
Definition at line 74 of file adf4351.c.
Referenced by ADF4351_status(), and ADF4351_sync().
MEMSPACE void ADF4351_Init (void)
Init all ADF4351 registers to default values.
Parameters
none
Definition at line 163 of file adf4351.c.
Referenced by setup().
MEMSPACE double ADF4351_PFD (double REFin, int R)
Compute PFD.
Parameters
REFin Reference in frequency
R Reference divider
Definition at line 356 of file adf4351.c.
Referenced by ADF4351_Config().
MEMSPACE uint32_t ADF4351_status (uint8_t mode)
Read ADF4351 status Only of value if spi bus input is tied to mux out This function has not been tested!
Parameters
mode muxout mode
Returns
32bit result
Definition at line 305 of file adf4351.c.
MEMSPACE void ADF4351_sync (int all)
Sync settings to ADF4351 registers.
=============================================================
Parameters
in all sync all registers
Definition at line 50 of file adf4351.c.
Referenced by ADF4351_Init(), ADF4351_status(), and user_tests().
MEMSPACE void ADF_dump_registers (void)