adf4351/adf4351_hal.c File Reference
#include <user_config.h>
*
#include `adf4351_hal.h`
*
Functions
MEMSPACE void ADF4351_gpio_init (void)
Initialize ADF4351 LE pin.
MEMSPACE void ADF4351_spi_init (void)
Obtain SPI bus for ADF4351 display, raise LE return: void.
void ADF4351_spi_begin ()
Obtain SPI bus for ADF4351 display, LE LOW return: void.
void ADF4351_spi_end ()
Release SPI bus from ADF4351, LE HIGH return: void.
uint32_t ADF4351_txrx (uint32_t value)
Transmit 32 bit data value.
Variables
uint16_t ADF4351_clock = -1
cahce of SPI clock devisor
Function Documentation
MEMSPACE void ADF4351_gpio_init (void)
Initialize ADF4351 LE pin.
=============================================================
HAL
Returns
diplay ID 9341
Definition at line 38 of file adf4351_hal.c.
Referenced by ADF4351_Init().
void ADF4351_spi_begin (void)
Obtain SPI bus for ADF4351 display, LE LOW return: void.
Definition at line 65 of file adf4351_hal.c.
Referenced by ADF4351_txrx().
void ADF4351_spi_end (void)
Release SPI bus from ADF4351, LE HIGH return: void.
Definition at line 76 of file adf4351_hal.c.
Referenced by ADF4351_txrx().
MEMSPACE void ADF4351_spi_init (void)
Obtain SPI bus for ADF4351 display, raise LE return: void.
Definition at line 55 of file adf4351_hal.c.
Referenced by ADF4351_Init().
uint32_t ADF4351_txrx (uint32_t value)
Transmit 32 bit data value.
Parameters
in value 32bit data send return: spi data
Definition at line 89 of file adf4351_hal.c.
Referenced by ADF4351_status(), and ADF4351_sync().
Variable Documentation
uint16_t ADF4351_clock = -1
cahce of SPI clock devisor
Start SPI Hardware Abstraction Layer Keep all hardware dependent SPI code in this section
Definition at line 50 of file adf4351_hal.c.
Referenced by ADF4351_spi_begin(), and ADF4351_spi_init().