adf4351/adf4351_hal.h File Reference
#include <user_config.h>
*
Macros
#define ADF4351_LE_PIN 0
#define ADF4351_LE_LOW GPIO_OUTPUT_SET(0, 0)
#define ADF4351_LE_HI GPIO_OUTPUT_SET(0, 1)
#define ADF4351_LE_INIT PIN_FUNC_SELECT(PERIPHS_IO_MUX_GPIO0_U, FUNC_GPIO0); ADF4351_LE_HI
Functions
MEMSPACE void ADF4351_gpio_init (void)
Initialize ADF4351 LE pin.
MEMSPACE void ADF4351_spi_init ()
Obtain SPI bus for ADF4351 display, raise LE return: void.
void ADF4351_spi_begin (void)
Obtain SPI bus for ADF4351 display, LE LOW return: void.
void ADF4351_spi_end (void)
Release SPI bus from ADF4351, LE HIGH return: void.
uint32_t ADF4351_txrx (uint32_t value)
Transmit 32 bit data value.
Macro Definition Documentation
#define ADF4351_LE_HI GPIO_OUTPUT_SET(0, 1)
Definition at line 34 of file adf4351_hal.h.
Referenced by ADF4351_gpio_init(), and ADF4351_spi_end().
#define ADF4351_LE_INIT PIN_FUNC_SELECT(PERIPHS_IO_MUX_GPIO0_U, FUNC_GPIO0); ADF4351_LE_HI
Definition at line 35 of file adf4351_hal.h.
Referenced by ADF4351_gpio_init().
#define ADF4351_LE_LOW GPIO_OUTPUT_SET(0, 0)
Definition at line 33 of file adf4351_hal.h.
Referenced by ADF4351_spi_begin(), ADF4351_spi_end(), and ADF4351_spi_init().
#define ADF4351_LE_PIN 0
Definition at line 32 of file adf4351_hal.h.
Referenced by ADF4351_gpio_init().
Function Documentation
MEMSPACE void ADF4351_gpio_init (void)
Initialize ADF4351 LE pin.
=============================================================
HAL
Returns
diplay ID 9341
Definition at line 38 of file adf4351_hal.c.
Referenced by ADF4351_Init().
void ADF4351_spi_begin (void)
Obtain SPI bus for ADF4351 display, LE LOW return: void.
Definition at line 65 of file adf4351_hal.c.
Referenced by ADF4351_txrx().
void ADF4351_spi_end (void)
Release SPI bus from ADF4351, LE HIGH return: void.
Definition at line 76 of file adf4351_hal.c.
Referenced by ADF4351_txrx().
MEMSPACE void ADF4351_spi_init ()
Obtain SPI bus for ADF4351 display, raise LE return: void.
Definition at line 55 of file adf4351_hal.c.
Referenced by ADF4351_Init().
uint32_t ADF4351_txrx (uint32_t value)
Transmit 32 bit data value.
Parameters
in value 32bit data send return: spi data
Definition at line 89 of file adf4351_hal.c.
Referenced by ADF4351_status(), and ADF4351_sync().