adf4351/adf4351.c File Reference
#include `adf4351_hal.h`
*
#include `adf4351.h`
*
#include <math.h>
*
Functions
MEMSPACE void ADF4351_sync (int all)
Sync settings to ADF4351 registers.
MEMSPACE uint32_t ADF4351_GetReg32 (int addr)
Returns 32bit register value from register buffer.
MEMSPACE int ADF4351_CHARGE_PUMP_uA (int32_t x)
Convert charge pump current in uA to R2 register value.
MEMSPACE void ADF4351_Init (void)
Init all ADF4351 registers to default values.
MEMSPACE uint32_t ADF4351_status (uint8_t mode)
Read ADF4351 status Only of value if spi bus input is tied to mux out This function has not been tested!
MEMSPACE uint32_t ADF4351_GCD32 (uint32_t u, uint32_t v)
Return the GCD of two unsifned 32bit numbers.
MEMSPACE MEMSPACE double ADF4351_PFD (double REFin, int R)
Compute PFD.
MEMSPACE void ADF4351_display_error (int error)
Verbose Error messages.
MEMSPACE int ADF4351_Config (double RFout, double REFin, double ChannelSpacing, double *RFoutCalc)
Calculate register values for ADF4351.
Variables
adf4351_regs_t regs
ADF4351 register buffer.
Function Documentation
MEMSPACE int ADF4351_CHARGE_PUMP_uA (int32_t x)
Convert charge pump current in uA to R2 register value.
Parameters
none
Definition at line 135 of file adf4351.c.
Referenced by ADF4351_Init().
MEMSPACE int ADF4351_Config (double RFout, double REFin, double ChannelSpacing, double * RFoutCalc)
Calculate register values for ADF4351.
Parameters
RFout Required output frequency in Hz
REFin Reference clock in Hz
Spacing Output channel spacing in Hz RFoutCalc: Calculated actual output frequency in Hz
Return values
0=OK,or Error code
RFoutVCO = [r0_INT + (r0_FRAC/r1_MOD)] × (PFD) RFout = [r0_INT + (r0_FRAC/r1_MOD)] × (PFD /RFoutDIV) RFout is the RF frequency output. r0_INT is the integer division factor. r0_FRAC is the numerator of the fractional division (0 to MOD − 1). r1_MOD is the preset fractional modulus (2 to 4095). RFoutDIV is the VCO output divider. PFD = REFin × [(1 + REFinMUL2)/(R × (1 + REFinDIV2))] REFin is the reference frequency input. REFinMUL2 is the REFin doubler bit (0 or 1). r2_R is REFin division factor (1 to 1023). REFinDIV2 is the reference divide-by-2 bit (0 or 1). Fres = ChannelSpacing * RFoutDIV r1_MOD=REFin / Fres
Definition at line 412 of file adf4351.c.
Referenced by user_tests().
MEMSPACE void ADF4351_display_error (int error)
Verbose Error messages.
Display ADF4351 error return code
Parameters
error error code
Definition at line 380 of file adf4351.c.
Referenced by user_tests().
MEMSPACE uint32_t ADF4351_GCD32 (uint32_t u, uint32_t v)
Return the GCD of two unsifned 32bit numbers.
Parameters
u first number
v second number
Returns
GCD of u and v
Definition at line 320 of file adf4351.c.
Referenced by ADF4351_Config().
MEMSPACE uint32_t ADF4351_GetReg32 (int addr)
Returns 32bit register value from register buffer.
=============================================================
Parameters
addr Register address
Return values
register value
Definition at line 64 of file adf4351.c.
Referenced by ADF4351_status(), and ADF4351_sync().
MEMSPACE void ADF4351_Init (void)
Init all ADF4351 registers to default values.
Parameters
none
Definition at line 153 of file adf4351.c.
Referenced by setup().
MEMSPACE MEMSPACE double ADF4351_PFD (double REFin, int R)
Compute PFD.
Parameters
REFin Reference in frequency
R Reference divider
Definition at line 346 of file adf4351.c.
Referenced by ADF4351_Config().
MEMSPACE uint32_t ADF4351_status (uint8_t mode)
Read ADF4351 status Only of value if spi bus input is tied to mux out This function has not been tested!
Parameters
mode muxout mode
Returns
32bit result
Definition at line 295 of file adf4351.c.
MEMSPACE void ADF4351_sync (int all)
Sync settings to ADF4351 registers.
=============================================================
Parameters
in all sync all registers
Definition at line 42 of file adf4351.c.
Referenced by ADF4351_Init(), ADF4351_status(), and user_tests().
Variable Documentation
adf4351_regs_t regs
ADF4351 register buffer.
Definition at line 35 of file adf4351.c.
Referenced by cal_dex_dump().