adf4351/adf4351_cmd.c File Reference
#include `user_config.h`
*
#include <stdint.h>
*
#include <stdarg.h>
*
#include `hspi.h`
*
#include `stringsup.h`
*
#include `adf4351.h`
*
#include `mathio.h`
*
Data Structures
struct freq_t
Functions
MEMSPACE void ADF4351_update (double freq)
MEMSPACE void ADF4351_task ()
MEMSPACE int adf4351_cmd (int argc, char *argv[])
Variables
freq_t frequency = { 100e6, 100e6, 100e6, 0.0, 0.0, 0 }
Function Documentation
MEMSPACE int adf4351_cmd (int argc, char * argv[])
Parameters
in line - command line
Returns
void
Definition at line 102 of file adf4351_cmd.c.
Referenced by user_tests().
MEMSPACE void ADF4351_task (void)
Definition at line 59 of file adf4351_cmd.c.
Referenced by user_loop().
MEMSPACE void ADF4351_update (double freq)
Definition at line 51 of file adf4351_cmd.c.
Referenced by ADF4351_task().
Variable Documentation
freq_t frequency = { 100e6, 100e6, 100e6, 0.0, 0.0, 0 }
Definition at line 47 of file adf4351_cmd.c.