fonts/bdffontutil.c File Reference
BDF to C code converter Copyright 2015 Mike Gore Displays fonts generated by bdffont2c BDF to C code converter BDF = Glyph Bitmap Distribution Format The code handles fixed, proportional and bounding box format fonts.
#include <stdio.h>
*
#include <stdlib.h>
*
#include <unistd.h>
*
#include <string.h>
*
#include <limits.h>
*
#include <errno.h>
*
#include <stdint.h>
*
#include <ctype.h>
*
#include `font.h`
*
#include `bdffontutil.h`
*
Functions
void * db_calloc (size_t size)
calloc memory or error exit
void * db_free (void *p)
free memory
char * stralloc (char *str)
Allocate memory and copy string into it.
char * remove_quotes (char *str)
STrip quotes from string and leading spaces.
void line_wrap (char *str, int max)
Line wrap function ASSUMES we write back into the string (replace space or tab with newlines.
void trim_tail (char *str)
Remove characters less then or equal to space from end of string.
char * skip_spaces (char *str)
Skip spaces at start of string.
char * get_token (char *str, char *token, int max)
get first non space containing string Skip spaces at start of string
int ishex (int c)
is a character hex ASCII character
int ishexstr (char *str)
Does a string only contain hex characters ?
char * match_token (char *str, char *pat)
Match next token against pattern.
void FontHeaderInfo (FILE *out, _font *font, char *prog, char *target)
Write Font Header Information Copyright, font family, etc.
void Convert_Font2c (FILE *out, _font *font)
Convert font to C structure Writes header information, font specification, font bitmap.
void emit_number (FILE *out, char *name, int num)
Write Font Structure element as a number.
void emit_data (FILE *out, char *name, unsigned char *data, int size)
Write Font Structure element as a uint8_t value.
void emit_str (FILE *out, char *name, unsigned char *data)
Write Font Structure string.
void InitNames ()
Reset File and Structure names.
void InitFonts (_font *font)
Initialize all font structures to reset states.
void FreeFont (_font *font)
Free font data.
void AddFontName (_font *font)
Generate the font name for this font This is based on the BDF FAMILY_NAME,WEIGHT_NAME,SLANT keywords.
int FindFontName (char *str)
Search for a font name.
void WriteFontBits (FILE *out, _font *font)
Write Font bitmap data for all characters in a font.
void WriteFontInfo (FILE *out, _font *font)
Write C Header: Font Information Summary.
void WriteFontTable (FILE *out, _font *font)
Write Specification Font Table.
void WriteCharacterBits (FILE *out, _font *font, int num)
Write Font bitmap data for one charactre.
int ReadBdf (char *name, _font *font, int lower, int upper)
Read and parse a BDF file for specified font and character set range Fills fonts structures.
void AdjustFontTable (_font *font)
Adjust Font X Y offset, renormalize X Y to 0 0 Also readjust font bounding box.
void FontAdjustFull (_font *font)
Adjust font to full size with no offset.
void FontAdjustSmall (_font *font)
Ajust font to use smallest font bounding box for each font Can be used to converting large fixed fonts to more compact form Creates font->specs if missing. Updates font->specs with new font size and offsets Can convert fixed to proportional or optimize bounding box to smallest size for space savings.
void ComputeGapSize (_font *font)
Find a good gap size (inter-character spacing) for any font Currently we searching for the smallest width feature in a font set and use it as the gap Set update font->gap FIXME Alternatively we may wish to consider scanning characters only in their middle (virtically) center.
void bsetv (unsigned char *ptr, int addr)
bit set in byte array
void bclrv (unsigned char *ptr, int addr)
bit clear in byte array
int btestv (unsigned char *ptr, int addr)
Test bit in byte array.
int bittestxy (unsigned char *ptr, int x, int y, int w, int h)
Test bit in width * height size bit array usng x and y offsets.
void bitsetxy (unsigned char *ptr, int x, int y, int w, int h)
Set bit in width * height size bit array usng x and y offsets.
void bitclrxy (unsigned char *ptr, int x, int y, int width, int height)
Clear bit in width * height size bit array usng x and y offsets.
void FontPreview (FILE *out, _font *font, int num)
Write Font Preview bit bounding box in ASCII character comments.
void FontPreviewFull (FILE *out, _font *font, int num)
Write Font Preview as full format in ASCII character comments.
void FontPreviewProportional (FILE *out, _font *font, int num)
Write Font Preview as proportional format in ASCII character comments.
void WriteFontBitsPreview (FILE *out, _font *font, int preview)
Write all Font characters in a font as ASCII character comments.
Variables
_bdffile BDFnames [MAXFONTS]
char * fnames [MAXFONTS]
char * EMPTY = ``
Detailed Description
BDF to C code converter Copyright 2015 Mike Gore Displays fonts generated by bdffont2c BDF to C code converter BDF = Glyph Bitmap Distribution Format The code handles fixed, proportional and bounding box format fonts.
See also
http://en.wikipedia.org/wiki/Glyph_Bitmap_Distribution_Format
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
void AddFontName (_font * font)
Generate the font name for this font This is based on the BDF FAMILY_NAME,WEIGHT_NAME,SLANT keywords.
Parameters
in *font Font pointer
Returns
: void
Definition at line 582 of file bdffontutil.c.
Referenced by ReadBdf().
void AdjustFontTable (_font * font)
Adjust Font X Y offset, renormalize X Y to 0 0 Also readjust font bounding box.
Parameters
in *font Font pointer
Returns
: void
Definition at line 1191 of file bdffontutil.c.
Referenced by FontAdjustSmall(), and ReadBdf().
void bclrv (unsigned char * ptr, int addr)
bit clear in byte array
Parameters
in *ptr byte array
in addr bit offset to clear
Returns
void
Definition at line 1639 of file bdffontutil.c.
void bitclrxy (unsigned char * ptr, int x, int y, int width, int height)
Clear bit in width * height size bit array usng x and y offsets.
Parameters
in *ptr byte array
in x bit x offset
in y bit y offset
in width width of bit array
in height height of bit array
Returns
void
Definition at line 1726 of file bdffontutil.c.
Referenced by FontAdjustFull(), and ReadBdf().
void bitsetxy (unsigned char * ptr, int x, int y, int w, int h)
Set bit in width * height size bit array usng x and y offsets.
Parameters
in *ptr byte array
in x bit x offset
in y bit y offset
in w width of bit array
in h height of bit array
Returns
void
Definition at line 1698 of file bdffontutil.c.
Referenced by FontAdjustFull(), FontAdjustSmall(), and ReadBdf().
int bittestxy (unsigned char * ptr, int x, int y, int w, int h)
Test bit in width * height size bit array usng x and y offsets.
Test bit in w * h size bit array usng x and y offsets.
Parameters
in *ptr byte array
in x bit x offset
in y bit y offset
in w the width of bit array
in h the height of bit array
Returns
1 if bit is set, 0 if not
Definition at line 1670 of file bdffontutil.c.
Referenced by ComputeGapSize(), FontAdjustFull(), FontAdjustSmall(), FontPreview(), FontPreviewFull(), and FontPreviewProportional().
void bsetv (unsigned char * ptr, int addr)
bit set in byte array
Parameters
in *ptr byte array
in addr bit offset to clear
Returns
void
Definition at line 1625 of file bdffontutil.c.
int btestv (unsigned char * ptr, int addr)
Test bit in byte array.
Parameters
in *ptr byte array
in addr bit offset to clear
Returns
1 if bit is set, 0 if not
Definition at line 1653 of file bdffontutil.c.
void ComputeGapSize (_font * font)
Find a good gap size (inter-character spacing) for any font Currently we searching for the smallest width feature in a font set and use it as the gap Set update font->gap FIXME Alternatively we may wish to consider scanning characters only in their middle (virtically) center.
Parameters
in *font Font pointer
Returns
: void
Definition at line 1524 of file bdffontutil.c.
Referenced by main(), and ReadBdf().
void Convert_Font2c (FILE * out, _font * font)
Convert font to C structure Writes header information, font specification, font bitmap.
Parameters
in *out File handle
in *font Font handle
Returns
: void
Definition at line 365 of file bdffontutil.c.
Referenced by main().
void* db_calloc (size_t size)
calloc memory or error exit
Parameters
in size memory size to calloc
Returns
: void * pointer
Definition at line 62 of file bdffontutil.c.
Referenced by FontAdjustFull(), FontAdjustSmall(), InitFonts(), ReadBdf(), and stralloc().
void* db_free (void * p)
free memory
Parameters
in *p memory pointer to free
Returns
: void * pointer
Definition at line 78 of file bdffontutil.c.
Referenced by FontAdjustFull(), FontAdjustSmall(), and FreeFont().
void emit_data (FILE * out, char * name, unsigned char * data, int size)
Write Font Structure element as a uint8_t value.
Parameters
in *out File handle
in *name structure name
in *data data
in size size of data to write
Returns
: void
Definition at line 457 of file bdffontutil.c.
void emit_number (FILE * out, char * name, int num)
Write Font Structure element as a number.
Parameters
in *out File output handle
in *name number structure name
in num number to display
Returns
: void
Definition at line 442 of file bdffontutil.c.
Referenced by Convert_Font2c().
void emit_str (FILE * out, char * name, unsigned char * data)
Write Font Structure string.
Parameters
in *out File handle
in *name structure name
in *data string
Returns
: void
Definition at line 478 of file bdffontutil.c.
Referenced by WriteFontInfo().
int FindFontName (char * str)
Search for a font name.
Returns
: index into BDFnames[]
Definition at line 611 of file bdffontutil.c.
Referenced by main().
void FontAdjustFull (_font * font)
Adjust font to full size with no offset.
Parameters
in *font Font pointer
Returns
: void
Definition at line 1240 of file bdffontutil.c.
Referenced by main().
void FontAdjustSmall (_font * font)
Ajust font to use smallest font bounding box for each font Can be used to converting large fixed fonts to more compact form Creates font->specs if missing. Updates font->specs with new font size and offsets Can convert fixed to proportional or optimize bounding box to smallest size for space savings.
Parameters
in *font Font pointer
Returns
: void
Definition at line 1325 of file bdffontutil.c.
Referenced by main().
void FontHeaderInfo (FILE * out, _font * font, char * prog, char * target)
Write Font Header Information Copyright, font family, etc.
Parameters
in *out File handle
in *font Font handle
in *prog program name
in *target file name comments
Returns
: void
Definition at line 323 of file bdffontutil.c.
Referenced by main().
void FontPreview (FILE * out, _font * font, int num)
Write Font Preview bit bounding box in ASCII character comments.
Parameters
in *out File handle
in *font Font pointer
in num Font character
Returns
: void
Definition at line 1753 of file bdffontutil.c.
Referenced by WriteFontBitsPreview().
void FontPreviewFull (FILE * out, _font * font, int num)
Write Font Preview as full format in ASCII character comments.
Parameters
in *out File handle
in *font Font pointer
in num Font character
Returns
: void
Definition at line 1836 of file bdffontutil.c.
Referenced by WriteFontBitsPreview().
void FontPreviewProportional (FILE * out, _font * font, int num)
Write Font Preview as proportional format in ASCII character comments.
Parameters
in *out File handle
in *font Font pointer
in num Font character
Returns
: void
Definition at line 1938 of file bdffontutil.c.
Referenced by WriteFontBitsPreview().
void FreeFont (_font * font)
Free font data.
Parameters
in *font Font pointer
Returns
: void
Definition at line 554 of file bdffontutil.c.
Referenced by main().
char* get_token (char * str, char * token, int max)
get first non space containing string Skip spaces at start of string
return next token
Parameters
in *str string
out *token token characters greter then space less then 0x7f
in max maximum length of token
Returns
: string pointer to character after token
Definition at line 209 of file bdffontutil.c.
Referenced by ReadBdf().
void InitFonts (_font * font)
Initialize all font structures to reset states.
Parameters
in *font Font pointer
Returns
: void
Definition at line 512 of file bdffontutil.c.
Referenced by ReadBdf().
void InitNames (void)
Reset File and Structure names.
Returns
: void
Definition at line 491 of file bdffontutil.c.
int ishex (int c)
is a character hex ASCII character
Parameters
in c character to test
Returns
: 0 .. 15 or -1 on error
Definition at line 247 of file bdffontutil.c.
Referenced by ishexstr(), and ReadBdf().
int ishexstr (char * str)
Does a string only contain hex characters ?
Returns
: 1 if hex , 0 if not
Definition at line 262 of file bdffontutil.c.
Referenced by ReadBdf().
void line_wrap (char * str, int max)
Line wrap function ASSUMES we write back into the string (replace space or tab with newlines.
Parameters
in *str string to remove quotes from
in max Maximum string length
Returns
: void
Definition at line 141 of file bdffontutil.c.
char* match_token (char * str, char * pat)
Match next token against pattern.
Parameters
in str string to search
in pat pattern Skips spaces at start of string A token is any string with caracters greter then space less then 0x7f
Returns
: length of match on sucess
Definition at line 279 of file bdffontutil.c.
int ReadBdf (char * name, _font * font, int lower, int upper)
Read and parse a BDF file for specified font and character set range Fills fonts structures.
See also
: http://en.wikipedia.org/wiki/Glyph_Bitmap_Distribution_Format
Parameters
in *name BDF File name
in *font Font pointer
in lower First character
in upper Last character
Returns
: number of characters processed
Definition at line 790 of file bdffontutil.c.
Referenced by main().
char* remove_quotes (char * str)
STrip quotes from string and leading spaces.
Parameters
in *str string to remove quotes from
Returns
: char * pointer to first non-space character
Definition at line 109 of file bdffontutil.c.
Referenced by ReadBdf().
char* skip_spaces (char * str)
Skip spaces at start of string.
Parameters
in *str string to remove quotes from
Returns
: first non space character
Definition at line 193 of file bdffontutil.c.
Referenced by get_token().
char* stralloc (char * str)
Allocate memory and copy string into it.
Allocate space for string.
Parameters
in *str string to allocate and copy memory for
Returns
: char * pointer to allocated string
Definition at line 93 of file bdffontutil.c.
Referenced by AddFontName(), and ReadBdf().
void trim_tail (char * str)
Remove characters less then or equal to space from end of string.
Trim White space and control characters from end of string.
Parameters
in *str string to remove quotes from
Returns
: void
Definition at line 177 of file bdffontutil.c.
Referenced by ReadBdf(), and remove_quotes().
void WriteCharacterBits (FILE * out, _font * font, int num)
Write Font bitmap data for one charactre.
Parameters
in *out File handle
in *font Font pointer
in num character number
Returns
: void
Definition at line 721 of file bdffontutil.c.
Referenced by WriteFontBits().
void WriteFontBits (FILE * out, _font * font)
Write Font bitmap data for all characters in a font.
Parameters
in *out File handle
in *font Font pointer
Returns
: void
Definition at line 631 of file bdffontutil.c.
Referenced by Convert_Font2c(), and main().
void WriteFontBitsPreview (FILE * out, _font * font, int preview)
Write all Font characters in a font as ASCII character comments.
Parameters
in *out File handle
in *font Font pointer
in preview 1 bit bounding box, 2 Full size, 3 proportional
Returns
: void
Definition at line 2040 of file bdffontutil.c.
Referenced by main().
void WriteFontInfo (FILE * out, _font * font)
Write C Header: Font Information Summary.
Parameters
in *out File handle
in *font Font pointer
Returns
: void
Definition at line 654 of file bdffontutil.c.
Referenced by Convert_Font2c(), and main().
void WriteFontTable (FILE * out, _font * font)
Write Specification Font Table.
Parameters
in *out File handle
in *font Font pointer
Returns
: void
Definition at line 684 of file bdffontutil.c.
Referenced by Convert_Font2c(), and main().
Variable Documentation
_bdffile BDFnames[MAXFONTS]
BDF = Glyph Bitmap Distribution Format
See also
http://en.wikipedia.org/wiki/Glyph_Bitmap_Distribution_Format
Definition at line 51 of file bdffontutil.c.
Referenced by main().
char* EMPTY = ``
Definition at line 55 of file bdffontutil.c.
Referenced by db_free(), and InitFonts().
char* fnames[MAXFONTS]
Definition at line 53 of file bdffontutil.c.
Referenced by InitNames(), and main().