fonts/bdffontutil.h File Reference
par BDF font utils for BDF to C code converter Displays fonts generated by bdffont2c BDF to C code converter BDF = Glyph Bitmap Distribution Format The code handles fixed, proportional and bounding box format fonts
Macros
#define MATCH(a, b) ((strcmp(a,b) == 0) ? 1 : 0)
#define MAXLINE 1024
Functions
void * db_calloc (size_t size)
calloc memory or error exit
void * db_free (void *p)
free memory
char * stralloc (char *str)
Allocate memory and copy string into it.
char * remove_quotes (char *str)
STrip quotes from string and leading spaces.
void line_wrap (char *str, int max)
Line wrap function ASSUMES we write back into the string (replace space or tab with newlines.
void trim_tail (char *str)
Remove characters less then or equal to space from end of string.
char * skip_spaces (char *str)
Skip spaces at start of string.
char * get_token (char *str, char *token, int max)
get first non space containing string Skip spaces at start of string
int ishex (int c)
is a character hex ASCII character
int ishexstr (char *str)
Does a string only contain hex characters ?
char * match_token (char *str, char *pat)
Match next token against pattern.
void FontHeaderInfo (FILE *out, _font *font, char *prog, char *target)
Write Font Header Information Copyright, font family, etc.
void Convert_Font2c (FILE *out, _font *font)
Convert font to C structure Writes header information, font specification, font bitmap.
void emit_number (FILE *out, char *name, int num)
Write Font Structure element as a number.
void emit_data (FILE *out, char *name, unsigned char *data, int size)
Write Font Structure element as a uint8_t value.
void emit_str (FILE *out, char *name, unsigned char *data)
Write Font Structure string.
void InitNames (void)
Reset File and Structure names.
void InitFonts (_font *font)
Initialize all font structures to reset states.
void FreeFont (_font *font)
Free font data.
void AddFontName (_font *font)
Generate the font name for this font This is based on the BDF FAMILY_NAME,WEIGHT_NAME,SLANT keywords.
int FindFontName (char *str)
Search for a font name.
void WriteFontBits (FILE *out, _font *font)
Write Font bitmap data for all charactres in font.
void WriteFontInfo (FILE *out, _font *font)
Write Information.
void WriteFontTable (FILE *out, _font *font)
Write Specification Table.
void WriteCharacterBits (FILE *out, _font *font, int num)
Write Font bitmap data for one charactre in font.
int ReadBdf (char *name, _font *font, int lower, int upper)
Read BDF file Read BDF file format.
void AdjustFontTable (_font *font)
Adjust Font offset, renormalize X and Y to 0 Readjust font bounding box.
void FontAdjustFull (_font *font)
Adjust font to full size with no offset.
void FontAdjustSmall (_font *font)
Ajust font to use smallest font bounding box for each font Can be used to converting large fixed fonts to more compact form Creates font->specs if missing. Updates font->specs with new font size and offsets.
void ComputeGapSize (_font *font)
Find gap size for proportional font (gap between characters) Searching for the smallest width feature in a font Set update font->gap Work in progress.
void bsetv (unsigned char *ptr, int addr)
bit set in byte array
void bclrv (unsigned char *ptr, int addr)
bit clear in byte array
int btestv (unsigned char *ptr, int addr)
Test bit in byte array.
int bittestxy (unsigned char *ptr, int x, int y, int w, int h)
Test bit in width * height size bit array usng x and y offsets.
void bitsetxy (unsigned char *ptr, int x, int y, int w, int h)
Set bit in width * height size bit array usng x and y offsets.
void bitclrxy (unsigned char *ptr, int x, int y, int width, int height)
Clear bit in width * height size bit array usng x and y offsets.
void FontPreview (FILE *out, _font *font, int num)
Write Font Preview bit bounding box in ASCII character comments.
void FontPreviewFull (FILE *out, _font *font, int num)
Write Font Preview as full format in ASCII character comments.
void FontPreviewProportional (FILE *out, _font *font, int num)
Write Font Preview as proportional format in ASCII character comments.
void WriteFontBitsPreview (FILE *out, _font *font, int preview)
Write all Font characters in a font as ASCII character comments.
Variables
_font font
_bdffile BDFnames [MAXFONTS]
char * fnames [MAXFONTS]
Detailed Description
par BDF font utils for BDF to C code converter Displays fonts generated by bdffont2c BDF to C code converter BDF = Glyph Bitmap Distribution Format The code handles fixed, proportional and bounding box format fonts
See Also
http://en.wikipedia.org/wiki/Glyph_Bitmap_Distribution_Format
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file bdffontutil.h.
Macro Definition Documentation
#define MATCH(a, b) ((strcmp(a,b) == 0) ? 1 : 0)
BDF = Glyph Bitmap Distribution Format See: http://en.wikipedia.org/wiki/Glyph_Bitmap_Distribution_Format
Definition at line 39 of file bdffontutil.h.
Referenced by ReadBdf().
#define MAXLINE 1024
Definition at line 40 of file bdffontutil.h.
Referenced by AddFontName(), main(), and ReadBdf().
Function Documentation
void AddFontName (_font * font)
Generate the font name for this font This is based on the BDF FAMILY_NAME,WEIGHT_NAME,SLANT keywords.
Parameters
in *font Font pointer
Returns
: void
Definition at line 580 of file bdffontutil.c.
Referenced by ReadBdf().
void AdjustFontTable (_font * font)
Adjust Font offset, renormalize X and Y to 0 Readjust font bounding box.
Parameters
in *font Font pointer
Returns
: void
Definition at line 1189 of file bdffontutil.c.
Referenced by FontAdjustSmall(), and ReadBdf().
void bclrv (unsigned char * ptr, int addr)
bit clear in byte array
Parameters
in *ptr byte array
in addr bit offset to clear
Returns
void
Definition at line 1622 of file bdffontutil.c.
void bitclrxy (unsigned char * ptr, int x, int y, int width, int height)
Clear bit in width * height size bit array usng x and y offsets.
Parameters
in *ptr byte array
in x bit x offset
in y bit y offset
in width width of bit array
in height height of bit array
Returns
void
Definition at line 1709 of file bdffontutil.c.
Referenced by FontAdjustFull(), and ReadBdf().
void bitsetxy (unsigned char * ptr, int x, int y, int w, int h)
Set bit in width * height size bit array usng x and y offsets.
Parameters
in *ptr byte array
in x bit x offset
in y bit y offset
in w width of bit array
in h height of bit array
Returns
void
Definition at line 1681 of file bdffontutil.c.
Referenced by FontAdjustFull(), FontAdjustSmall(), and ReadBdf().
int bittestxy (unsigned char * ptr, int x, int y, int w, int h)
Test bit in width * height size bit array usng x and y offsets.
Parameters
in *ptr byte array
in x bit x offset
in y bit y offset
in w the width of bit array
in h the height of bit array
Returns
1 if bit is set, 0 if not
Definition at line 1653 of file bdffontutil.c.
Referenced by ComputeGapSize(), FontAdjustFull(), FontAdjustSmall(), FontPreview(), FontPreviewFull(), and FontPreviewProportional().
void bsetv (unsigned char * ptr, int addr)
bit set in byte array
Parameters
in *ptr byte array
in addr bit offset to clear
Returns
void
Definition at line 1608 of file bdffontutil.c.
int btestv (unsigned char * ptr, int addr)
Test bit in byte array.
Parameters
in *ptr byte array
in addr bit offset to clear
Returns
1 if bit is set, 0 if not
Definition at line 1636 of file bdffontutil.c.
void ComputeGapSize (_font * font)
Find gap size for proportional font (gap between characters) Searching for the smallest width feature in a font Set update font->gap Work in progress.
Parameters
in *font Font pointer
Returns
: void
Definition at line 1521 of file bdffontutil.c.
Referenced by main(), and ReadBdf().
void Convert_Font2c (FILE * out, _font * font)
Convert font to C structure Writes header information, font specification, font bitmap.
Parameters
in *out File handle
in *font Font handle
Returns
: void
Definition at line 363 of file bdffontutil.c.
Referenced by main().
void* db_calloc (size_t size)
calloc memory or error exit
Parameters
in size memory size to calloc
Returns
: void * pointer
Definition at line 60 of file bdffontutil.c.
Referenced by FontAdjustFull(), FontAdjustSmall(), InitFonts(), ReadBdf(), and stralloc().
void* db_free (void * p)
free memory
Parameters
in *p memory pointer to free
Returns
: void * pointer
Definition at line 76 of file bdffontutil.c.
Referenced by FontAdjustFull(), FontAdjustSmall(), and FreeFont().
void emit_data (FILE * out, char * name, unsigned char * data, int size)
Write Font Structure element as a uint8_t value.
Parameters
in *out File handle
in *name structure name
in *data data
in size size of data to write
Returns
: void
Definition at line 455 of file bdffontutil.c.
void emit_number (FILE * out, char * name, int num)
Write Font Structure element as a number.
Parameters
in *out File output handle
in *name number structure name
in num number to display
Returns
: void
Definition at line 440 of file bdffontutil.c.
Referenced by Convert_Font2c().
void emit_str (FILE * out, char * name, unsigned char * data)
Write Font Structure string.
Parameters
in *out File handle
in *name structure name
in *data string
Returns
: void
Definition at line 476 of file bdffontutil.c.
Referenced by WriteFontInfo().
int FindFontName (char * str)
Search for a font name.
Returns
: index into BDFnames[]
Definition at line 609 of file bdffontutil.c.
Referenced by main().
void FontAdjustFull (_font * font)
Adjust font to full size with no offset.
Parameters
in *font Font pointer
Returns
: void
Definition at line 1238 of file bdffontutil.c.
Referenced by main().
void FontAdjustSmall (_font * font)
Ajust font to use smallest font bounding box for each font Can be used to converting large fixed fonts to more compact form Creates font->specs if missing. Updates font->specs with new font size and offsets.
Parameters
in *font Font pointer
Returns
: void
Definition at line 1322 of file bdffontutil.c.
Referenced by main().
void FontHeaderInfo (FILE * out, _font * font, char * prog, char * target)
Write Font Header Information Copyright, font family, etc.
Parameters
in *out File handle
in *font Font handle
in *prog program name
in *target file name comments
Returns
: void
Definition at line 321 of file bdffontutil.c.
Referenced by main().
void FontPreview (FILE * out, _font * font, int num)
Write Font Preview bit bounding box in ASCII character comments.
Parameters
in *out File handle
in *font Font pointer
in num Font character
Returns
: void
Definition at line 1736 of file bdffontutil.c.
Referenced by WriteFontBitsPreview().
void FontPreviewFull (FILE * out, _font * font, int num)
Write Font Preview as full format in ASCII character comments.
Parameters
in *out File handle
in *font Font pointer
in num Font character
Returns
: void
Definition at line 1819 of file bdffontutil.c.
Referenced by WriteFontBitsPreview().
void FontPreviewProportional (FILE * out, _font * font, int num)
Write Font Preview as proportional format in ASCII character comments.
Parameters
in *out File handle
in *font Font pointer
in num Font character
Returns
: void
Definition at line 1921 of file bdffontutil.c.
Referenced by WriteFontBitsPreview().
void FreeFont (_font * font)
Free font data.
Parameters
in *font Font pointer
Returns
: void
Definition at line 552 of file bdffontutil.c.
Referenced by main().
char* get_token (char * str, char * token, int max)
get first non space containing string Skip spaces at start of string
Parameters
in *str string
out *token token characters greter then space less then 0x7f
in max maximum length of token
Returns
: string pointer to character after token
Definition at line 207 of file bdffontutil.c.
Referenced by ReadBdf().
void InitFonts (_font * font)
Initialize all font structures to reset states.
Parameters
in *font Font pointer
Returns
: void
Definition at line 510 of file bdffontutil.c.
Referenced by ReadBdf().
void InitNames (void)
Reset File and Structure names.
Returns
: void
Definition at line 489 of file bdffontutil.c.
int ishex (int c)
is a character hex ASCII character
Parameters
in c character to test
Returns
: 0 .. 15 or -1 on error
Definition at line 245 of file bdffontutil.c.
Referenced by ishexstr(), and ReadBdf().
int ishexstr (char * str)
Does a string only contain hex characters ?
Returns
: 1 if hex , 0 if not
Definition at line 260 of file bdffontutil.c.
Referenced by ReadBdf().
void line_wrap (char * str, int max)
Line wrap function ASSUMES we write back into the string (replace space or tab with newlines.
Parameters
in *str string to remove quotes from
in max Maximum string length
Returns
: void
Definition at line 139 of file bdffontutil.c.
char* match_token (char * str, char * pat)
Match next token against pattern.
Parameters
in str string to search
in pat pattern Skips spaces at start of string A token is any string with caracters greter then space less then 0x7f
Returns
: length of match on sucess
Definition at line 277 of file bdffontutil.c.
int ReadBdf (char * name, _font * font, int lower, int upper)
Read BDF file Read BDF file format.
See Also
: http://en.wikipedia.org/wiki/Glyph_Bitmap_Distribution_Format
Parameters
in *name BDF File name
in *font Font pointer
in lower First character
in upper Last character
Returns
: number of characters processed
Definition at line 788 of file bdffontutil.c.
Referenced by main().
char* remove_quotes (char * str)
STrip quotes from string and leading spaces.
Parameters
in *str string to remove quotes from
Returns
: char * pointer to first non-space character
Definition at line 107 of file bdffontutil.c.
Referenced by ReadBdf().
char* skip_spaces (char * str)
Skip spaces at start of string.
Parameters
in *str string to remove quotes from
Returns
: first non space character
Definition at line 191 of file bdffontutil.c.
Referenced by get_token().
char* stralloc (char * str)
Allocate memory and copy string into it.
Parameters
in *str string to allocate and copy memory for
Returns
: char * pointer to allocated string
Definition at line 91 of file bdffontutil.c.
Referenced by AddFontName(), main(), and ReadBdf().
void trim_tail (char * str)
Remove characters less then or equal to space from end of string.
Parameters
in *str string to remove quotes from
Returns
: void
Definition at line 175 of file bdffontutil.c.
Referenced by ReadBdf(), and remove_quotes().
void WriteCharacterBits (FILE * out, _font * font, int num)
Write Font bitmap data for one charactre in font.
Parameters
in *out File handle
in *font Font pointer
in num character number
Returns
: void
Definition at line 719 of file bdffontutil.c.
Referenced by WriteFontBits().
void WriteFontBits (FILE * out, _font * font)
Write Font bitmap data for all charactres in font.
Parameters
in *out File handle
in *font Font pointer
Returns
: void
Definition at line 629 of file bdffontutil.c.
Referenced by Convert_Font2c(), and main().
void WriteFontBitsPreview (FILE * out, _font * font, int preview)
Write all Font characters in a font as ASCII character comments.
Parameters
in *out File handle
in *font Font pointer
in preview 1 bit bounding box, 2 Full size, 3 proportional
Returns
: void
Definition at line 2023 of file bdffontutil.c.
Referenced by main().
void WriteFontInfo (FILE * out, _font * font)
Write Information.
Parameters
in *out File handle
in *font Font pointer
Returns
: void
Definition at line 652 of file bdffontutil.c.
Referenced by Convert_Font2c(), and main().
void WriteFontTable (FILE * out, _font * font)
Write Specification Table.
Parameters
in *out File handle
in *font Font pointer
Returns
: void
Definition at line 682 of file bdffontutil.c.
Referenced by Convert_Font2c(), and main().
Variable Documentation
_bdffile BDFnames[MAXFONTS]
BDF = Glyph Bitmap Distribution Format
See Also
http://en.wikipedia.org/wiki/Glyph_Bitmap_Distribution_Format
Definition at line 49 of file bdffontutil.c.
Referenced by main().
char* fnames[MAXFONTS]
Definition at line 51 of file bdffontutil.c.
Referenced by InitNames(), and main().
_font font