bridge/bridge.c File Reference
Serial bridge.
#include `user_config.h`
*
#include `bridge.h`
*
Functions
static ICACHE_FLASH_ATTR void tcp_accept (struct espconn *esp_config, esp_tcp *esp_tcp_config, uint16_t port, void(*connect_callback)(struct espconn *))
Accept an incomming connection, setup connect_callback.
static ICACHE_FLASH_ATTR void tcp_data_sent_callback (void *arg)
Network transmit finished callback function.
static ICACHE_FLASH_ATTR void tcp_data_receive_callback (void *arg, char *data, uint16_t length)
Network receive callback function.
static ICACHE_FLASH_ATTR void tcp_data_disconnect_callback (void *arg)
Network disconnect callback function.
static ICACHE_FLASH_ATTR void tcp_data_connect_callback (struct espconn *new_connection)
incomming connection setup callbacks
ICACHE_FLASH_ATTR bridge_task_init (int port)
Serial Bridge task initialize.
static ICACHE_FLASH_ATTR void bridge_task (os_event_t *events)
Main serial bridge task.
Variables
os_event_t bridge_task_queue [bridge_task_queue_length]
ESP8266 OS task queue.
queue_t * uart_send_queue
uart send queue
queue_t * uart_receive_queue
uart receive queue
static char * tcp_data_send_buffer
TCP send buffer.
static char tcp_data_send_buffer_busy
TCP send buffer busy flag.
static struct espconn * esp_data_tcp_connection
network connection
Detailed Description
Serial bridge.
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
Please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file bridge.c.
Function Documentation
static ICACHE_FLASH_ATTR void bridge_task (os_event_t * events) [static]
Main serial bridge task.
Parameters
in *events event signal message strurture - not used
Returns
void
Definition at line 191 of file bridge.c.
Referenced by bridge_task_init().
ICACHE_FLASH_ATTR bridge_task_init (int port)
Serial Bridge task initialize.
Parameters
in port network port
Definition at line 159 of file bridge.c.
Referenced by user_init().
static ICACHE_FLASH_ATTR void tcp_accept (struct espconn * esp_config, esp_tcp * esp_tcp_config, uint16_t port, void(*)(struct espconn *) connect_callback) [static]
Accept an incomming connection, setup connect_callback.
Parameters
in *esp_config,ESP8266 network type an mode configuration structure
in *esp_tcp_config,network protocol structure
in port,network port to listen on
in connect_callback connection callback function pointer
Returns
void
Definition at line 56 of file bridge.c.
Referenced by bridge_task_init().
static ICACHE_FLASH_ATTR void tcp_data_connect_callback (struct espconn * new_connection) [static]
incomming connection setup callbacks
Parameters
in *new_connection
Returns
void
Definition at line 134 of file bridge.c.
Referenced by bridge_task_init().
static ICACHE_FLASH_ATTR void tcp_data_disconnect_callback (void * arg) [static]
Network disconnect callback function.
Parameters
in *arg unused
Returns
void
Definition at line 122 of file bridge.c.
Referenced by tcp_data_connect_callback().
static ICACHE_FLASH_ATTR void tcp_data_receive_callback (void * arg, char * data, uint16_t length) [static]
Network receive callback function.
Parameters
in *arg unused
in *data Data received
in length Length of data received
Returns
void
Definition at line 92 of file bridge.c.
Referenced by tcp_data_connect_callback().
static ICACHE_FLASH_ATTR void tcp_data_sent_callback (void * arg) [static]
Network transmit finished callback function.
Parameters
in *arg unused
Returns
void
Definition at line 77 of file bridge.c.
Referenced by tcp_data_connect_callback().
Variable Documentation
os_event_t bridge_task_queue[bridge_task_queue_length]
ESP8266 OS task queue.
Definition at line 30 of file bridge.c.
Referenced by bridge_task_init().
struct espconn* esp_data_tcp_connection [static]
network connection
Definition at line 45 of file bridge.c.
Referenced by bridge_task(), bridge_task_init(), tcp_data_connect_callback(), and tcp_data_disconnect_callback().
char* tcp_data_send_buffer [static]
TCP send buffer.
Definition at line 39 of file bridge.c.
Referenced by bridge_task(), and bridge_task_init().
char tcp_data_send_buffer_busy [static]
TCP send buffer busy flag.
Definition at line 41 of file bridge.c.
Referenced by bridge_task(), tcp_data_connect_callback(), and tcp_data_sent_callback().
queue_t* uart_receive_queue
uart receive queue
See Also
queue.c
Definition at line 37 of file bridge.c.
queue_t* uart_send_queue
uart send queue
uart send and receive queue,
See Also
queue.c
Definition at line 34 of file bridge.c.