driver/cal_dex.c File Reference
Data Structures
struct ex_regs
Macros
#define CAL_DEX_VERSION `0.1`
#define CAL_DEX_DUMP_FORMAT `0.1`
#define L(x) (((unsigned int)(x)) & 0xFFFF)
#define USE_ETS_PRINTF 1
#define c_puts(a) cal_tprintf(a)
#define cal_tprintf printf
#define NUM 8
Functions
void * __real__xtos_set_exception_handler (int exno, void(*exhandler)())
char * system_get_sdk_version ()
static void cal_dex_handler (int exccause, ex_regs regs)
void ets_uart_printf (char *fmt,...)
void cal_dex_dump_hex (int *p, int cnt)
int stackok (int *sp)
void cal_dex_dump_stack (int *sp)
static int get_excvaddr ()
static int get_depc ()
void cal_dex_dump (int *sp)
void * __wrap__xtos_set_exception_handler (int exno, void(*exhandler)())
Variables
char _text_start
char _text_end
char _rodata_start
char _rodata_end
char _data_start
char _data_end
char _bss_start
char _bss_end
static void(* orighandler)(int code)
Macro Definition Documentation
#define c_puts(a) cal_tprintf(a)
Definition at line 60 of file cal_dex.c.
Referenced by __wrap__xtos_set_exception_handler(), cal_dex_dump(), cal_dex_dump_hex(), and cal_dex_dump_stack().
#define CAL_DEX_DUMP_FORMAT `0.1`
Definition at line 8 of file cal_dex.c.
Referenced by cal_dex_dump().
#define CAL_DEX_VERSION `0.1`
cal_dex 0.1
Debug exception support. (20150421, cal)
Definition at line 7 of file cal_dex.c.
Referenced by cal_dex_dump().
#define cal_tprintf printf
Definition at line 63 of file cal_dex.c.
Referenced by cal_dex_dump(), and cal_dex_dump_stack().
#define L(x) (((unsigned int)(x)) & 0xFFFF)
Definition at line 54 of file cal_dex.c.
Referenced by cal_dex_dump(), clock_set(), clock_settime(), clock_task(), ctime_gm(), gettimeofday(), gmtime_r(), localtime_r(), main(), mktime(), rewind(), setdate_r(), settimeofday(), setup(), subtract_timespec(), and timegm().
#define NUM 8
Definition at line 122 of file cal_dex.c.
Referenced by cal_dex_dump_hex().
#define USE_ETS_PRINTF 1
Definition at line 57 of file cal_dex.c.
Function Documentation
void* __real__xtos_set_exception_handler (int exno, void(*)() exhandler)
Referenced by __wrap__xtos_set_exception_handler().
void* __wrap__xtos_set_exception_handler (int exno, void(*)() exhandler)
This intercepts calls to _xtos_set_exception_handler which is reached via symbol __real__xtos_set_exception_handler.
Calls to exception handler are intercepted by cal_dex_handler before delegating to original handler.
Definition at line 359 of file cal_dex.c.
void cal_dex_dump (int * sp)
Definition at line 217 of file cal_dex.c.
Referenced by cal_dex_handler().
void cal_dex_dump_hex (int * p, int cnt)
Definition at line 126 of file cal_dex.c.
Referenced by cal_dex_dump_stack().
void cal_dex_dump_stack (int * sp)
Definition at line 162 of file cal_dex.c.
Referenced by cal_dex_dump().
void cal_dex_handler (int exccause, ex_regs regs) [static]
Definition at line 329 of file cal_dex.c.
Referenced by __wrap__xtos_set_exception_handler(), and cal_dex_dump().
void ets_uart_printf (char * fmt, ...)
Referenced by tft_readRegister().
static int get_depc () [static]
Definition at line 205 of file cal_dex.c.
Referenced by cal_dex_dump().
static int get_excvaddr () [static]
Definition at line 194 of file cal_dex.c.
Referenced by cal_dex_dump().
int stackok (int * sp)
Definition at line 154 of file cal_dex.c.
Referenced by cal_dex_dump(), and cal_dex_dump_stack().
char* system_get_sdk_version ()
Referenced by cal_dex_dump().
Variable Documentation
char _bss_end
char _bss_start
char _data_end
char _data_start
char _rodata_end
char _rodata_start
char _text_end
char _text_start
void(* orighandler) (int code) [static]
Definition at line 51 of file cal_dex.c.
Referenced by __wrap__xtos_set_exception_handler(), and cal_dex_handler().