yield/cont_util.c File Reference
#include `cont.h`
*
#include <stddef.h>
*
#include `ets_sys.h`
*
Macros
#define CONT_STACKGUARD 0xfeefeffe
Functions
void cont_init (cont_t *cont)
int cont_check (cont_t *cont)
bool cont_can_yield (cont_t *cont)
Macro Definition Documentation
#define CONT_STACKGUARD 0xfeefeffe
Definition at line 26 of file cont_util.c.
Referenced by cont_check(), and cont_init().
Function Documentation
bool cont_can_yield (cont_t * cont)
Definition at line 45 of file cont_util.c.
Referenced by esp_yield(), optimistic_yield(), and yield().
int cont_check (cont_t * cont)
Definition at line 37 of file cont_util.c.
Referenced by loop_task().
void cont_init (cont_t * cont)
Definition at line 28 of file cont_util.c.
Referenced by user_init().