yield/cont.h File Reference
#include <stdbool.h>
*
Data Structures
struct cont_
Macros
#define CONT_STACKSIZE 4096
Typedefs
typedef struct cont_ cont_t
Functions
void cont_init (cont_t *)
void cont_run (cont_t *, void(*pfn)(void))
void cont_yield (cont_t *)
int cont_check (cont_t *cont)
bool cont_can_yield (cont_t *cont)
Macro Definition Documentation
#define CONT_STACKSIZE 4096
Definition at line 27 of file cont.h.
Typedef Documentation
typedef struct cont_ cont_t
Function Documentation
bool cont_can_yield (cont_t * cont)
Definition at line 45 of file cont_util.c.
Referenced by esp_yield(), optimistic_yield(), and yield().
int cont_check (cont_t * cont)
Definition at line 37 of file cont_util.c.
Referenced by loop_task().
void cont_init (cont_t *)
Definition at line 28 of file cont_util.c.
Referenced by user_init().
void cont_run (cont_t * , void(*)(void) pfn)
Referenced by loop_task().
void cont_yield (cont_t *)
Referenced by esp_yield().