cordic/cordic.c File Reference
Cordic Routines Handle angle outside of the first quadrant Added standalone test to verify CORDIC against math library Add Documenation and references.
#include <user_config.h>
*
#include <math.h>
*
#include `cordic.h`
*
#include `cordic2c_inc.h`
*
Macros
#define CORDIC_TABLE /* include the generated cordic table */
Functions
MEMSPACE double deg2rad (double d)
Convert Degrees to Rads.
double angle_quad (double quads, int *quad)
Compute quadrant of angle and the quadrant modulus Note: Integer part is quadrant.
void Circular (Cordic_T x, Cordic_T y, Cordic_T z)
MEMSPACE void cordic_quad (double angle, double *s, double *c)
Compute Sin and Cos from angle in quads using Cordic.
MEMSPACE void cordic_deg (double deg, double *s, double *c)
Compute Sin and Cos from angle in degrees using Cordic.
MEMSPACE void cordic_rad (double rad, double *s, double *c)
Compute Sin and Cos from angle in rads using Cordic.
MEMSPACE void scale_point (point *P, double scale)
Scale x,y,z by scale factor.
MEMSPACE void shift_point (point *P, point *shift)
Shift x,y,z by shift.
MEMSPACE void rotate (point *P, point *V)
Rotate point P by View point.
MEMSPACE void PerspectiveProjection (point *P, double scale, int x, int y)
Variables
Cordic_T X
Main Cordic rountine - used for basic trig and vector rotations We use fixed point numbers, where 1.0=Cordic_One cordic.h.
Cordic_T Y
Cordic_T Z
Detailed Description
Cordic Routines Handle angle outside of the first quadrant Added standalone test to verify CORDIC against math library Add Documenation and references. Cordic Code Modified by Mike Gore 2015 to generate C Cordic tables The code has been adjusted to quads (Where 90 degrees = 1.0) The angle is just the fractional part of a floating point number The interger part is the quadrant. This makes computations for code using the tables much faster.
See Also
http://en.wikipedia.org/wiki/CORDIC
cordic.h, we use fixed point numbers, where 1.0=Cordic_One Note: 1.0 = 90 degrees
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Orginal Documentation
CORDIC algorithms. The original code was published in Docter Dobbs Journal issue ddj9010. The ddj version can be obtained using FTP from SIMTEL and other places.
Converted to ANSI-C (with prototypes) by P. Knoppers, 13-Apr-1992.
The main advantage of the CORDIC algorithms is that all commonly used math functions ([a]sin[h] [a]cos[h] [a]tan[h] atahh ln exp sqrt) are implemented using only shift, add, subtract and compare. All values are treated as integers. Actually they are fixed point doubleing point values. The position of the fixed point is a compile time constant (Cordic_T_FractionBits). I don't believe that this can be easily fixed...
Some initialization of internal tables and constants is necessary before all functions can be used. The constant `Cordic_HalfPI` must be determined before compile time, all others are computed during run-time - see main() below.
Of course, any serious implementation of these functions should probably have all constants determined sometime before run-time and most functions might be written in assembler.
The layout of the code is adapted to my personal preferences. PK.
Definition in file cordic.c.
Macro Definition Documentation
#define CORDIC_TABLE /* include the generated cordic table */
Definition at line 35 of file cordic.c.
Function Documentation
double angle_quad (double quads, int * quad)
Compute quadrant of angle and the quadrant modulus Note: Integer part is quadrant.
See Also
cordic.h, we use fixed point numbers, where 1.0=Cordic_One Note: 1.0 = 90 degrees
Parameters
in quads 1.0 = 90 degrees
out quad quadrant 0 = 0 .. 89.9999, 1 = 90 ... 179.999 ..., etc
Returns
fractional part of quads
Definition at line 67 of file cordic.c.
Referenced by cordic_quad().
void Circular (Cordic_T x, Cordic_T y, Cordic_T z)
Definition at line 99 of file cordic.c.
Referenced by cordic_quad().
MEMSPACE void cordic_deg (double deg, double * s, double * c)
Compute Sin and Cos from angle in degrees using Cordic.
See Also
http://en.wikipedia.org/wiki/CORDIC
Parameters
in deg angle in degrees
in,out *s sin
in,out *c cos
Returns
void
Definition at line 211 of file cordic.c.
Referenced by rotate().
MEMSPACE void cordic_quad (double angle, double * s, double * c)
Compute Sin and Cos from angle in quads using Cordic.
See Also
http://en.wikipedia.org/wiki/CORDIC
Parameters
in angle angle in quads (1 quad = 90 degrees)
out *s sin
out *c cos
Returns
void
Definition at line 140 of file cordic.c.
Referenced by cordic_deg(), and cordic_rad().
MEMSPACE void cordic_rad (double rad, double * s, double * c)
Compute Sin and Cos from angle in rads using Cordic.
See Also
http://en.wikipedia.org/wiki/CORDIC
Parameters
in rad angle in radians
out *s sin
out *c cos
Returns
void
Definition at line 224 of file cordic.c.
MEMSPACE double deg2rad (double d)
Convert Degrees to Rads.
Parameters
in d degrees
Returns
radians
Definition at line 53 of file cordic.c.
MEMSPACE void PerspectiveProjection (point * P, double scale, int x, int y)
Definition at line 306 of file cordic.c.
Referenced by wire_draw().
MEMSPACE void rotate (point * P, point * V)
Rotate point P by View point.
Parameters
in *P x,y,z point
in *V View point
Returns
void
Definition at line 261 of file cordic.c.
Referenced by wire_draw().
MEMSPACE void scale_point (point * P, double scale)
Scale x,y,z by scale factor.
Parameters
in *P x,y,z point
in scale scale factor
Returns
void
Definition at line 235 of file cordic.c.
MEMSPACE void shift_point (point * P, point * shift)
Shift x,y,z by shift.
Parameters
in *P x,y,z point
in shift shift to apply to x,y,z
Returns
void
Definition at line 248 of file cordic.c.
Variable Documentation
Cordic_T X
Main Cordic rountine - used for basic trig and vector rotations We use fixed point numbers, where 1.0=Cordic_One cordic.h.
See Also
http://en.wikipedia.org/wiki/CORDIC
Parameters
in,out x in: Cordik_K, out: Cos of z
in,out y in: 0, out: Sin of z
in,out z in: fixed point version of angle in quads, out: not used
Returns
void
Definition at line 98 of file cordic.c.
Referenced by AdjustFontTable(), Circular(), cordic_quad(), and FontAdjustSmall().
Cordic_T Y
Definition at line 98 of file cordic.c.
Referenced by AdjustFontTable(), Circular(), cordic_quad(), and FontAdjustSmall().
Cordic_T Z
Definition at line 98 of file cordic.c.
Referenced by Circular().