cube/cube.c File Reference
#include `user_config.h`
*
#include <math.h>
*
#include `cube.h`
*
Functions
static void calcPerspectiveProjection (const int16_t *coordinate, int16_t *x, int16_t *y)
static void drawLine (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t color)
void cube_calculate (double degreeX, double degreeY, double degreeZ, double scale, int16_t shiftX, int16_t shiftY, int16_t shiftZ)
void cube_draw (uint16_t color)
Variables
static const int16_t pix [AMOUNT_NODE][3]
static int16_t newpix [AMOUNT_NODE][3]
Function Documentation
static void calcPerspectiveProjection (const int16_t * coordinate, int16_t * x, int16_t * y) [static]
Definition at line 17 of file cube.c.
Referenced by cube_draw().
void cube_calculate (double degreeX, double degreeY, double degreeZ, double scale, int16_t shiftX, int16_t shiftY, int16_t shiftZ)
Definition at line 28 of file cube.c.
Referenced by test().
void cube_draw (uint16_t color)
Definition at line 69 of file cube.c.
Referenced by test().
static void drawLine (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t color) [static]
Definition at line 23 of file cube.c.
Referenced by cube_draw().
Variable Documentation
int16_t newpix[AMOUNT_NODE][3] [static]
Definition at line 14 of file cube.c.
Referenced by cube_calculate(), and cube_draw().
const int16_t pix[AMOUNT_NODE][3] [static]
Initial value:
={{-25,-25,-25},{25,-25,-25},{25,25,-25},{-25,25,-25},
                                            {-25,-25,25}, {25,-25,25}, {25,25,25}, {-25,25,25}}
Definition at line 12 of file cube.c.
Referenced by cube_calculate().