fatfs.hal/diskio.h File Reference
#include `integer.h`
*
Data Structures
struct SDIO_CTRL
Macros
#define _USE_WRITE 1	/* 1: Enable disk_write function */
#define _USE_IOCTL 1	/* 1: Enable disk_ioctl fucntion */
#define _USE_ISDIO 1	/* 1: Enable iSDIO controls via disk_ioctl */
#define STA_NOINIT 0x01	/* Drive not initialized */
#define STA_NODISK 0x02	/* No medium in the drive */
#define STA_PROTECT 0x04	/* Write protected */
#define CTRL_SYNC 0	/* Complete pending write process (needed at _FS_READONLY == 0) */
#define GET_SECTOR_COUNT 1	/* Get media size (needed at _USE_MKFS == 1) */
#define GET_SECTOR_SIZE 2	/* Get sector size (needed at _MAX_SS != _MIN_SS) */
#define GET_BLOCK_SIZE 3	/* Get erase block size (needed at _USE_MKFS == 1) */
#define CTRL_TRIM 4	/* Inform device that the data on the block of sectors is no longer used (needed at _USE_TRIM == 1) */
#define CTRL_FORMAT 5	/* Create physical format on the media */
#define CTRL_POWER_IDLE 6	/* Put the device idle state */
#define CTRL_POWER_OFF 7	/* Put the device off state */
#define CTRL_LOCK 8	/* Lock media removal */
#define CTRL_UNLOCK 9	/* Unlock media removal */
#define CTRL_EJECT 10	/* Eject media */
#define MMC_GET_TYPE 50	/* Get card type */
#define MMC_GET_CSD 51	/* Get CSD */
#define MMC_GET_CID 52	/* Get CID */
#define MMC_GET_OCR 53	/* Get OCR */
#define MMC_GET_SDSTAT 54	/* Get SD status */
#define ISDIO_READ 55	/* Read data form SD iSDIO register */
#define ISDIO_WRITE 56	/* Write data to SD iSDIO register */
#define ISDIO_MRITE 57	/* Masked write data to SD iSDIO register */
#define ATA_GET_REV 60	/* Get F/W revision */
#define ATA_GET_MODEL 61	/* Get model name */
#define ATA_GET_SN 62	/* Get serial number */
#define CT_MMC 0x01		/* MMC ver 3 */
#define CT_SD1 0x02		/* SD ver 1 */
#define CT_SD2 0x04		/* SD ver 2 */
#define CT_SDC (CT_SD1|CT_SD2)	/* SD */
#define CT_BLOCK 0x08		/* Block addressing */
Typedefs
typedef BYTE DSTATUS
Enumerations
enum DRESULT {
*
RES_OK = 0,
RES_ERROR,
RES_WRPRT,
RES_NOTRDY,
*
RES_PARERR
 }
Functions
DSTATUS disk_initialize (BYTE pdrv)
DSTATUS disk_status (BYTE pdrv)
DRESULT disk_read (BYTE pdrv, BYTE *buff, DWORD sector, UINT count)
DRESULT disk_write (BYTE pdrv, const BYTE *buff, DWORD sector, UINT count)
DRESULT disk_ioctl (BYTE pdrv, BYTE cmd, void *buff)
void disk_timerproc (void)
Macro Definition Documentation
#define _USE_IOCTL 1	/* 1: Enable disk_ioctl fucntion */
Definition at line 13 of file diskio.h.
#define _USE_ISDIO 1	/* 1: Enable iSDIO controls via disk_ioctl */
Definition at line 14 of file diskio.h.
#define _USE_WRITE 1	/* 1: Enable disk_write function */
Definition at line 12 of file diskio.h.
#define ATA_GET_MODEL 61	/* Get model name */
Definition at line 87 of file diskio.h.
#define ATA_GET_REV 60	/* Get F/W revision */
Definition at line 86 of file diskio.h.
#define ATA_GET_SN 62	/* Get serial number */
Definition at line 88 of file diskio.h.
#define CT_BLOCK 0x08		/* Block addressing */
Definition at line 96 of file diskio.h.
Referenced by mmc_disk_initialize(), and mmc_disk_read().
#define CT_MMC 0x01		/* MMC ver 3 */
Definition at line 92 of file diskio.h.
Referenced by mmc_disk_initialize().
#define CT_SD1 0x02		/* SD ver 1 */
Definition at line 93 of file diskio.h.
Referenced by mmc_disk_initialize(), and mmc_disk_read().
#define CT_SD2 0x04		/* SD ver 2 */
Definition at line 94 of file diskio.h.
Referenced by mmc_disk_initialize(), and mmc_disk_read().
#define CT_SDC (CT_SD1|CT_SD2)	/* SD */
Definition at line 95 of file diskio.h.
Referenced by mmc_disk_read().
#define CTRL_EJECT 10	/* Eject media */
Definition at line 73 of file diskio.h.
#define CTRL_FORMAT 5	/* Create physical format on the media */
Definition at line 68 of file diskio.h.
#define CTRL_LOCK 8	/* Lock media removal */
Definition at line 71 of file diskio.h.
#define CTRL_POWER_IDLE 6	/* Put the device idle state */
Definition at line 69 of file diskio.h.
#define CTRL_POWER_OFF 7	/* Put the device off state */
Definition at line 70 of file diskio.h.
Referenced by mmc_disk_read().
#define CTRL_SYNC 0	/* Complete pending write process (needed at _FS_READONLY == 0) */
Definition at line 61 of file diskio.h.
Referenced by f_mkfs(), mmc_disk_read(), and sync_fs().
#define CTRL_TRIM 4	/* Inform device that the data on the block of sectors is no longer used (needed at _USE_TRIM == 1) */
Definition at line 65 of file diskio.h.
Referenced by f_mkfs(), mmc_disk_read(), and remove_chain().
#define CTRL_UNLOCK 9	/* Unlock media removal */
Definition at line 72 of file diskio.h.
#define GET_BLOCK_SIZE 3	/* Get erase block size (needed at _USE_MKFS == 1) */
Definition at line 64 of file diskio.h.
Referenced by f_mkfs(), mmc_disk_read(), and mmc_init().
#define GET_SECTOR_COUNT 1	/* Get media size (needed at _USE_MKFS == 1) */
Definition at line 62 of file diskio.h.
Referenced by f_mkfs(), and mmc_disk_read().
#define GET_SECTOR_SIZE 2	/* Get sector size (needed at _MAX_SS != _MIN_SS) */
Definition at line 63 of file diskio.h.
Referenced by f_mkfs(), and find_volume().
#define ISDIO_MRITE 57	/* Masked write data to SD iSDIO register */
Definition at line 83 of file diskio.h.
Referenced by mmc_disk_read().
#define ISDIO_READ 55	/* Read data form SD iSDIO register */
Definition at line 81 of file diskio.h.
Referenced by mmc_disk_read().
#define ISDIO_WRITE 56	/* Write data to SD iSDIO register */
Definition at line 82 of file diskio.h.
Referenced by mmc_disk_read().
#define MMC_GET_CID 52	/* Get CID */
Definition at line 78 of file diskio.h.
Referenced by mmc_disk_read().
#define MMC_GET_CSD 51	/* Get CSD */
Definition at line 77 of file diskio.h.
Referenced by mmc_disk_read().
#define MMC_GET_OCR 53	/* Get OCR */
Definition at line 79 of file diskio.h.
Referenced by mmc_disk_read().
#define MMC_GET_SDSTAT 54	/* Get SD status */
Definition at line 80 of file diskio.h.
Referenced by mmc_disk_read().
#define MMC_GET_TYPE 50	/* Get card type */
Definition at line 76 of file diskio.h.
Referenced by mmc_disk_read().
#define STA_NODISK 0x02	/* No medium in the drive */
Definition at line 54 of file diskio.h.
Referenced by mmc_disk_initialize(), mmc_disk_timerproc(), and mmc_test_timeout().
#define STA_NOINIT 0x01	/* Drive not initialized */
Definition at line 53 of file diskio.h.
Referenced by disk_initialize(), disk_status(), f_mkfs(), find_volume(), mmc_disk_initialize(), mmc_disk_read(), mmc_disk_timerproc(), mmc_test_timeout(), and validate().
#define STA_PROTECT 0x04	/* Write protected */
Definition at line 55 of file diskio.h.
Referenced by f_mkfs(), find_volume(), mmc_disk_read(), and mmc_disk_timerproc().
Typedef Documentation
typedef BYTE DSTATUS
Definition at line 20 of file diskio.h.
Enumeration Type Documentation
enum DRESULT
Enumerator
RES_OK
RES_ERROR
RES_WRPRT
RES_NOTRDY
RES_PARERR
Definition at line 23 of file diskio.h.
Function Documentation
DSTATUS disk_initialize (BYTE pdrv)
Definition at line 53 of file diskio.c.
Referenced by f_mkfs(), find_volume(), and mmc_init().
DRESULT disk_ioctl (BYTE pdrv, BYTE cmd, void * buff)
Definition at line 130 of file diskio.c.
Referenced by f_mkfs(), find_volume(), mmc_init(), remove_chain(), and sync_fs().
DRESULT disk_read (BYTE pdrv, BYTE * buff, DWORD sector, UINT count)
Definition at line 76 of file diskio.c.
Referenced by f_expand(), f_lseek(), f_mkfs(), f_open(), f_read(), f_write(), and move_window().
DSTATUS disk_status (BYTE pdrv)
Definition at line 30 of file diskio.c.
Referenced by find_volume(), and validate().
void disk_timerproc (void)
Definition at line 156 of file diskio.c.
DRESULT disk_write (BYTE pdrv, const BYTE * buff, DWORD sector, UINT count)
Definition at line 103 of file diskio.c.
Referenced by f_expand(), f_lseek(), f_mkfs(), f_read(), f_sync(), f_truncate(), f_write(), sync_fs(), and sync_window().