fatfs/disk.h File Reference
Allocate, Free and display FILINFO structurs, getfattime(), display error messages.
#include <stdint.h>
*
#include <stdarg.h>
*
#include <string.h>
*
#include <math.h>
*
#include `mmc_hal.h`
*
#include `ff.h`
*
#include `diskio.h`
*
Functions
MEMSPACE uint32_t tm_to_fat (tm_t *t)
FAT time structer reference.
MEMSPACE DWORD get_fattime (void)
Read DS1307 RTC and convert to FAT32 time.
MEMSPACE void put_rc (int rc)
display FatFs return code as ascii string
MEMSPACE FILINFO * fatfs_alloc_finfo (int allocate)
Allocate FILINFO structure and optional long file name buffer.
MEMSPACE void fatfs_free_filinfo (FILINFO *finfo)
Free a FILINFO structure and optional long file name buffer allocated by fatfs_alloc_finfo()
MEMSPACE int fatfs_scan_files (char *path)
Compute space used, number of directories and files contained under a specified directory.
MEMSPACE void fatfs_status (char *ptr)
Compute space used, number of directories and files contained used by a drive.
MEMSPACE void fatfs_filinfo_list (FILINFO *info)
Display FILINFO structure in a readable format.
Variables
DWORD AccSize
Total file space used.
WORD AccFiles
Total number or Files and Directories.
WORD AccDirs
FATFS Fatfs [_VOLUMES]
FatFs Drive Volumes.
Detailed Description
Allocate, Free and display FILINFO structurs, getfattime(), display error messages.
Copyright 2015 Mike Gore, GPL License
Copyright 2013 ChaN.
Credit: part of FatFs avr example project (C)ChaN, 2013.
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
MEMSPACE FILINFO* fatfs_alloc_finfo (int allocate)
Allocate FILINFO structure and optional long file name buffer.
Parameters
in allocate If allocate is true use calloc otherwise return static __finfo
See also
fatfs_free_finfo()
fatfs_scan_files()
fatfs_ls()
Returns
FILINFO * on success
NULL on error
Definition at line 175 of file disk.c.
Referenced by fatfs_ls(), fatfs_scan_files(), fatfs_stat(), and stat().
MEMSPACE void fatfs_filinfo_list (FILINFO * info)
Display FILINFO structure in a readable format.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Example:
/// ----A 2014/10/16 00:39        14    test2.txt  
/// D---- 2014/10/12 21:29         0          tmp 
/// 
@param[in] : FILINFO pointer
@return  void  
Definition at line 371 of file disk.c.
Referenced by fatfs_ls(), and fatfs_stat().
MEMSPACE void fatfs_free_filinfo (FILINFO * finfo)
Free a FILINFO structure and optional long file name buffer allocated by fatfs_alloc_finfo()
Parameters
in finfo FatFs FILINFO pointer to free
See also
fatfs_alloc_finfo()
fatfs_scan_files()
fatfs_ls()
Returns
void
Definition at line 225 of file disk.c.
MEMSPACE int fatfs_scan_files (char * path)
Compute space used, number of directories and files contained under a specified directory.
Credit: part of FatFs avr example project (C)ChaN, 2013
Parameters
in path
See also
f_opendir()
f_readdir()
AccDirs: Total number of directories
AccFiles: Total number of Files
AccSize: Total size of all files
Returns
0 if no error
FafFs error code
Definition at line 254 of file disk.c.
Referenced by fatfs_scan_files(), and fatfs_status().
MEMSPACE void fatfs_status (char * ptr)
Compute space used, number of directories and files contained used by a drive.
Credit: part of FatFs avr example project (C)ChaN, 2013
Parameters
in ptr Drive path like `/`
See also
f_getfree() drive free space
fatfs_scan_files()
AccDirs: Total number of directories
AccFiles: Total number of Files
AccSize: Total size of all files
Returns
void
Definition at line 319 of file disk.c.
Referenced by fatfs_tests(), mmc_init(), and mmc_test().
MEMSPACE DWORD get_fattime (void)
Read DS1307 RTC and convert to FAT32 time.
Returns
FAT32 time.
See also
tm_to_fat().
Definition at line 124 of file disk.c.
MEMSPACE void put_rc (int rc)
display FatFs return code as ascii string
Credit: Part of FatFs avr example project (C)ChaN, 2013
Parameters
in rc FatFs status return code
Returns
void
Definition at line 139 of file disk.c.
Referenced by fatfs_cat(), fatfs_cd(), fatfs_copy(), fatfs_create(), fatfs_ls(), fatfs_mkdir(), fatfs_pwd(), fatfs_rename(), fatfs_rm(), fatfs_rmdir(), fatfs_stat(), fatfs_status(), fatfs_tests(), and mmc_init().
MEMSPACE uint32_t tm_to_fat (tm_t * t)
FAT time structer reference.
See also
rtc.h
http://lxr.free-electrons.com/source/fs/fat/misc.c
/// typedef struct
/// {
///     WORD   year;                                  /* 2000..2099 */
///     BYTE   month;                                 /* 1..12 */
///     BYTE   mday;                                  /* 1.. 31 */
///     BYTE   wday;                                  /* 1..7 */
///     BYTE   hour;                                  /* 0..23 */
///     BYTE   min;                                   /* 0..59 */
///     BYTE   sec;                                   /* 0..59 */
/// } RTC;
/// 
 Convert Linux POSIX tm_t * to FAT32 time.
Parameters
in t POSIX struct tm * to convert.
Returns
FAT32 time.
Definition at line 107 of file disk.c.
Referenced by get_fattime().
Variable Documentation
WORD AccDirs
Definition at line 155 of file disk.c.
Referenced by fatfs_scan_files(), and fatfs_status().
WORD AccFiles
Total number or Files and Directories.
Definition at line 155 of file disk.c.
Referenced by fatfs_scan_files(), and fatfs_status().
DWORD AccSize
Total file space used.
Definition at line 152 of file disk.c.
Referenced by fatfs_scan_files(), and fatfs_status().
FATFS Fatfs[_VOLUMES]
FatFs Drive Volumes.
Definition at line 39 of file disk.c.
Referenced by mmc_init().