fatfs/disk.c File Reference
Allocate, Free and display FILINFO structurs, getfattime(), display error messages.
#include <user_config.h>
*
#include `ff.h`
*
#include `diskio.h`
*
#include `posix.h`
*
Functions
MEMSPACE uint32_t tm_to_fat (tm_t *t)
FAT time structer reference.
MEMSPACE DWORD get_fattime (void)
Read DS1307 RTC and convert to FAT32 time.
MEMSPACE void put_rc (int rc)
display FatFs return code as ascii string
MEMSPACE FILINFO * fatfs_alloc_finfo (int allocate)
Allocate FILINFO structure and optional long file name buffer.
MEMSPACE void fatfs_free_filinfo (FILINFO *finfo)
Free a FILINFO structure and optional long file name buffer allocated by fatfs_alloc_finfo()
MEMSPACE int fatfs_scan_files (char *path)
Compute space used, number of directories and files contained under a specified directory.
MEMSPACE void fatfs_status (char *ptr)
Compute space used, number of directories and files contained used by a drive.
MEMSPACE void fatfs_filinfo_list (FILINFO *info)
Display FILINFO structure in a readable format.
Variables
FATFS Fatfs [_VOLUMES]
FatFs Drive Volumes.
static char * err_msg []
FatFs Error Messages.
DWORD AccSize
Total file space used.
WORD AccFiles
Total number or Files and Directories.
WORD AccDirs
static FILINFO __finfo
Use were FILINFO structure can be share in many functions See: fatfs_alloc_finfo(), fatfs_scan_files() and fatfs_ls()
static char __lfname [_MAX_LFN+1]
Detailed Description
Allocate, Free and display FILINFO structurs, getfattime(), display error messages.
Copyright 2015 Mike Gore, GPL License
Copyright 2013 ChaN.
Credit: part of FatFs avr example project (C)ChaN, 2013.
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
MEMSPACE FILINFO* fatfs_alloc_finfo (int allocate)
Allocate FILINFO structure and optional long file name buffer.
Parameters
in allocate If allocate is true use calloc otherwise return static __finfo
See also
fatfs_free_finfo()
fatfs_scan_files()
fatfs_ls()
Returns
FILINFO * on success
NULL on error
Definition at line 170 of file disk.c.
Referenced by fatfs_ls(), fatfs_scan_files(), fatfs_stat(), and stat().
MEMSPACE void fatfs_filinfo_list (FILINFO * info)
Display FILINFO structure in a readable format.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Example:
/// ----A 2014/10/16 00:39        14    test2.txt  
/// D---- 2014/10/12 21:29         0          tmp 
/// 
@param[in] : FILINFO pointer
@return  void  
Definition at line 366 of file disk.c.
Referenced by fatfs_ls(), and fatfs_stat().
MEMSPACE void fatfs_free_filinfo (FILINFO * finfo)
Free a FILINFO structure and optional long file name buffer allocated by fatfs_alloc_finfo()
Parameters
in finfo FatFs FILINFO pointer to free
See also
fatfs_alloc_finfo()
fatfs_scan_files()
fatfs_ls()
Returns
void
Definition at line 220 of file disk.c.
MEMSPACE int fatfs_scan_files (char * path)
Compute space used, number of directories and files contained under a specified directory.
Credit: part of FatFs avr example project (C)ChaN, 2013
Parameters
in path
See also
f_opendir()
f_readdir()
AccDirs: Total number of directories
AccFiles: Total number of Files
AccSize: Total size of all files
Returns
0 if no error
FafFs error code
Definition at line 249 of file disk.c.
Referenced by fatfs_scan_files(), and fatfs_status().
MEMSPACE void fatfs_status (char * ptr)
Compute space used, number of directories and files contained used by a drive.
Credit: part of FatFs avr example project (C)ChaN, 2013
Parameters
in ptr Drive path like `/`
See also
f_getfree() drive free space
fatfs_scan_files()
AccDirs: Total number of directories
AccFiles: Total number of Files
AccSize: Total size of all files
Returns
void
Definition at line 314 of file disk.c.
Referenced by fatfs_tests(), mmc_init(), and mmc_test().
MEMSPACE DWORD get_fattime (void)
Read DS1307 RTC and convert to FAT32 time.
Returns
FAT32 time.
See also
tm_to_fat().
Definition at line 119 of file disk.c.
Referenced by f_mkdir(), f_mkfs(), f_open(), f_setlabel(), and f_sync().
MEMSPACE void put_rc (int rc)
display FatFs return code as ascii string
Credit: Part of FatFs avr example project (C)ChaN, 2013
Parameters
in rc FatFs status return code
Returns
void
Definition at line 134 of file disk.c.
Referenced by fatfs_cat(), fatfs_cd(), fatfs_copy(), fatfs_create(), fatfs_ls(), fatfs_mkdir(), fatfs_pwd(), fatfs_rename(), fatfs_rm(), fatfs_rmdir(), fatfs_stat(), fatfs_status(), fatfs_tests(), and mmc_init().
MEMSPACE uint32_t tm_to_fat (tm_t * t)
FAT time structer reference.
See also
rtc.h
http://lxr.free-electrons.com/source/fs/fat/misc.c
/// typedef struct
/// {
///     WORD   year;                                  /* 2000..2099 */
///     BYTE   month;                                 /* 1..12 */
///     BYTE   mday;                                  /* 1.. 31 */
///     BYTE   wday;                                  /* 1..7 */
///     BYTE   hour;                                  /* 0..23 */
///     BYTE   min;                                   /* 0..59 */
///     BYTE   sec;                                   /* 0..59 */
/// } RTC;
/// 
 Convert Linux POSIX tm_t * to FAT32 time.
Parameters
in t POSIX struct tm * to convert.
Returns
FAT32 time.
Definition at line 102 of file disk.c.
Referenced by get_fattime().
Variable Documentation
FILINFO __finfo [static]
Use were FILINFO structure can be share in many functions See: fatfs_alloc_finfo(), fatfs_scan_files() and fatfs_ls()
Definition at line 154 of file disk.c.
char __lfname[_MAX_LFN+1] [static]
Definition at line 157 of file disk.c.
Referenced by fatfs_alloc_finfo(), and fatfs_free_filinfo().
WORD AccDirs
Definition at line 150 of file disk.c.
Referenced by fatfs_scan_files(), and fatfs_status().
WORD AccFiles
Total number or Files and Directories.
Definition at line 150 of file disk.c.
Referenced by fatfs_scan_files(), and fatfs_status().
DWORD AccSize
Total file space used.
Definition at line 147 of file disk.c.
Referenced by fatfs_scan_files(), and fatfs_status().
char* err_msg[] [static]
Initial value:
=
{
    "OK",
    "DISK_ERR",
    "INT_ERR",
    "NOT_READY",
    "NO_FILE",
    "NO_PATH",
    "INVALID_NAME",
    "DENIED",
    "EXIST",
    "INVALID_OBJECT",
    "WRITE_PROTECTED",
    "INVALID_DRIVE",
    "NOT_ENABLED",
    "NO_FILE_SYSTEM",
    "MKFS_ABORTED",
    "TIMEOUT",
    "LOCKED",
    "NOT_ENOUGH_CORE",
    "TOO_MANY_OPEN_FILES",
    "INVALID_PARAMETER",
    NULL
}
FatFs Error Messages.
Credit: part of FatFs avr example project (C)ChaN, 2013
Definition at line 53 of file disk.c.
Referenced by put_rc().
FATFS Fatfs[_VOLUMES]
FatFs Drive Volumes.
Definition at line 34 of file disk.c.
Referenced by mmc_init().