display/font.h File Reference
#include `stdint.h`
*
Data Structures
struct _bdffile
struct _fontspecs
struct _fontinfo
struct _font
struct _fontc
Macros
#define MAXFONTS 256 /* Maximum number of fonts to convert at one time */
#define MAXGLYPHS 256 /* Max Glyphs Per Font */
#define MAXWIDTH 127 /* Max Character Width */
#define MAXHEIGHT 127 /* Max Character Height */
Functions
int font_attr (int c, _fontc *f, int index)
Get font attributes for a font.
int tft_drawChar (uint8_t c, uint16_t x, uint16_t y, uint8_t index)
Display a character using font tables.
Macro Definition Documentation
#define MAXFONTS 256 /* Maximum number of fonts to convert at one time */
bdffont2c BDF to C code converter
Copyright 2015 Mike Gore, Inc. All rights reserved.
Edit History
[1.0] [Mike Gore] Initial revision of file.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
bdffont2c is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/. BDF = Glyph Bitmap Distribution Format See: http://en.wikipedia.org/wiki/Glyph_Bitmap_Distribution_Format
Definition at line 35 of file font.h.
Referenced by InitNames(), and main().
#define MAXGLYPHS 256 /* Max Glyphs Per Font */
Definition at line 36 of file font.h.
Referenced by FontAdjustSmall(), and InitFonts().
#define MAXHEIGHT 127 /* Max Character Height */
Definition at line 38 of file font.h.
Referenced by FontAdjustFull(), FontAdjustSmall(), and ReadBdf().
#define MAXWIDTH 127 /* Max Character Width */
Definition at line 37 of file font.h.
Referenced by FontAdjustFull(), FontAdjustSmall(), and ReadBdf().
Function Documentation
int font_attr (int c, _fontc * f, int index)
Get font attributes for a font.
Parameters
in c character
in *f font structure
in index font index (which font table we want)
Returns
void
Definition at line 64 of file font.c.
Referenced by tft_drawCentreString(), tft_drawChar(), tft_drawRightString(), and tft_putch().
int tft_drawChar (uint8_t c, uint16_t x, uint16_t y, uint8_t index)
Display a character using font tables.
Parameters
in c character
in x X offset in pixels
in y Y offset in pixels
in index Font index (with font set to use)
Returns
void
Definition at line 138 of file font.c.
Referenced by tft_drawCentreString(), tft_drawRightString(), tft_drawString(), and tft_putch().