earth/earth.h File Reference
#include `earth_inc.h`
*
Functions
void map2fp (mapxyz *in, point *out)
void Point2Display (point *p, int *x, int *y)
void earth_draw (point *view, double scale, uint16_t color)
Function Documentation
void earth_draw (point * view, double scale, uint16_t color)
Definition at line 51 of file earth.c.
Referenced by test().
void map2fp (mapxyz * in, point * out)
Definition at line 36 of file earth.c.
Referenced by earth_draw().
void Point2Display (point * p, int * x, int * y)
Definition at line 44 of file earth.c.
Referenced by earth_draw().