earth/earth.c File Reference
DIsplay earth costline wireframe The code handles fixed, proportional and bounding box format fonts.
#include `user_config.h`
*
#include `ili9341.h`
*
#include <math.h>
*
#include `cordic.h`
*
#include `earth.h`
*
Macros
#define MAP_DATA
Functions
void map2fp (mapxyz *in, point *out)
void Point2Display (point *p, int *x, int *y)
void earth_draw (point *view, double scale, uint16_t color)
Detailed Description
DIsplay earth costline wireframe The code handles fixed, proportional and bounding box format fonts.
earth wireframe viewer
Copyright 2015 Mike Gore, GPL License
See Also
http://en.wikipedia.org/wiki/Glyph_Bitmap_Distribution_Format
Edit History
[1.0] [Mike Gore] Initial revision of file.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
earth.c is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file earth.c.
Macro Definition Documentation
#define MAP_DATA
Definition at line 28 of file earth.c.
Function Documentation
void earth_draw (point * view, double scale, uint16_t color)
Definition at line 51 of file earth.c.
Referenced by test().
void map2fp (mapxyz * in, point * out)
Definition at line 36 of file earth.c.
Referenced by earth_draw().
void Point2Display (point * p, int * x, int * y)
Definition at line 44 of file earth.c.
Referenced by earth_draw().