yield/ets_sys.h File Reference
#include `c_types.h`
*
#include `eagle_soc.h`
*
#include `stdarg.h`
*
Data Structures
struct ETSEventTag
struct _ETSTIMER_
Macros
#define ETS_SLC_INUM 1
#define ETS_SPI_INUM 2
#define ETS_GPIO_INUM 4
#define ETS_UART_INUM 5
#define ETS_UART1_INUM 5
#define ETS_CCOMPARE0_INUM 6
#define ETS_SOFT_INUM 7
#define ETS_WDT_INUM 8
#define ETS_FRC_TIMER1_INUM 9 /* use edge*/
#define ETS_INTR_LOCK() ets_intr_lock()
#define ETS_INTR_UNLOCK() ets_intr_unlock()
#define ETS_INTR_ENABLE(inum) ets_isr_unmask((1<<inum))
#define ETS_INTR_DISABLE(inum) ets_isr_mask((1<<inum))
#define ETS_CCOMPARE0_INTR_ATTACH(func, arg) ets_isr_attach(ETS_CCOMPARE0_INUM, (int_handler_t)(func), (void *)(arg))
#define ETS_CCOMPARE0_ENABLE() ETS_INTR_ENABLE(ETS_CCOMPARE0_INUM)
#define ETS_CCOMPARE0_DISABLE() ETS_INTR_DISABLE(ETS_CCOMPARE0_INUM)
#define ETS_FRC_TIMER1_INTR_ATTACH(func, arg) ets_isr_attach(ETS_FRC_TIMER1_INUM, (int_handler_t)(func), (void *)(arg))
#define ETS_FRC_TIMER1_NMI_INTR_ATTACH(func) NmiTimSetFunc(func)
#define ETS_GPIO_INTR_ATTACH(func, arg) ets_isr_attach(ETS_GPIO_INUM, (int_handler_t)(func), (void *)(arg))
#define ETS_GPIO_INTR_ENABLE() ETS_INTR_ENABLE(ETS_GPIO_INUM)
#define ETS_GPIO_INTR_DISABLE() ETS_INTR_DISABLE(ETS_GPIO_INUM)
#define ETS_UART_INTR_ATTACH(func, arg) ets_isr_attach(ETS_UART_INUM, (int_handler_t)(func), (void *)(arg))
#define ETS_UART_INTR_ENABLE() ETS_INTR_ENABLE(ETS_UART_INUM)
#define ETS_UART_INTR_DISABLE() ETS_INTR_DISABLE(ETS_UART_INUM)
#define ETS_FRC1_INTR_ENABLE() ETS_INTR_ENABLE(ETS_FRC_TIMER1_INUM)
#define ETS_FRC1_INTR_DISABLE() ETS_INTR_DISABLE(ETS_FRC_TIMER1_INUM)
#define ETS_SPI_INTR_ATTACH(func, arg) ets_isr_attach(ETS_SPI_INUM, (int_handler_t)(func), (void *)(arg))
#define ETS_SPI_INTR_ENABLE() ETS_INTR_ENABLE(ETS_SPI_INUM)
#define ETS_SPI_INTR_DISABLE() ETS_INTR_DISABLE(ETS_SPI_INUM)
#define ETS_SLC_INTR_ATTACH(func, arg) ets_isr_attach(ETS_SLC_INUM, (int_handler_t)(func), (void *)(arg))
#define ETS_SLC_INTR_ENABLE() ETS_INTR_ENABLE(ETS_SLC_INUM)
#define ETS_SLC_INTR_DISABLE() ETS_INTR_DISABLE(ETS_SLC_INUM)
Typedefs
typedef uint32_t ETSSignal
typedef uint32_t ETSParam
typedef struct ETSEventTag ETSEvent
typedef void(* ETSTask) (ETSEvent *e)
typedef uint32_t ETSHandle
typedef void ETSTimerFunc(void *timer_arg)
typedef struct _ETSTIMER_ ETSTimer
typedef void(* int_handler_t) (void *)
Functions
bool ETS_INTR_WITHINISR ()
uint32_t ETS_INTR_ENABLED (void)
uint32_t ETS_INTR_PENDING (void)
void * pvPortMalloc (size_t xWantedSize) __attribute__((malloc
void alloc_size (1)))
void * pvPortRealloc (void *ptr, size_t xWantedSize) __attribute__((alloc_size(2)))
void pvPortFree (void *ptr)
void * vPortMalloc (size_t xWantedSize) __attribute__((malloc
void vPortFree (void *ptr)
void * ets_memcpy (void *dest, const void *src, size_t n)
void * ets_memset (void *s, int c, size_t n)
void ets_timer_arm_new (ETSTimer *a, int b, int c, int isMstimer)
void ets_timer_setfn (ETSTimer *t, ETSTimerFunc *fn, void *parg)
void ets_timer_disarm (ETSTimer *a)
int atoi (const char *nptr)
Convert ASCII string to number in base 10.
int ets_strncmp (const char *s1, const char *s2, int len)
int ets_strcmp (const char *s1, const char *s2)
int ets_strlen (const char *s)
char * ets_strcpy (char *dest, const char *src)
char * ets_strncpy (char *dest, const char *src, size_t n)
char * ets_strstr (const char *haystack, const char *needle)
int ets_sprintf (char *str, const char *format,...) __attribute__((format(printf
int int os_snprintf (char *str, size_t size, const char *format,...) __attribute__((format(printf
int int int ets_printf (const char *format,...) __attribute__((format(printf
int int int void ets_install_putc1 (void *routine)
void uart_div_modify (int no, int freq)
void ets_isr_mask (int intr)
void ets_isr_unmask (int intr)
void ets_isr_attach (int intr, int_handler_t handler, void *arg)
void ets_intr_lock ()
void ets_intr_unlock ()
int ets_vsnprintf (char *s, size_t n, const char *format, va_list arg) __attribute__((format(printf
int int ets_vprintf (const char *format, va_list arg) __attribute__((format(printf
Macro Definition Documentation
#define ETS_CCOMPARE0_DISABLE() ETS_INTR_DISABLE(ETS_CCOMPARE0_INUM)
Definition at line 93 of file ets_sys.h.
#define ETS_CCOMPARE0_ENABLE() ETS_INTR_ENABLE(ETS_CCOMPARE0_INUM)
Definition at line 90 of file ets_sys.h.
#define ETS_CCOMPARE0_INTR_ATTACH(func, arg) ets_isr_attach(ETS_CCOMPARE0_INUM, (int_handler_t)(func), (void *)(arg))
Definition at line 87 of file ets_sys.h.
#define ETS_CCOMPARE0_INUM 6
Definition at line 48 of file ets_sys.h.
#define ETS_FRC1_INTR_DISABLE() ETS_INTR_DISABLE(ETS_FRC_TIMER1_INUM)
Definition at line 125 of file ets_sys.h.
#define ETS_FRC1_INTR_ENABLE() ETS_INTR_ENABLE(ETS_FRC_TIMER1_INUM)
Definition at line 122 of file ets_sys.h.
#define ETS_FRC_TIMER1_INTR_ATTACH(func, arg) ets_isr_attach(ETS_FRC_TIMER1_INUM, (int_handler_t)(func), (void *)(arg))
Definition at line 97 of file ets_sys.h.
#define ETS_FRC_TIMER1_INUM 9 /* use edge*/
Definition at line 51 of file ets_sys.h.
#define ETS_FRC_TIMER1_NMI_INTR_ATTACH(func) NmiTimSetFunc(func)
Definition at line 100 of file ets_sys.h.
#define ETS_GPIO_INTR_ATTACH(func, arg) ets_isr_attach(ETS_GPIO_INUM, (int_handler_t)(func), (void *)(arg))
Definition at line 103 of file ets_sys.h.
#define ETS_GPIO_INTR_DISABLE() ETS_INTR_DISABLE(ETS_GPIO_INUM)
Definition at line 109 of file ets_sys.h.
#define ETS_GPIO_INTR_ENABLE() ETS_INTR_ENABLE(ETS_GPIO_INUM)
Definition at line 106 of file ets_sys.h.
#define ETS_GPIO_INUM 4
Definition at line 45 of file ets_sys.h.
#define ETS_INTR_DISABLE(inum) ets_isr_mask((1<<inum))
Definition at line 62 of file ets_sys.h.
#define ETS_INTR_ENABLE(inum) ets_isr_unmask((1<<inum))
Definition at line 59 of file ets_sys.h.
#define ETS_INTR_LOCK() ets_intr_lock()
Definition at line 53 of file ets_sys.h.
#define ETS_INTR_UNLOCK() ets_intr_unlock()
Definition at line 56 of file ets_sys.h.
#define ETS_SLC_INTR_ATTACH(func, arg) ets_isr_attach(ETS_SLC_INUM, (int_handler_t)(func), (void *)(arg))
Definition at line 139 of file ets_sys.h.
#define ETS_SLC_INTR_DISABLE() ETS_INTR_DISABLE(ETS_SLC_INUM)
Definition at line 145 of file ets_sys.h.
#define ETS_SLC_INTR_ENABLE() ETS_INTR_ENABLE(ETS_SLC_INUM)
Definition at line 142 of file ets_sys.h.
#define ETS_SLC_INUM 1
Definition at line 43 of file ets_sys.h.
#define ETS_SOFT_INUM 7
Definition at line 49 of file ets_sys.h.
#define ETS_SPI_INTR_ATTACH(func, arg) ets_isr_attach(ETS_SPI_INUM, (int_handler_t)(func), (void *)(arg))
Definition at line 129 of file ets_sys.h.
#define ETS_SPI_INTR_DISABLE() ETS_INTR_DISABLE(ETS_SPI_INUM)
Definition at line 135 of file ets_sys.h.
#define ETS_SPI_INTR_ENABLE() ETS_INTR_ENABLE(ETS_SPI_INUM)
Definition at line 132 of file ets_sys.h.
#define ETS_SPI_INUM 2
Definition at line 44 of file ets_sys.h.
#define ETS_UART1_INUM 5
Definition at line 47 of file ets_sys.h.
#define ETS_UART_INTR_ATTACH(func, arg) ets_isr_attach(ETS_UART_INUM, (int_handler_t)(func), (void *)(arg))
Definition at line 113 of file ets_sys.h.
Referenced by uart_init().
#define ETS_UART_INTR_DISABLE() ETS_INTR_DISABLE(ETS_UART_INUM)
Definition at line 119 of file ets_sys.h.
Referenced by uart_callback(), and uart_init().
#define ETS_UART_INTR_ENABLE() ETS_INTR_ENABLE(ETS_UART_INUM)
Definition at line 116 of file ets_sys.h.
Referenced by uart_callback(), and uart_init().
#define ETS_UART_INUM 5
Definition at line 46 of file ets_sys.h.
#define ETS_WDT_INUM 8
Definition at line 50 of file ets_sys.h.
Typedef Documentation
typedef struct ETSEventTag ETSEvent
Definition at line 18 of file ets_sys.h.
typedef uint32_t ETSHandle
Definition at line 28 of file ets_sys.h.
typedef uint32_t ETSParam
Definition at line 16 of file ets_sys.h.
typedef uint32_t ETSSignal
Definition at line 15 of file ets_sys.h.
typedef void(* ETSTask) (ETSEvent *e)
Definition at line 25 of file ets_sys.h.
typedef struct _ETSTIMER_ ETSTimer
typedef void ETSTimerFunc(void *timer_arg)
Definition at line 29 of file ets_sys.h.
typedef void(* int_handler_t) (void *)
Definition at line 41 of file ets_sys.h.
Function Documentation
void alloc_size (1)
int atoi (const char * str)
Convert ASCII string to number in base 10.
Parameters
in str string
Returns
int value
See also
strtol
Definition at line 190 of file std.c.
Referenced by html_status(), main(), parse_http_request(), and ReadBdf().
int int int void ets_install_putc1 (void * routine)
uint32_t ETS_INTR_ENABLED (void) [inline]
Definition at line 73 of file ets_sys.h.
void ets_intr_lock ()
uint32_t ETS_INTR_PENDING (void) [inline]
Definition at line 80 of file ets_sys.h.
void ets_intr_unlock ()
bool ETS_INTR_WITHINISR () [inline]
Definition at line 65 of file ets_sys.h.
Referenced by cont_can_yield().
void ets_isr_attach (int intr, int_handler_t handler, void * arg)
void ets_isr_mask (int intr)
void ets_isr_unmask (int intr)
void* ets_memcpy (void * dest, const void * src, size_t n)
void* ets_memset (void * s, int c, size_t n)
int int int ets_printf (const char * format, ...)
int ets_sprintf (char * str, const char * format, ...)
int ets_strcmp (const char * s1, const char * s2)
char* ets_strcpy (char * dest, const char * src)
int ets_strlen (const char * s)
int ets_strncmp (const char * s1, const char * s2, int len)
char* ets_strncpy (char * dest, const char * src, size_t n)
char* ets_strstr (const char * haystack, const char * needle)
void ets_timer_arm_new (ETSTimer * a, int b, int c, int isMstimer)
void ets_timer_disarm (ETSTimer * a)
void ets_timer_setfn (ETSTimer * t, ETSTimerFunc * fn, void * parg)
int int ets_vprintf (const char * format, va_list arg)
int ets_vsnprintf (char * s, size_t n, const char * format, va_list arg)
int int os_snprintf (char * str, size_t size, const char * format, ...)
void pvPortFree (void * ptr)
void* pvPortMalloc (size_t xWantedSize)
void* pvPortRealloc (void * ptr, size_t xWantedSize)
void uart_div_modify (int no, int freq)
Referenced by uart_config().
void vPortFree (void * ptr)
void* vPortMalloc (size_t xWantedSize)