fatfs/fatfs_utils.c File Reference
fatfs test utilities with user interface
#include `user_config.h`
*
#include `posix.h`
*
#include `disk.h`
*
#include `fatfs_utils.h`
*
Functions
MEMSPACE void mmc_test (void)
Perform key FatFs diagnostics tests.
MEMSPACE void fatfs_help (void)
Display FatFs test diagnostics help menu.
MEMSPACE void fatfs_ls (char *ptr)
List files under a specified directory.
MEMSPACE void fatfs_rename (const char *oldpath, const char *newpath)
Rename a file.
MEMSPACE void fatfs_cat (char *name)
Display the contents of a file.
MEMSPACE void fatfs_copy (char *from, char *to)
Copy a file.
MEMSPACE void fatfs_create (char *name, char *str)
Create a new file from a user supplied string.
MEMSPACE void fatfs_rm (char *name)
Delete a file by name.
MEMSPACE void fatfs_mkdir (char *name)
Make a directory.
MEMSPACE void fatfs_rmdir (char *name)
Delete a directory.
MEMSPACE void fatfs_stat (char *name)
Display FILINFO status of a file by name.
MEMSPACE void fatfs_cd (char *name)
Change directory.
MEMSPACE void fatfs_pwd (void)
Display current working directory.
MEMSPACE int fatfs_tests (char *str)
FatFs test parser.
Variables
static const BYTE ft [] = {0,12,16,32}
FatFS size lookup table.
Detailed Description
fatfs test utilities with user interface
Copyright 2015 Mike Gore, GPL License
Copyright 2013 ChaN.
Credit: part of FatFs avr example project (C)ChaN, 2013.
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file fatfs_utils.c.
Function Documentation
MEMSPACE void fatfs_cat (char * name)
Display the contents of a file.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in name file name.
Returns
void.
Todo
Todo FIXME
Definition at line 181 of file fatfs_utils.c.
Referenced by fatfs_tests(), and mmc_test().
MEMSPACE void fatfs_cd (char * name)
Change directory.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in name Directory name.
Returns
void.
Definition at line 415 of file fatfs_utils.c.
Referenced by fatfs_tests(), and mmc_test().
MEMSPACE void fatfs_copy (char * from, char * to)
Copy a file.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in from source file.
in to destination file.
Returns
void.
Definition at line 244 of file fatfs_utils.c.
Referenced by fatfs_tests(), and mmc_test().
MEMSPACE void fatfs_create (char * name, char * str)
Create a new file from a user supplied string.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in name name of file to create.
in str string containing file contents.
Returns
void.
Definition at line 306 of file fatfs_utils.c.
Referenced by fatfs_tests(), and mmc_test().
MEMSPACE void fatfs_help (void)
Display FatFs test diagnostics help menu.
Returns
void
Definition at line 74 of file fatfs_utils.c.
Referenced by fatfs_tests(), and user_help().
MEMSPACE void fatfs_ls (char * ptr)
List files under a specified directory.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in ptr pathname of directory to list
See Also
fatfs_filinfo_list().
Returns
void.
Definition at line 109 of file fatfs_utils.c.
Referenced by fatfs_tests(), and mmc_test().
MEMSPACE void fatfs_mkdir (char * name)
Make a directory.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in name Directory name.
Returns
void
Definition at line 365 of file fatfs_utils.c.
Referenced by fatfs_tests(), and mmc_test().
MEMSPACE void fatfs_pwd (void)
Display current working directory.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Returns
void.
Definition at line 429 of file fatfs_utils.c.
Referenced by fatfs_tests(), and mmc_test().
MEMSPACE void fatfs_rename (const char * oldpath, const char * newpath)
Rename a file.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in oldpath old name.
in newpath new name.
Returns
void
Definition at line 161 of file fatfs_utils.c.
Referenced by fatfs_tests().
MEMSPACE void fatfs_rm (char * name)
Delete a file by name.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in name File name to delete.
Returns
void.
Definition at line 349 of file fatfs_utils.c.
Referenced by fatfs_tests().
MEMSPACE void fatfs_rmdir (char * name)
Delete a directory.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in name Directory name.
Returns
void.
Definition at line 382 of file fatfs_utils.c.
Referenced by fatfs_tests().
MEMSPACE void fatfs_stat (char * name)
Display FILINFO status of a file by name.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in name File name.
Returns
void
Definition at line 397 of file fatfs_utils.c.
Referenced by fatfs_tests().
MEMSPACE int fatfs_tests (char * str)
FatFs test parser.
Keywords and arguments are matched against fatfs test functions If ther are matched the function along with its argements are called.
Parameters
in str User supplied command line with FatFs test and arguments.
Returns
1 The ruturn code indicates a command matched.
0 if no rules matched
Definition at line 453 of file fatfs_utils.c.
Referenced by user_task().
MEMSPACE void mmc_test (void)
Perform key FatFs diagnostics tests.
Perform all basic file tests
Assumes the device is formatted
Returns
void
Definition at line 41 of file fatfs_utils.c.
Referenced by fatfs_tests().
Variable Documentation
const BYTE ft[] = {0,12,16,32} [static]
FatFS size lookup table.
Definition at line 32 of file fatfs_utils.c.
Referenced by fatfs_status().