fatfs/fatfs_utils.h File Reference
fatfs test utilities with user interface
#include <stdint.h>
*
#include <stdarg.h>
*
#include <string.h>
*
#include <math.h>
*
#include `mmc_hal.h`
*
#include `ff.h`
*
#include `diskio.h`
*
Functions
MEMSPACE void mmc_test (void)
Perform key FatFs diagnostics tests.
MEMSPACE void fatfs_help (void)
Display FatFs test diagnostics help menu.
MEMSPACE void fatfs_ls (char *ptr)
List files under a specified directory.
MEMSPACE void fatfs_rename (const char *oldpath, const char *newpath)
Rename a file.
MEMSPACE void fatfs_cat (char *name)
Display the contents of a file.
MEMSPACE void fatfs_copy (char *from, char *to)
Copy a file.
MEMSPACE void fatfs_create (char *name, char *str)
Create a new file from a user supplied string.
MEMSPACE void fatfs_rm (char *name)
Delete a file by name.
MEMSPACE void fatfs_mkdir (char *name)
Make a directory.
MEMSPACE void fatfs_rmdir (char *name)
Delete a directory.
MEMSPACE void fatfs_stat (char *name)
Display FILINFO status of a file by name.
MEMSPACE void fatfs_cd (char *name)
Change directory.
MEMSPACE void fatfs_pwd (void)
Display current working directory.
MEMSPACE int fatfs_tests (char *str)
FatFs test parser.
Detailed Description
fatfs test utilities with user interface
Copyright 2015 Mike Gore, GPL License
Copyright 2013 ChaN.
Credit: part of FatFs avr example project (C)ChaN, 2013.
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
MEMSPACE void fatfs_cat (char * name)
Display the contents of a file.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in name file name.
Returns
void.
Todo
Todo FIXME
Definition at line 187 of file fatfs_utils.c.
Referenced by fatfs_tests(), and mmc_test().
MEMSPACE void fatfs_cd (char * name)
Change directory.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in name Directory name.
Returns
void.
Definition at line 430 of file fatfs_utils.c.
Referenced by fatfs_tests(), and mmc_test().
MEMSPACE void fatfs_copy (char * from, char * to)
Copy a file.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in from source file.
in to destination file.
Returns
void.
Definition at line 250 of file fatfs_utils.c.
Referenced by fatfs_tests(), and mmc_test().
MEMSPACE void fatfs_create (char * name, char * str)
Create a new file from a user supplied string.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in name name of file to create.
in str string containing file contents.
Returns
void.
Definition at line 312 of file fatfs_utils.c.
Referenced by fatfs_tests(), and mmc_test().
MEMSPACE void fatfs_help (void)
Display FatFs test diagnostics help menu.
Returns
void
Definition at line 80 of file fatfs_utils.c.
Referenced by fatfs_tests(), and user_help().
MEMSPACE void fatfs_ls (char * ptr)
List files under a specified directory.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in ptr pathname of directory to list
See also
fatfs_filinfo_list().
Returns
void.
Definition at line 115 of file fatfs_utils.c.
Referenced by fatfs_tests(), and mmc_test().
MEMSPACE void fatfs_mkdir (char * name)
Make a directory.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in name Directory name.
Returns
void
Definition at line 371 of file fatfs_utils.c.
Referenced by fatfs_tests(), and mmc_test().
MEMSPACE void fatfs_pwd (void)
Display current working directory.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Returns
void.
Definition at line 444 of file fatfs_utils.c.
Referenced by fatfs_tests(), and mmc_test().
MEMSPACE void fatfs_rename (const char * oldpath, const char * newpath)
Rename a file.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in oldpath old name.
in newpath new name.
Returns
void
Definition at line 167 of file fatfs_utils.c.
Referenced by fatfs_tests().
MEMSPACE void fatfs_rm (char * name)
Delete a file by name.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in name File name to delete.
Returns
void.
Definition at line 355 of file fatfs_utils.c.
Referenced by fatfs_tests().
MEMSPACE void fatfs_rmdir (char * name)
Delete a directory.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in name Directory name.
Returns
void.
Definition at line 388 of file fatfs_utils.c.
Referenced by fatfs_tests().
MEMSPACE void fatfs_stat (char * name)
Display FILINFO status of a file by name.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in name File name.
Returns
void
Definition at line 403 of file fatfs_utils.c.
Referenced by fatfs_tests().
MEMSPACE int fatfs_tests (char * str)
FatFs test parser.
Keywords and arguments are matched against fatfs test functions If ther are matched the function along with its argements are called.
Parameters
in str User supplied command line with FatFs test and arguments.
Returns
1 The ruturn code indicates a command matched.
0 if no rules matched
Definition at line 468 of file fatfs_utils.c.
Referenced by loop_task().
MEMSPACE void mmc_test (void)
Perform key FatFs diagnostics tests.
Perform all basic file tests
Assumes the device is formatted
Returns
void
Definition at line 47 of file fatfs_utils.c.
Referenced by fatfs_tests().