fatfs.sup/fatfs_tests.h File Reference
Functions
MEMSPACE void fatfs_help (void)
Display FatFs test diagnostics help menu.
MEMSPACE int fatfs_tests (int argc, char *argv[])
FatFs test parser.
MEMSPACE void mmc_test (void)
Perform key FatFs diagnostics tests.
MEMSPACE void fatfs_cat (char *name)
MEMSPACE void fatfs_copy (char *from, char *to)
MEMSPACE void fatfs_create (char *name, char *str)
MEMSPACE void fatfs_cd (char *name)
MEMSPACE void fatfs_ls (char *name)
MEMSPACE void fatfs_mkdir (char *name)
MEMSPACE void fatfs_pwd (void)
MEMSPACE void fatfs_rename (const char *oldpath, const char *newpath)
MEMSPACE void fatfs_rm (char *name)
MEMSPACE void fatfs_rmdir (char *name)
MEMSPACE void fatfs_stat (char *name)
Function Documentation
MEMSPACE void fatfs_cat (char * name)
Referenced by fatfs_ls(), fatfs_tests(), and mmc_test().
MEMSPACE void fatfs_cd (char * name)
Referenced by fatfs_ls(), fatfs_tests(), and mmc_test().
MEMSPACE void fatfs_copy (char * from, char * to)
Referenced by fatfs_ls(), fatfs_tests(), and mmc_test().
MEMSPACE void fatfs_create (char * name, char * str)
Referenced by fatfs_ls(), fatfs_tests(), and mmc_test().
MEMSPACE void fatfs_help (void)
Display FatFs test diagnostics help menu.
Returns
void
Definition at line 42 of file fatfs_tests.c.
Referenced by fatfs_tests(), and user_help().
MEMSPACE void fatfs_ls (char * name)
Credit: part of FatFs avr example project (C)ChaN, 2013.
Parameters
in ptr pathname of directory to list
See also
fatfs_filinfo_list().
Returns
void.
Definition at line 307 of file fatfs_tests.c.
Referenced by fatfs_tests(), and mmc_test().
MEMSPACE void fatfs_mkdir (char * name)
Referenced by fatfs_ls(), fatfs_tests(), and mmc_test().
MEMSPACE void fatfs_pwd (void)
Referenced by fatfs_ls(), fatfs_tests(), and mmc_test().
MEMSPACE void fatfs_rename (const char * oldpath, const char * newpath)
Referenced by fatfs_ls(), and fatfs_tests().
MEMSPACE void fatfs_rm (char * name)
Referenced by fatfs_ls(), and fatfs_tests().
MEMSPACE void fatfs_rmdir (char * name)
Referenced by fatfs_ls(), and fatfs_tests().
MEMSPACE void fatfs_stat (char * name)
Referenced by fatfs_ls(), and fatfs_tests().
MEMSPACE int fatfs_tests (int argc, char * argv[])
FatFs test parser.
Keywords and arguments are matched against fatfs test functions If ther are matched the function along with its argements are called.
Parameters
in str User supplied command line with FatFs test and arguments.
Returns
1 The ruturn code indicates a command matched.
0 if no rules matched
Definition at line 92 of file fatfs_tests.c.
Referenced by user_tests().
MEMSPACE void mmc_test (void)
Perform key FatFs diagnostics tests.
Perform all basic file tests
Assumes the device is formatted
Returns
void
Definition at line 265 of file fatfs_tests.c.
Referenced by fatfs_tests().