fatfs.sup/fatfs_sup.c File Reference
#include `user_config.h`
*
#include `printf/mathio.h`
*
#include `lib/time.h`
*
#include `esp8266/hspi.h`
*
#include `fatfs.sup/fatfs.h`
*
Functions
MEMSPACE uint32_t tm_to_fat (tm_t *t)
FAT time structer reference.
MEMSPACE DWORD get_fattime (void)
Read DS1307 RTC and convert to FAT32 time.
MEMSPACE void put_rc (int rc)
display FatFs return code as ascii string
MEMSPACE int fatfs_scan_files (char *path)
Use were FILINFO structure can be share in many functions See: fatfs_alloc_filinfo(), fatfs_scan_files() and fatfs_ls()
MEMSPACE char * fatfs_fstype (int type)
return a string with the file system type
MEMSPACE void fatfs_status (char *ptr)
Compute space used, number of directories and files contained used by a drive.
MEMSPACE void fatfs_filinfo_list (FILINFO *info)
Display FILINFO structure in a readable format.
Variables
FATFS Fatfs [_VOLUMES]
FatFs Drive Volumes.
DWORD AccSize
Total file space used.
WORD AccFiles
Total number or Files and Directories.
WORD AccDirs
Function Documentation
MEMSPACE void fatfs_filinfo_list (FILINFO * info)
Display FILINFO structure in a readable format.
Credit: part of FatFs avr example project (C)ChaN, 2013.
Example:
/// ----A 2014/10/16 00:39        14    test2.txt  
/// D---- 2014/10/12 21:29         0          tmp 
/// 
@param[in] : FILINFO pointer
@return  void  
Definition at line 335 of file fatfs_sup.c.
Referenced by fatfs_cat(), and fatfs_ls().
MEMSPACE char* fatfs_fstype (int type)
return a string with the file system type
Parameters
in type file system type
Returns
string with file system type
Definition at line 230 of file fatfs_sup.c.
Referenced by fatfs_status().
MEMSPACE int fatfs_scan_files (char * path)
Use were FILINFO structure can be share in many functions See: fatfs_alloc_filinfo(), fatfs_scan_files() and fatfs_ls()
Allocate FILINFO structure and optional long file name buffer
Parameters
in allocate If allocate is true use calloc otherwise return static __filinfo
See also
fatfs_free_filinfo()
fatfs_scan_files()
fatfs_ls()
Returns
FILINFO * on success
NULL on error Compute space used, number of directories and files contained under a specified directory
Credit: part of FatFs avr example project (C)ChaN, 2013
Parameters
in path
See also
f_opendir()
f_readdir()
AccDirs: Total number of directories
AccFiles: Total number of Files
AccSize: Total size of all files
Returns
0 if no error
FafFs error code
Definition at line 192 of file fatfs_sup.c.
Referenced by fatfs_scan_files(), and fatfs_status().
MEMSPACE void fatfs_status (char * ptr)
Compute space used, number of directories and files contained used by a drive.
Credit: part of FatFs avr example project (C)ChaN, 2013
Parameters
in ptr Drive path like `/`
See also
f_getfree() drive free space
fatfs_scan_files()
AccDirs: Total number of directories
AccFiles: Total number of Files
AccSize: Total size of all files
Returns
void
Definition at line 266 of file fatfs_sup.c.
Referenced by fatfs_tests(), mmc_init(), and mmc_test().
MEMSPACE DWORD get_fattime (void)
Read DS1307 RTC and convert to FAT32 time.
Returns
FAT32 time.
See also
tm_to_fat().
Definition at line 128 of file fatfs_sup.c.
Referenced by rtc_read().
MEMSPACE void put_rc (int rc)
display FatFs return code as ascii string
Credit: Part of FatFs avr example project (C)ChaN, 2013
Parameters
in rc FatFs status return code
Returns
void
Definition at line 143 of file fatfs_sup.c.
Referenced by fatfs_cat(), fatfs_ls(), fatfs_status(), fatfs_tests(), and mmc_init().
MEMSPACE uint32_t tm_to_fat (tm_t * t)
FAT time structer reference.
See also
rtc.h
http://lxr.free-electrons.com/source/fs/fat/misc.c
/// typedef struct
/// {
///     WORD   year;                                  /* 2000..2099 */
///     BYTE   month;                                 /* 1..12 */
///     BYTE   mday;                                  /* 1.. 31 */
///     BYTE   wday;                                  /* 1..7 */
///     BYTE   hour;                                  /* 0..23 */
///     BYTE   min;                                   /* 0..59 */
///     BYTE   sec;                                   /* 0..59 */
/// } RTC;
/// 
 Convert Linux POSIX tm_t * to FAT32 time.
Parameters
in t POSIX struct tm * to convert.
Returns
FAT32 time.
Definition at line 111 of file fatfs_sup.c.
Referenced by get_fattime(), and rtc_read().
Variable Documentation
WORD AccDirs
Definition at line 162 of file fatfs_sup.c.
Referenced by fatfs_scan_files(), and fatfs_status().
WORD AccFiles
Total number or Files and Directories.
Definition at line 162 of file fatfs_sup.c.
Referenced by fatfs_scan_files(), and fatfs_status().
DWORD AccSize
Total file space used.
Definition at line 159 of file fatfs_sup.c.
Referenced by fatfs_scan_files(), and fatfs_status().
FATFS Fatfs[_VOLUMES]
FatFs Drive Volumes.
Definition at line 41 of file fatfs_sup.c.
Referenced by mmc_init().