fatfs/ff.h File Reference
FatFS file system module include file R0.10b (C) ChaN, 2014.
#include `user_config.h`
*
#include `integer.h`
*
#include `ffconf.h`
*
Data Structures
struct FATFS
File system object structure (FATFS)
struct FIL
File object structure (FIL)
struct DIR
Directory object structure (DIR)
struct FILINFO
File status structure (FILINFO)
Macros
#define _FATFS 8051 /* Revision ID */
#define LD2PD(vol) (BYTE)(vol) /*< Each logical drive is bound to the same physical drive number */
#define LD2PT(vol) 0 /*< Find first valid partition or in SFD */
#define _T(x) x
#define _TEXT(x) x
#define f_eof(fp) (((fp)->fptr == (fp)->fsize) ? 1 : 0)
#define f_error(fp) ((fp)->err)
#define f_tell(fp) ((fp)->fptr)
#define f_size(fp) ((fp)->fsize)
#define EOF (-1)
#define FA_READ 0x01
#define FA_OPEN_EXISTING 0x00
#define FA_WRITE 0x02
#define FA_CREATE_NEW 0x04
#define FA_CREATE_ALWAYS 0x08
#define FA_OPEN_ALWAYS 0x10
#define FA__WRITTEN 0x20
#define FA__DIRTY 0x40
#define FS_FAT12 1
#define FS_FAT16 2
#define FS_FAT32 3
#define AM_RDO 0x01 /* Read only */
#define AM_HID 0x02 /* Hidden */
#define AM_SYS 0x04 /* System */
#define AM_VOL 0x08 /* Volume label */
#define AM_LFN 0x0F /* LFN entry */
#define AM_DIR 0x10 /* Directory */
#define AM_ARC 0x20 /* Archive */
#define AM_MASK 0x3F /* Mask of defined bits */
#define CREATE_LINKMAP 0xFFFFFFFF
#define LD_WORD(ptr) (WORD)(((WORD)*((BYTE*)(ptr)+1)<<8)|(WORD)*(BYTE*)(ptr))
#define LD_DWORD(ptr) (DWORD)(((DWORD)*((BYTE*)(ptr)+3)<<24)|((DWORD)*((BYTE*)(ptr)+2)<<16)|((WORD)*((BYTE*)(ptr)+1)<<8)|*(BYTE*)(ptr))
#define ST_WORD(ptr, val) *(BYTE*)(ptr)=(BYTE)(val); *((BYTE*)(ptr)+1)=(BYTE)((WORD)(val)>>8)
#define ST_DWORD(ptr, val) *(BYTE*)(ptr)=(BYTE)(val); *((BYTE*)(ptr)+1)=(BYTE)((WORD)(val)>>8); *((BYTE*)(ptr)+2)=(BYTE)((DWORD)(val)>>16); *((BYTE*)(ptr)+3)=(BYTE)((DWORD)(val)>>24)
Typedefs
typedef char TCHAR
Enumerations
enum FRESULT {
*
FR_OK = 0,
FR_DISK_ERR,
FR_INT_ERR,
FR_NOT_READY,
*
FR_NO_FILE,
FR_NO_PATH,
FR_INVALID_NAME,
FR_DENIED,
*
FR_EXIST,
FR_INVALID_OBJECT,
FR_WRITE_PROTECTED,
FR_INVALID_DRIVE,
*
FR_NOT_ENABLED,
FR_NO_FILESYSTEM,
FR_MKFS_ABORTED,
FR_TIMEOUT,
*
FR_LOCKED,
FR_NOT_ENOUGH_CORE,
FR_TOO_MANY_OPEN_FILES,
FR_INVALID_PARAMETER
 }
File function return code (FRESULT)
Functions
FRESULT f_open (FIL *fp, const TCHAR *path, BYTE mode)
FRESULT f_close (FIL *fp)
FRESULT f_read (FIL *fp, void *buff, UINT btr, UINT *br)
FRESULT f_write (FIL *fp, const void *buff, UINT btw, UINT *bw)
FRESULT f_forward (FIL *fp, UINT(*func)(const BYTE *, UINT), UINT btf, UINT *bf)
FRESULT f_lseek (FIL *fp, DWORD ofs)
FRESULT f_truncate (FIL *fp)
FRESULT f_sync (FIL *fp)
FRESULT f_opendir (DIR *dp, const TCHAR *path)
FRESULT f_closedir (DIR *dp)
FRESULT f_readdir (DIR *dp, FILINFO *fno)
FRESULT f_mkdir (const TCHAR *path)
FRESULT f_unlink (const TCHAR *path)
FRESULT f_rename (const TCHAR *path_old, const TCHAR *path_new)
FRESULT f_stat (const TCHAR *path, FILINFO *fno)
FRESULT f_chmod (const TCHAR *path, BYTE value, BYTE mask)
FRESULT f_utime (const TCHAR *path, const FILINFO *fno)
FRESULT f_chdir (const TCHAR *path)
FRESULT f_chdrive (const TCHAR *path)
FRESULT f_getcwd (TCHAR *buff, UINT len)
FRESULT f_getfree (const TCHAR *path, DWORD *nclst, FATFS **fatfs)
FRESULT f_getlabel (const TCHAR *path, TCHAR *label, DWORD *vsn)
FRESULT f_setlabel (const TCHAR *label)
FRESULT f_mount (FATFS *fs, const TCHAR *path, BYTE opt)
FRESULT f_mkfs (const TCHAR *path, BYTE sfd, UINT au)
FRESULT f_fdisk (BYTE pdrv, const DWORD szt[], void *work)
int f_putc (TCHAR c, FIL *fp)
int f_puts (const TCHAR *str, FIL *cp)
int f_printf (FIL *fp, const TCHAR *str,...)
TCHAR * f_gets (TCHAR *buff, int len, FIL *fp)
DWORD get_fattime (void)
Read DS1307 RTC and convert to FAT32 time.
WCHAR ff_convert (WCHAR chr, UINT dir)
WCHAR ff_wtoupper (WCHAR chr)
void * ff_memalloc (UINT msize)
void ff_memfree (void *mblock)
Detailed Description
FatFS file system module include file R0.10b (C) ChaN, 2014.
Copyright 2014 ChaN.
Definition in file ff.h.
Macro Definition Documentation
#define _FATFS 8051 /* Revision ID */
Definition at line 26 of file ff.h.
#define _T(x) x
Definition at line 73 of file ff.h.
#define _TEXT(x) x
Definition at line 74 of file ff.h.
#define AM_ARC 0x20 /* Archive */
Definition at line 317 of file ff.h.
Referenced by f_chmod(), f_rename(), f_sync(), and fatfs_filinfo_list().
#define AM_DIR 0x10 /* Directory */
Definition at line 316 of file ff.h.
Referenced by f_chdir(), f_mkdir(), f_open(), f_opendir(), f_rename(), f_unlink(), fatfs_filinfo_list(), fatfs_ls(), fatfs_scan_files(), follow_path(), and stat().
#define AM_HID 0x02 /* Hidden */
Definition at line 312 of file ff.h.
Referenced by f_chmod(), and fatfs_filinfo_list().
#define AM_LFN 0x0F /* LFN entry */
Definition at line 315 of file ff.h.
Referenced by dir_find(), dir_read(), and fit_lfn().
#define AM_MASK 0x3F /* Mask of defined bits */
Definition at line 318 of file ff.h.
Referenced by dir_find(), and dir_read().
#define AM_RDO 0x01 /* Read only */
Definition at line 311 of file ff.h.
Referenced by f_chmod(), f_open(), f_unlink(), fatfs_filinfo_list(), and stat().
#define AM_SYS 0x04 /* System */
Definition at line 313 of file ff.h.
Referenced by f_chmod(), fatfs_filinfo_list(), and stat().
#define AM_VOL 0x08 /* Volume label */
Definition at line 314 of file ff.h.
Referenced by dir_find(), dir_read(), and f_setlabel().
#define CREATE_LINKMAP 0xFFFFFFFF
Definition at line 321 of file ff.h.
Referenced by f_lseek().
#define EOF (-1)
Definition at line 257 of file ff.h.
Referenced by f_printf(), f_putc(), f_puts(), fatfs_getc(), fatfs_putc(), fclose(), fgetc(), and fputc().
#define f_eof(fp) (((fp)->fptr == (fp)->fsize) ? 1 : 0)
Definition at line 251 of file ff.h.
#define f_error(fp) ((fp)->err)
Definition at line 252 of file ff.h.
#define f_size(fp) ((fp)->fsize)
Definition at line 254 of file ff.h.
#define f_tell(fp) ((fp)->fptr)
Definition at line 253 of file ff.h.
#define FA__DIRTY 0x40
Definition at line 300 of file ff.h.
Referenced by f_lseek(), f_read(), f_sync(), f_truncate(), and f_write().
#define FA__WRITTEN 0x20
Definition at line 299 of file ff.h.
Referenced by f_lseek(), f_open(), f_sync(), f_truncate(), and f_write().
#define FA_CREATE_ALWAYS 0x08
Definition at line 297 of file ff.h.
Referenced by f_open(), fatfs_copy(), fatfs_create(), and open().
#define FA_CREATE_NEW 0x04
Definition at line 296 of file ff.h.
Referenced by f_open().
#define FA_OPEN_ALWAYS 0x10
Definition at line 298 of file ff.h.
Referenced by f_open(), and open().
#define FA_OPEN_EXISTING 0x00
Definition at line 292 of file ff.h.
Referenced by fatfs_cat(), fatfs_copy(), and truncate().
#define FA_READ 0x01
Definition at line 291 of file ff.h.
Referenced by f_open(), f_read(), fatfs_cat(), fatfs_copy(), open(), and truncate().
#define FA_WRITE 0x02
Definition at line 295 of file ff.h.
Referenced by f_lseek(), f_open(), f_truncate(), f_write(), fatfs_copy(), fatfs_create(), open(), and truncate().
#define FS_FAT12 1
Definition at line 305 of file ff.h.
Referenced by f_getfree(), f_mkfs(), find_volume(), get_fat(), and put_fat().
#define FS_FAT16 2
Definition at line 306 of file ff.h.
Referenced by f_getfree(), f_mkfs(), find_volume(), get_fat(), and put_fat().
#define FS_FAT32 3
Definition at line 307 of file ff.h.
Referenced by dir_sdi(), f_getlabel(), f_mkdir(), f_mkfs(), f_rename(), find_volume(), get_fat(), ld_clust(), put_fat(), and sync_fs().
#define LD2PD(vol) (BYTE)(vol) /*< Each logical drive is bound to the same physical drive number */
Definition at line 54 of file ff.h.
Referenced by f_mkfs(), and find_volume().
#define LD2PT(vol) 0 /*< Find first valid partition or in SFD */
Definition at line 55 of file ff.h.
Referenced by f_mkfs(), and find_volume().
#define LD_DWORD(ptr) (DWORD)(((DWORD)*((BYTE*)(ptr)+3)<<24)|((DWORD)*((BYTE*)(ptr)+2)<<16)|((WORD)*((BYTE*)(ptr)+1)<<8)|*(BYTE*)(ptr))
Definition at line 333 of file ff.h.
Referenced by check_fs(), f_getfree(), f_getlabel(), f_mkfs(), f_open(), find_volume(), get_fat(), get_fileinfo(), and put_fat().
#define LD_WORD(ptr) (WORD)(((WORD)*((BYTE*)(ptr)+1)<<8)|(WORD)*(BYTE*)(ptr))
Definition at line 332 of file ff.h.
Referenced by check_fs(), cmp_lfn(), f_getfree(), f_mkfs(), find_volume(), get_fat(), get_fileinfo(), ld_clust(), and pick_lfn().
#define ST_DWORD(ptr, val) *(BYTE*)(ptr)=(BYTE)(val); *((BYTE*)(ptr)+1)=(BYTE)((WORD)(val)>>8); *((BYTE*)(ptr)+2)=(BYTE)((DWORD)(val)>>16); *((BYTE*)(ptr)+3)=(BYTE)((DWORD)(val)>>24)
Definition at line 335 of file ff.h.
Referenced by f_mkdir(), f_mkfs(), f_open(), f_setlabel(), f_sync(), put_fat(), and sync_fs().
#define ST_WORD(ptr, val) *(BYTE*)(ptr)=(BYTE)(val); *((BYTE*)(ptr)+1)=(BYTE)((WORD)(val)>>8)
Definition at line 334 of file ff.h.
Referenced by f_mkfs(), f_sync(), f_utime(), fit_lfn(), put_fat(), st_clust(), and sync_fs().
Typedef Documentation
typedef char TCHAR
Definition at line 72 of file ff.h.
Enumeration Type Documentation
enum FRESULT
File function return code (FRESULT)
Enumerator
FR_OK
FR_DISK_ERR
FR_INT_ERR
FR_NOT_READY
FR_NO_FILE
FR_NO_PATH
FR_INVALID_NAME
FR_DENIED
FR_EXIST
FR_INVALID_OBJECT
FR_WRITE_PROTECTED
FR_INVALID_DRIVE
FR_NOT_ENABLED
FR_NO_FILESYSTEM
FR_MKFS_ABORTED
FR_TIMEOUT
FR_LOCKED
FR_NOT_ENOUGH_CORE
FR_TOO_MANY_OPEN_FILES
FR_INVALID_PARAMETER
Definition at line 179 of file ff.h.
Function Documentation
FRESULT f_chdir (const TCHAR * path)
Definition at line 3132 of file ff.c.
Referenced by fatfs_cd().
FRESULT f_chdrive (const TCHAR * path)
FRESULT f_chmod (const TCHAR * path, BYTE value, BYTE mask)
Definition at line 3943 of file ff.c.
Referenced by fatfs_tests().
FRESULT f_close (FIL * fp)
Definition at line 3078 of file ff.c.
Referenced by close(), fatfs_cat(), fatfs_copy(), fatfs_create(), and open().
FRESULT f_closedir (DIR * dp)
Definition at line 3516 of file ff.c.
FRESULT f_fdisk (BYTE pdrv, const DWORD szt[], void * work)
FRESULT f_forward (FIL * fp, UINT(*)(const BYTE *, UINT) func, UINT btf, UINT * bf)
FRESULT f_getcwd (TCHAR * buff, UINT len)
Definition at line 3170 of file ff.c.
Referenced by fatfs_pwd().
FRESULT f_getfree (const TCHAR * path, DWORD * nclst, FATFS ** fatfs)
Definition at line 3634 of file ff.c.
Referenced by fatfs_ls(), and fatfs_status().
FRESULT f_getlabel (const TCHAR * path, TCHAR * label, DWORD * vsn)
Definition at line 4135 of file ff.c.
TCHAR* f_gets (TCHAR * buff, int len, FIL * fp)
Definition at line 4733 of file ff.c.
FRESULT f_lseek (FIL * fp, DWORD ofs)
Definition at line 3262 of file ff.c.
Referenced by ftruncate(), lseek(), open(), and truncate().
FRESULT f_mkdir (const TCHAR * path)
Definition at line 3863 of file ff.c.
Referenced by fatfs_mkdir().
FRESULT f_mkfs (const TCHAR * path, BYTE sfd, UINT au)
Definition at line 4378 of file ff.c.
Referenced by fatfs_tests().
FRESULT f_mount (FATFS * fs, const TCHAR * path, BYTE opt)
Definition at line 2563 of file ff.c.
Referenced by fatfs_tests(), and mmc_init().
FRESULT f_open (FIL * fp, const TCHAR * path, BYTE mode)
Definition at line 2610 of file ff.c.
Referenced by fatfs_cat(), fatfs_copy(), fatfs_create(), open(), and truncate().
FRESULT f_opendir (DIR * dp, const TCHAR * path)
Definition at line 3453 of file ff.c.
Referenced by fatfs_ls(), and fatfs_scan_files().
int f_printf (FIL * fp, const TCHAR * str, ...)
Definition at line 4940 of file ff.c.
int f_putc (TCHAR c, FIL * fp)
Definition at line 4889 of file ff.c.
int f_puts (const TCHAR * str, FIL * cp)
Definition at line 4914 of file ff.c.
FRESULT f_read (FIL * fp, void * buff, UINT btr, UINT * br)
Definition at line 2770 of file ff.c.
Referenced by f_gets(), fatfs_cat(), fatfs_copy(), fatfs_getc(), and read().
FRESULT f_readdir (DIR * dp, FILINFO * fno)
Definition at line 3547 of file ff.c.
Referenced by fatfs_ls(), and fatfs_scan_files().
FRESULT f_rename (const TCHAR * path_old, const TCHAR * path_new)
Definition at line 4036 of file ff.c.
Referenced by fatfs_rename(), and rename().
FRESULT f_setlabel (const TCHAR * label)
Definition at line 4207 of file ff.c.
FRESULT f_stat (const TCHAR * path, FILINFO * fno)
Definition at line 3595 of file ff.c.
Referenced by fatfs_stat(), and stat().
FRESULT f_sync (FIL * fp)
Definition at line 3028 of file ff.c.
Referenced by f_close(), and syncfs().
FRESULT f_truncate (FIL * fp)
Definition at line 3714 of file ff.c.
Referenced by ftruncate(), and truncate().
FRESULT f_unlink (const TCHAR * path)
Definition at line 3779 of file ff.c.
Referenced by fatfs_rm(), fatfs_rmdir(), rmdir(), and unlink().
FRESULT f_utime (const TCHAR * path, const FILINFO * fno)
Definition at line 3991 of file ff.c.
FRESULT f_write (FIL * fp, const void * buff, UINT btw, UINT * bw)
Definition at line 2886 of file ff.c.
Referenced by f_printf(), f_putc(), f_puts(), fatfs_copy(), fatfs_create(), fatfs_putc(), putc_bfd(), and write().
WCHAR ff_convert (WCHAR chr, UINT dir)
Definition at line 15 of file unicode.c.
Referenced by create_name(), f_getlabel(), f_gets(), f_setlabel(), get_fileinfo(), and putc_bfd().
void* ff_memalloc (UINT msize)
Definition at line 148 of file syscall.c.
void ff_memfree (void * mblock)
Definition at line 161 of file syscall.c.
WCHAR ff_wtoupper (WCHAR chr)
Definition at line 27 of file unicode.c.
Referenced by cmp_lfn(), create_name(), and f_setlabel().
DWORD get_fattime (void)
Read DS1307 RTC and convert to FAT32 time.
Returns
FAT32 time.
See Also
tm_to_fat().
Definition at line 119 of file disk.c.
Referenced by f_mkdir(), f_mkfs(), f_open(), f_setlabel(), and f_sync().