utils/flash.c File Reference
#include <user_config.h>
*
#include `flash.h`
*
Macros
#define USE_CACHE
Functions
uint8_t read_flash8 (uint8_t *p)
void cpy_flash (uint8_t *src, uint8_t *dest, int size)
Copy data from Flash to Ram Uses flash_read8() to avoid alighnment problems.
uint16_t read_flash16 (uint8_t *p)
16 bits reads from Flash memory space Uses cpy_flash() to avoid alighnment problems
uint32_t read_flash32 (uint8_t *p)
32 bits reads from Flash memory space Uses cpy_flash() to avoid alighnment problems
uint64_t read_flash64 (uint8_t *p)
64 bits reads from Flash memory space Uses cpy_flash() to avoid alighnment problems
uint32_t read_flash_ptr (uint8_t *p)
Pointer read from Flash memory space Uses cpy_flash() to avoid alighnment problems.
int bittestv (unsigned char *ptr, int off)
Test bit in byte array.
int bittestxy (unsigned char *ptr, int x, int y, int w, int h)
Test bit in w * h size bit array usng x and y offsets.
Variables
uint32_t _addr = 0
Read bit bit value from flash Supports 8 bits reads from memory spaced that must have 32bit aligned data Caches the 32bit read.
uint32_t _data
uint8_t * p8 = (uint8_t *) &_data
Macro Definition Documentation
#define USE_CACHE
Definition at line 28 of file flash.c.
Function Documentation
int bittestv (unsigned char * ptr, int off)
Test bit in byte array.
Parameters
in *ptr byte array
in off bit offset to test
Returns
1 if bit is set, 0 if not
Definition at line 146 of file flash.c.
Referenced by bittestxy(), and tft_bit_blit().
int bittestxy (unsigned char * ptr, int x, int y, int w, int h)
Test bit in w * h size bit array usng x and y offsets.
Parameters
in *ptr byte array
in x bit x offset
in y bit y offset
in w bit array wide
in h bit array high
Returns
1 if bit is set, 0 if not
Definition at line 161 of file flash.c.
void cpy_flash (uint8_t * src, uint8_t * dest, int size)
Copy data from Flash to Ram Uses flash_read8() to avoid alighnment problems.
Parameters
in *src address to read from
out *dest address to write to
in size number of bytes to copy
Returns
void
Definition at line 84 of file flash.c.
Referenced by font_attr(), read_flash16(), read_flash32(), read_flash64(), read_flash_ptr(), and wire_draw().
uint16_t read_flash16 (uint8_t * p)
16 bits reads from Flash memory space Uses cpy_flash() to avoid alighnment problems
Parameters
in *p address to read
Returns
uint16_t
Definition at line 98 of file flash.c.
uint32_t read_flash32 (uint8_t * p)
32 bits reads from Flash memory space Uses cpy_flash() to avoid alighnment problems
Parameters
in *p address to read
Returns
uint32_t
Definition at line 110 of file flash.c.
uint64_t read_flash64 (uint8_t * p)
64 bits reads from Flash memory space Uses cpy_flash() to avoid alighnment problems
Parameters
in *p address to read
Returns
uint64_t
Definition at line 122 of file flash.c.
uint8_t read_flash8 (uint8_t * p)
Definition at line 41 of file flash.c.
Referenced by bittestv(), and cpy_flash().
uint32_t read_flash_ptr (uint8_t * p)
Pointer read from Flash memory space Uses cpy_flash() to avoid alighnment problems.
Parameters
in *p address to read
Returns
uint32_t
Definition at line 134 of file flash.c.
Variable Documentation
uint32_t _addr = 0
Read bit bit value from flash Supports 8 bits reads from memory spaced that must have 32bit aligned data Caches the 32bit read.
Parameters
in *p address to read
Returns
uint8_t
Definition at line 38 of file flash.c.
Referenced by read_flash8().
uint32_t _data
Definition at line 39 of file flash.c.
Referenced by read_flash8().
uint8_t* p8 = (uint8_t *) &_data
Definition at line 40 of file flash.c.
Referenced by read_flash8().