esp8266/flash.h File Reference
Flash read and bit test utilities.
Functions
uint8_t read_flash8 (uint8_t *p)
void cpy_flash (uint8_t *src, uint8_t *dest, int size)
Copy data from Flash to Ram Uses flash_read8() to avoid alighnment problems.
uint16_t read_flash16 (uint8_t *p)
16 bits reads from Flash memory space Uses cpy_flash() to avoid alighnment problems
uint32_t read_flash32 (uint8_t *p)
32 bits reads from Flash memory space Uses cpy_flash() to avoid alighnment problems
uint64_t read_flash64 (uint8_t *p)
64 bits reads from Flash memory space Uses cpy_flash() to avoid alighnment problems
uint32_t read_flash_ptr (uint8_t *p)
Pointer read from Flash memory space Uses cpy_flash() to avoid alighnment problems.
int bittestv (unsigned char *ptr, int off)
Test bit in byte array.
int bittestxy (unsigned char *ptr, int x, int y, int w, int h)
Test bit in w * h size bit array usng x and y offsets.
Detailed Description
Flash read and bit test utilities.
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
Please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
int bittestv (unsigned char * ptr, int off)
Test bit in byte array.
Parameters
in *ptr byte array
in off bit offset to test
Returns
1 if bit is set, 0 if not
Definition at line 151 of file flash.c.
Referenced by bittestxy(), and tft_bit_blit().
int bittestxy (unsigned char * ptr, int x, int y, int w, int h)
Test bit in w * h size bit array usng x and y offsets.
Parameters
in *ptr byte array
in x bit x offset
in y bit y offset
in w bit array wide
in h bit array high
Returns
1 if bit is set, 0 if not
Test bit in w * h size bit array usng x and y offsets.
Parameters
in *ptr byte array
in x bit x offset
in y bit y offset
in w the width of bit array
in h the height of bit array
Returns
1 if bit is set, 0 if not
Definition at line 166 of file flash.c.
void cpy_flash (uint8_t * src, uint8_t * dest, int size)
Copy data from Flash to Ram Uses flash_read8() to avoid alighnment problems.
Parameters
in *src address to read from
out *dest address to write to
in size number of bytes to copy
Returns
void
Definition at line 89 of file flash.c.
Referenced by font_attr(), read_flash16(), read_flash32(), read_flash64(), read_flash_ptr(), and wire_draw().
uint16_t read_flash16 (uint8_t * p)
16 bits reads from Flash memory space Uses cpy_flash() to avoid alighnment problems
Parameters
in *p address to read
Returns
uint16_t
Definition at line 103 of file flash.c.
Referenced by user_tests().
uint32_t read_flash32 (uint8_t * p)
32 bits reads from Flash memory space Uses cpy_flash() to avoid alighnment problems
Parameters
in *p address to read
Returns
uint32_t
Definition at line 115 of file flash.c.
Referenced by user_tests().
uint64_t read_flash64 (uint8_t * p)
64 bits reads from Flash memory space Uses cpy_flash() to avoid alighnment problems
Parameters
in *p address to read
Returns
uint64_t
Definition at line 127 of file flash.c.
uint8_t read_flash8 (uint8_t * p)
Definition at line 46 of file flash.c.
Referenced by bittestv(), cpy_flash(), read_flash8(), and user_tests().
uint32_t read_flash_ptr (uint8_t * p)
Pointer read from Flash memory space Uses cpy_flash() to avoid alighnment problems.
Parameters
in *p address to read
Returns
uint32_t
Definition at line 139 of file flash.c.