fonts/font.h File Reference
#include `stdint.h`
*
Data Structures
struct _bdffile
struct _fontspecs
struct _fontinfo
struct _font
struct _fontc
Macros
#define MAXFONTS 256 /* Maximum number of fonts to convert at one time */
#define MAXGLYPHS 256 /* Max Glyphs Per Font */
#define MAXWIDTH 127 /* Max Character Width */
#define MAXHEIGHT 127 /* Max Character Height */
Functions
int font_attr (int c, _fontc *f, int index)
Get font attributes for a font.
int tft_drawChar (uint8_t c, uint16_t x, uint16_t y, uint8_t index)
Display a character using font tables.
Macro Definition Documentation
#define MAXFONTS 256 /* Maximum number of fonts to convert at one time */
BDF = Glyph Bitmap Distribution Format See: http://en.wikipedia.org/wiki/Glyph_Bitmap_Distribution_Format
Definition at line 38 of file font.h.
#define MAXGLYPHS 256 /* Max Glyphs Per Font */
Definition at line 39 of file font.h.
#define MAXHEIGHT 127 /* Max Character Height */
Definition at line 41 of file font.h.
#define MAXWIDTH 127 /* Max Character Width */
Definition at line 40 of file font.h.
Function Documentation
int font_attr (int c, _fontc * f, int index)
Get font attributes for a font.
Parameters
in c character
in *f font structure
in index font index (which font table we want)
Returns
void
Definition at line 64 of file font.c.
Referenced by tft_drawCentreString(), tft_drawChar(), tft_drawRightString(), and tft_putch().
int tft_drawChar (uint8_t c, uint16_t x, uint16_t y, uint8_t index)
Display a character using font tables.
Parameters
in c character
in x X offset in pixels
in y Y offset in pixels
in index Font index (with font set to use)
Returns
void
Definition at line 138 of file font.c.
Referenced by tft_drawCentreString(), tft_drawRightString(), tft_drawString(), and tft_putch().