driver/hspi.h File Reference
#include `spi_register.h`
*
#include <ets_sys.h>
*
#include <osapi.h>
*
#include <os_type.h>
*
#include <gpio.h>
*
Macros
#define SPI 0
#define HSPI 1
#define HSPI_FIFO_SIZE 64
#define CONFIG_FOR_TX 1
#define CONFIG_FOR_RX_TX 2
Functions
void hspi_init (void)
HSPI Initiaization - with automatic chip sellect Pins: MISO GPIO12 MOSI GPIO13 CLK GPIO14 CS GPIO15 DC GPIO2.
void hspi_config (int configState)
HSPI Configuration for tranasmit and receive.
void hspi_setBits (uint16_t bytes)
HSPI FIFO send or receive byte count.
void hspi_startSend (void)
HSPI Start Send.
void hspi_waitReady (void)
HSPI Ready wait.
void hspi_writeFIFO (uint8_t *write_data, uint16_t bytes)
HSPI FIFO write in units of 32 bits (4 byte words)
void hspi_readFIFO (uint8_t *read_data, uint16_t bytes)
HSPI FIFO Read in units of 32 bits (4 byte words)
void hspi_stream_init (void)
HSPI stream init We use the fifo - or a buffer to queue spi writes The overhead of N writes done at once is less N writes done one at a time.
void hspi_stream (uint8_t data)
HSPI stream byte to buffer We use the fifo - or a buffer to queue spi writes The overhead of N writes done at once is less N writes done one at a time.
void hspi_stream_flush (void)
HSPI stream flush We use the fifo - or a buffer to queue spi writes The overhead of N writes done at once is less N writes done one at a time.
void hspi_TxRx (uint8_t *data, uint16_t bytes)
Used only for small (less then HSPI_FIFO_SIZE) write / read Write and Read uses same buffer and same byte count.
void hspi_Tx (uint8_t *data, uint16_t bytes)
Used only for small (less then HSPI_FIFO_SIZE) write Used for small (less then HSPI_FIFO_SIZE) packet send only.
void hspi_TxBuffered (uint8_t *write_data, uint32_t bytes, uint32_t repeats)
Send large buffer (datasize bytes in size) repeat times Send repeats times Note: a repeat of zero will cause NO data to be sent Used for small (less then HSPI_FIFO_SIZE) packet send only.
Macro Definition Documentation
#define CONFIG_FOR_RX_TX 2
Definition at line 22 of file hspi.h.
Referenced by hspi_config(), and hspi_TxRx().
#define CONFIG_FOR_TX 1
Definition at line 21 of file hspi.h.
Referenced by hspi_config(), hspi_stream_flush(), and hspi_Tx().
#define HSPI 1
Definition at line 18 of file hspi.h.
Referenced by hspi_config(), hspi_init(), hspi_readFIFO(), hspi_setBits(), hspi_startSend(), hspi_waitReady(), and hspi_writeFIFO().
#define HSPI_FIFO_SIZE 64
Definition at line 19 of file hspi.h.
Referenced by hspi_readFIFO(), hspi_stream(), hspi_Tx(), hspi_TxBuffered(), hspi_TxRx(), and hspi_writeFIFO().
#define SPI 0
Definition at line 17 of file hspi.h.
Function Documentation
void hspi_config (int configState)
HSPI Configuration for tranasmit and receive.
Parameters
in configState CONFIG_FOR_RX_TX or CONFIG_FOR_RX
Returns
void
Definition at line 76 of file hspi.c.
Referenced by hspi_stream_flush(), hspi_Tx(), and hspi_TxRx().
void hspi_init (void)
HSPI Initiaization - with automatic chip sellect Pins: MISO GPIO12 MOSI GPIO13 CLK GPIO14 CS GPIO15 DC GPIO2.
Returns
void
Definition at line 43 of file hspi.c.
Referenced by tft_init().
void hspi_readFIFO (uint8_t * read_data, uint16_t bytes)
HSPI FIFO Read in units of 32 bits (4 byte words)
Parameters
in read_data read buffer
in bytes bytes to write
Returns
void
Definition at line 193 of file hspi.c.
Referenced by hspi_TxRx().
void hspi_setBits (uint16_t bytes)
HSPI FIFO send or receive byte count.
Parameters
in bytes bytes to send or receive
Returns
void
Definition at line 112 of file hspi.c.
Referenced by hspi_readFIFO(), and hspi_writeFIFO().
void hspi_startSend (void)
HSPI Start Send.
Returns
void
Definition at line 123 of file hspi.c.
Referenced by hspi_stream_flush(), hspi_Tx(), and hspi_TxRx().
void hspi_stream (uint8_t data)
HSPI stream byte to buffer We use the fifo - or a buffer to queue spi writes The overhead of N writes done at once is less N writes done one at a time.
Parameters
in data byte to add to buffer
Returns
void
Definition at line 267 of file hspi.c.
Referenced by tft_bit_blit(), tft_blit(), tft_writeColor16Repeat(), and tft_writeDataBuffered().
void hspi_stream_flush (void)
HSPI stream flush We use the fifo - or a buffer to queue spi writes The overhead of N writes done at once is less N writes done one at a time.
Returns
void
Definition at line 248 of file hspi.c.
Referenced by hspi_stream(), tft_bit_blit(), tft_blit(), tft_writeColor16Repeat(), and tft_writeDataBuffered().
void hspi_stream_init (void)
HSPI stream init We use the fifo - or a buffer to queue spi writes The overhead of N writes done at once is less N writes done one at a time.
Definition at line 237 of file hspi.c.
Referenced by tft_bit_blit(), tft_blit(), tft_writeColor16Repeat(), and tft_writeDataBuffered().
void hspi_Tx (uint8_t * data, uint16_t bytes)
Used only for small (less then HSPI_FIFO_SIZE) write Used for small (less then HSPI_FIFO_SIZE) packet send only.
Parameters
in data buffer
in bytes bytes to write
Returns
void
Definition at line 302 of file hspi.c.
Referenced by hspi_TxBuffered(), tft_writeCmd(), tft_writeCmdData(), tft_writeData(), and tft_writeData16().
void hspi_TxBuffered (uint8_t * write_data, uint32_t bytes, uint32_t repeats)
Send large buffer (datasize bytes in size) repeat times Send repeats times Note: a repeat of zero will cause NO data to be sent Used for small (less then HSPI_FIFO_SIZE) packet send only.
Parameters
in write_data buffer
in bytes bytes to write
in repeats repeates to send
Returns
void
Definition at line 321 of file hspi.c.
void hspi_TxRx (uint8_t * data, uint16_t bytes)
Used only for small (less then HSPI_FIFO_SIZE) write / read Write and Read uses same buffer and same byte count.
Parameters
in,out data buffer
in bytes bytes to write and or read
Returns
void
Definition at line 284 of file hspi.c.
Referenced by tft_readData16(), tft_readRegister(), and tft_writeCmdData().
void hspi_waitReady (void)
HSPI Ready wait.
Returns
void
Definition at line 134 of file hspi.c.
Referenced by hspi_config(), hspi_stream_flush(), hspi_stream_init(), hspi_Tx(), hspi_TxRx(), tft_readData16(), tft_readRegister(), tft_writeCmd(), tft_writeCmdData(), tft_writeData(), and tft_writeData16().
void hspi_writeFIFO (uint8_t * write_data, uint16_t bytes)
HSPI FIFO write in units of 32 bits (4 byte words)
Parameters
in write_data write buffer
in bytes bytes to write
Returns
void
Definition at line 147 of file hspi.c.
Referenced by hspi_stream_flush(), hspi_Tx(), and hspi_TxRx().