esp8266/hspi.c File Reference
HSPI driver for ESP8255 Based on initial work from Sem 2015 - rewrittem Added code to handle proper aligned reads and writes and buffering.
#include `user_config.h`
*
#include <stdint.h>
*
#include <stdarg.h>
*
#include <string.h>
*
#include <math.h>
*
#include `hspi.h`
*
#include `gpio.h`
*
Macros
#define HSPI_PRESCALER 16
Functions
void hspi_cs_enable (uint8_t cs)
HSPI CS enable function.
void hspi_cs_disable (uint8_t cs)
HSPI CS disable function.
uint8_t hspi_cs_status ()
HSPI CS pin status return CS pin status.
void hspi_init (uint16_t prescale, int hwcs)
HSPI Initiaization - with automatic chip select Pins: MISO GPIO12 MOSI GPIO13 CLK GPIO14 CS GPIO15 - optional DC GPIO2.
static void hspi_config (int configState)
HSPI Configuration for tranasmit and receive.
static void hspi_setBits (uint16_t bytes)
HSPI FIFO send or receive byte count.
static void hspi_startSend (void)
HSPI Start Send.
void hspi_waitReady (void)
HSPI Ready wait.
static void hspi_writeFIFO (uint8_t *write_data, int bytes)
HSPI FIFO write in units of 32 bits (4 byte words)
static void hspi_readFIFO (uint8_t *read_data, int bytes)
HSPI FIFO Read in units of 32 bits (4 byte words)
void hspi_TX (uint8_t *data, int count)
SPI buffered write functions.
void hspi_TXRX (uint8_t *data, int count)
HSPI write and read using FIFO.
void hspi_RX (uint8_t *data, int count)
HSPI read using FIFO.
Variables
uint8_t _cs_pin = 0xff
hspi CS cached value
static _hspi_init_done = 0
uint16_t hspi_clock = -1
hspi clock cached value
Detailed Description
HSPI driver for ESP8255 Based on initial work from Sem 2015 - rewrittem Added code to handle proper aligned reads and writes and buffering.
Copyright 2015 Sem
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
Please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Macro Definition Documentation
#define HSPI_PRESCALER 16
Definition at line 37 of file hspi.c.
Function Documentation
static void hspi_config (int configState) [static]
HSPI Configuration for tranasmit and receive.
Parameters
in configState CONFIG_FOR_RX_TX or CONFIG_FOR_RX
Returns
void
Definition at line 148 of file hspi.c.
Referenced by hspi_RX(), hspi_TX(), and hspi_TXRX().
void hspi_cs_disable (uint8_t cs)
HSPI CS disable function.
Parameters
in cs GPIO CS pin
Definition at line 62 of file hspi.c.
Referenced by loop(), mmc_cs_disable(), tft_init(), and tft_spi_end().
void hspi_cs_enable (uint8_t cs)
HSPI CS enable function.
Parameters
in cs GPIO CS pin
Definition at line 45 of file hspi.c.
Referenced by mmc_cs_enable(), and tft_spi_begin().
uint8_t hspi_cs_status ()
HSPI CS pin status return CS pin status.
Definition at line 79 of file hspi.c.
Referenced by loop().
void hspi_init (uint16_t prescale, int hwcs)
HSPI Initiaization - with automatic chip select Pins: MISO GPIO12 MOSI GPIO13 CLK GPIO14 CS GPIO15 - optional DC GPIO2.
Parameters
in prescale prescale from CPU clock 0 .. 0x1fff
in hwcs enable GPIO15 hardware chip select
Returns
void
Definition at line 99 of file hspi.c.
Referenced by ADF4351_spi_begin(), ADF4351_spi_init(), mmc_spi_init(), setup(), tft_spi_begin(), and tft_spi_init().
static void hspi_readFIFO (uint8_t * read_data, int bytes) [static]
HSPI FIFO Read in units of 32 bits (4 byte words)
Parameters
in read_data read buffer
in bytes bytes to write
Returns
void
Definition at line 259 of file hspi.c.
Referenced by hspi_RX(), and hspi_TXRX().
void hspi_RX (uint8_t * data, int count)
HSPI read using FIFO.
Parameters
in *data receive buffer
in count number of bytes to read
Returns
void
Definition at line 362 of file hspi.c.
Referenced by mmc_spi_RX(), mmc_spi_RX_buffer(), and tft_spi_RX().
static void hspi_setBits (uint16_t bytes) [static]
HSPI FIFO send or receive byte count.
Parameters
in bytes bytes to send or receive
Returns
void
Definition at line 184 of file hspi.c.
Referenced by hspi_readFIFO(), and hspi_writeFIFO().
static void hspi_startSend (void) [static]
HSPI Start Send.
Returns
void
Definition at line 195 of file hspi.c.
Referenced by hspi_RX(), hspi_TX(), and hspi_TXRX().
void hspi_TX (uint8_t * data, int count)
SPI buffered write functions.
=================================================================HSPI write using FIFO
Parameters
in *data transmit buffer
in count number of bytes to write
Returns
void
Definition at line 309 of file hspi.c.
Referenced by mmc_spi_TX(), mmc_spi_TX_buffer(), and tft_spi_TX().
void hspi_TXRX (uint8_t * data, int count)
HSPI write and read using FIFO.
Parameters
in *data transmit / receive buffer
in count number of bytes to write / read
Returns
void
Definition at line 336 of file hspi.c.
Referenced by ADF4351_spi_txrx(), mmc_spi_TXRX(), and tft_spi_TXRX().
void hspi_waitReady (void)
HSPI Ready wait.
Returns
void
Definition at line 203 of file hspi.c.
Referenced by ADF4351_spi_begin(), ADF4351_spi_end(), ADF4351_spi_init(), esp_yield(), hspi_config(), hspi_cs_disable(), hspi_cs_enable(), hspi_init(), hspi_RX(), hspi_TX(), hspi_TXRX(), loop_wrapper(), mmc_power_off(), mmc_spi_init(), tft_spi_begin(), tft_spi_end(), tft_spi_RX(), tft_spi_TX(), and tft_spi_TXRX().
static void hspi_writeFIFO (uint8_t * write_data, int bytes) [static]
HSPI FIFO write in units of 32 bits (4 byte words)
Parameters
in write_data write buffer
in bytes bytes to write
Returns
void
Definition at line 213 of file hspi.c.
Referenced by hspi_RX(), hspi_TX(), and hspi_TXRX().
Variable Documentation
uint8_t _cs_pin = 0xff
hspi CS cached value
Definition at line 42 of file hspi.c.
Referenced by hspi_cs_disable(), hspi_cs_enable(), and hspi_cs_status().
_hspi_init_done = 0 [static]
Definition at line 85 of file hspi.c.
Referenced by hspi_init().
uint16_t hspi_clock = -1
hspi clock cached value
Definition at line 88 of file hspi.c.
Referenced by hspi_init().