driver/ili9341_adafruit.c File Reference
#include <ets_sys.h>
*
#include <osapi.h>
*
#include <os_type.h>
*
#include <gpio.h>
*
#include <mem.h>
*
#include `hspi.h`
*
#include `font.h`
*
#include `util.h`
*
#include `ili9341_adafruit.h`
*
#include `ili9341.h`
*
Functions
MEMSPACE void tft_configRegister (void)
Initialize ILI9341 display.
void tft_drawFastVLine (int16_t x, int16_t y, int16_t h, uint16_t color)
Fast virtical line drawing FIXME use MADCTL and fill.
void tft_drawFastHLine (int16_t x, int16_t y, int16_t w, uint16_t color)
Fast virtical line drawing FIXME use MADCTL and fill.
MEMSPACE void tft_drawBitmap (int16_t x, int16_t y, const uint16_t *bitmap, int16_t w, int16_t h)
Draw bitmap FIXME use MADCTL and fill.
MEMSPACE void tft_drawCircle (int16_t x0, int16_t y0, int16_t r, uint16_t color)
Draw a circle outline.
MEMSPACE void tft_drawCircleHelper (int16_t x0, int16_t y0, int16_t r, uint8_t cornername, uint16_t color)
Draw a circle helper.
MEMSPACE void tft_fillCircleHelper (int16_t x0, int16_t y0, int16_t r, uint8_t cornername, int16_t delta, uint16_t color)
Fill circle helper.
MEMSPACE void tft_fillCircle (int16_t x0, int16_t y0, int16_t r, uint16_t color)
Fill circle.
MEMSPACE void tft_drawRect (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
Draw a rectangle.
MEMSPACE void tft_drawRoundRect (int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t color)
Draw a rounded rectangle.
MEMSPACE void tft_fillRoundRect (int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t color)
Fill a rounded rectangle.
MEMSPACE void tft_drawTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t color)
Draw a triangle.
MEMSPACE void tft_fillTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t color)
Fill a triangle.
Function Documentation
MEMSPACE void tft_configRegister (void)
Initialize ILI9341 display.
This is the core graphics library for all our displays, providing a common set of graphics primitives (points, lines, circles, etc.). It needs to be paired with a hardware-specific library for each display device we carry (to handle the lower-level functions).
Adafruit invests time and resources providing this open source code, please support Adafruit & open-source hardware by purchasing products from Adafruit!
Copyright (c) 2013 Adafruit Industries. All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS `AS IS` AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Returns
void
Definition at line 58 of file ili9341_adafruit.c.
Referenced by tft_init().
MEMSPACE void tft_drawBitmap (int16_t x, int16_t y, const uint16_t * bitmap, int16_t w, int16_t h)
Draw bitmap FIXME use MADCTL and fill.
Parameters
in x X offset
in y Y offset
in w Width of bitmap
in h Height of bitmap
Returns
void
Definition at line 206 of file ili9341_adafruit.c.
MEMSPACE void tft_drawCircle (int16_t x0, int16_t y0, int16_t r, uint16_t color)
Draw a circle outline.
Parameters
in x X offset
in y Y offset
in r Radius of circle
in color Color
Returns
void
Definition at line 230 of file ili9341_adafruit.c.
Referenced by test().
MEMSPACE void tft_drawCircleHelper (int16_t x0, int16_t y0, int16_t r, uint8_t cornername, uint16_t color)
Draw a circle helper.
Parameters
in x0 X offset
in y0 Y offset
in r Radius of circle
in cornername Corner to draw
in color Color
Returns
void
Definition at line 276 of file ili9341_adafruit.c.
Referenced by tft_drawRoundRect().
void tft_drawFastHLine (int16_t x, int16_t y, int16_t w, uint16_t color)
Fast virtical line drawing FIXME use MADCTL and fill.
Parameters
in x X offset
in y Y offset
in w Width of line
in color Color
Returns
void
Definition at line 191 of file ili9341_adafruit.c.
Referenced by tft_drawRect(), tft_drawRoundRect(), and tft_fillTriangle().
void tft_drawFastVLine (int16_t x, int16_t y, int16_t h, uint16_t color)
Fast virtical line drawing FIXME use MADCTL and fill.
Parameters
in x X offset
in y Y offset
in h Height of line
in color Color
Returns
void
Definition at line 177 of file ili9341_adafruit.c.
Referenced by tft_drawRect(), tft_drawRoundRect(), tft_fillCircle(), and tft_fillCircleHelper().
MEMSPACE void tft_drawRect (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
Draw a rectangle.
Parameters
in x X offset
in y Y offset
in w Width
in h Height
in color Color
Returns
void
Definition at line 380 of file ili9341_adafruit.c.
MEMSPACE void tft_drawRoundRect (int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t color)
Draw a rounded rectangle.
Parameters
in x X offset
in y Y offset
in w Width
in h Height
in r Radius
in color Color
Returns
void
Definition at line 400 of file ili9341_adafruit.c.
MEMSPACE void tft_drawTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t color)
Draw a triangle.
Parameters
in x0 X0 offset
in y0 Y0 offset
in x1 X1 offset
in y1 Y1 offset
in x2 X2 offset
in y2 Y2 offset
in color Color
Returns
void
Definition at line 448 of file ili9341_adafruit.c.
MEMSPACE void tft_fillCircle (int16_t x0, int16_t y0, int16_t r, uint16_t color)
Fill circle.
Parameters
in x0 X offset
in y0 Y offset
in color Color
Returns
void
Definition at line 364 of file ili9341_adafruit.c.
MEMSPACE void tft_fillCircleHelper (int16_t x0, int16_t y0, int16_t r, uint8_t cornername, int16_t delta, uint16_t color)
Fill circle helper.
Parameters
in x0 X offset
in y0 Y offset
in r Radius of circle
in cornername Corner to draw
in delta X or X offset
in color Color
Returns
void
Definition at line 328 of file ili9341_adafruit.c.
Referenced by tft_fillCircle(), and tft_fillRoundRect().
MEMSPACE void tft_fillRoundRect (int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t color)
Fill a rounded rectangle.
Parameters
in x X offset
in y Y offset
in w Width
in h Height
in r Radius
in color Color
Returns
void
Definition at line 425 of file ili9341_adafruit.c.
MEMSPACE void tft_fillTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t color)
Fill a triangle.
Parameters
in x0 X0 offset
in y0 Y0 offset
in x1 X1 offset
in y1 Y1 offset
in x2 X2 offset
in y2 Y2 offset
in color Color
Returns
void
Definition at line 468 of file ili9341_adafruit.c.