display/ili9341.h File Reference
ili9341 driver inspired by Adafruit ili9341 code All code in this file has been rewritten by Mike Gore
#include `font.h`
*
#include `ili9341_adafruit.h`
*
Data Structures
struct window
Macros
#define MEMSPACE
#define WEAK_ATR __attribute__((weak))
#define FONT_VAR 1
#define WRAP_H 2
#define WRAP_V 4
#define WRAP (WRAP_H | WRAP_V)
#define TFT_W (MAX_TFT_X-MIN_TFT_X+1)
#define TFT_H (MAX_TFT_Y-MIN_TFT_Y+1)
#define TFT_XOFF (MIN_TFT_X)
#define TFT_YOFF (MIN_TFT_Y)
#define tft_RGBto565(r, g, b) ((uint16_t) (((r) & 0xf8) << 8) | (((g) & 0xfc) << 3) | (((b) & 0xf8) >>3))
Pass 8-bit (each) R,G,B, get back 16-bit packed color ILI9341 defaults to MSB/LSB data so we have to reverse it.
#define SWAP(a, b) do { a ^= b; b ^= a; a ^= b; } while(0)
#define ABS(x) ((x)<0 ? -(x) : (x))
Functions
int font_max ()
int font_H (int font)
Get font height used for line to line spacing.
int font_W (int font)
Get font Width used for character to character spacing.
int font_attr (window *win, int c, _fontc *f)
Get font attributes for a font.
void tft_drawChar (window *win, uint8_t c)
Display a character and optionally wrap the graphic cursor.
void tft_Cmd (uint8_t cmd)
Transmit 8 bit command.
uint8_t tft_Data (uint8_t data)
Transmit 8 bit data amd read 8bit data.
void tft_Cmd_Data_TX (uint8_t cmd, uint8_t *data, int bytes)
Transmit 8 bit command and optionally send data buffer.
int32_t tft_abs_window (window *win, int16_t x, int16_t y, int16_t w, int16_t h)
=============================================================
int32_t tft_rel_window (window *win, int16_t x, int16_t y, int16_t w, int16_t h)
Set the ili9341 working window by relative position and size Note: Function clips x,y,w,y.
MEMSPACE uint32_t tft_readRegister (uint8_t command, uint8_t parameter)
====================================
MEMSPACE uint32_t tft_readId (void)
Read ILI9341 device ID should be 9341 This does not work for really high SPI clock speeds Make sure that when called the clock speed in reduced.
void tft_bit_blit (window *win, uint8_t *ptr, int16_t x, int16_t y, int16_t w, int16_t h)
BLIT functions
void tft_fillWin (window *win, uint16_t color)
Fill functions
void tft_fillRectWH (window *win, int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
Partial window Fill with color We clip the window to the current view.
void tft_fillRectXY (window *win, int16_t x, int16_t y, int16_t xl, int16_t yl, uint16_t color)
Fill rectangle with color We clip the window to the current view.
void tft_drawPixel (window *win, int16_t x, int16_t y, int16_t color)
Pixel functions
void tft_writeRect (window *win, int16_t x, int16_t y, int16_t w, int16_t h, uint16_t *color)
Write a rectangle pixel array.
void tft_readRect (window *win, int16_t x, int16_t y, int16_t w, int16_t h, uint16_t *color)
void tft_Vscroll (window *win, int dir)
Scroll window up by dir lines We start at the top of the window and move down.
uint16_t tft_readPixel (window *win, int16_t x, int16_t y)
Read one pixel and return color in 1bit 565 RGB format We clip the window to the current view Note: Read Memory must be done in a continious write/read operation Chip select can not be deactivated for the transaction.
MEMSPACE void tft_setRotation (uint8_t m)
Set Display rotation, applies to the master window only Set hardware display rotation and memory fill option bits Update software display limits FIXME Work in progress.
void tft_565toRGB (uint16_t color, uint8_t *r, uint8_t *g, uint8_t *b)
Color conversions
MEMSPACE void tft_invertDisplay (int flag)
Invert the display.
MEMSPACE int tft_window_clip (window *win)
Clip window structure to TFT limits.
MEMSPACE int tft_window_clip_args (window *win, int16_t *x, int16_t *y, int16_t *w, int16_t *h)
clip arguments to window limits Arguments position x,y width w and height h to be clipped
MEMSPACE void tft_window_init (window *win, int16_t x, int16_t y, int16_t w, int16_t h)
Initialize window structure we default values FIXME check x+w, y+h absolute limits against TFT limuts.
MEMSPACE void tft_setTextColor (window *win, uint16_t fg, uint16_t bg)
====================================
MEMSPACE void tft_setpos (window *win, int16_t x, int16_t y)
Set current window text pointer in pixels (per current rotation)
MEMSPACE void tft_set_textpos (window *win, int16_t x, int16_t y)
Set current window text pointer in characters (per current rotation) - overall font bounding box.
MEMSPACE void tft_set_font (window *win, uint16_t index)
Set current font size (per current rotation)
MEMSPACE void tft_font_fixed (window *win)
MEMSPACE void tft_font_var (window *win)
Set current font type to variable.
int tft_get_font_height (window *win)
Get font height.
void tft_drawFastVLine (window *win, int16_t x, int16_t y, int16_t h, uint16_t color)
Fast virtical line drawing.
void tft_drawFastHLine (window *win, int16_t x, int16_t y, int16_t w, uint16_t color)
Fast virtical line drawing.
void tft_drawLine (window *win, int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint16_t color)
Draw line From my blit test code testit.c 1984 - 1985 Mike Gore.
MEMSPACE void tft_cleareol (window *win)
Character and String functions
MEMSPACE void tft_clearline (window *win)
Clear display text line.
void tft_putch (window *win, int c)
put character in current winoow
void tft_spi_init (uint32_t prescale)
Obtain SPI bus for TFT display, assert chip select return: void.
void tft_spi_begin (void)
Obtain SPI bus for TFT display, assert chip select return: void.
void tft_spi_end (void)
Release SPI bus from TFT display, deassert chip select return: void.
void tft_reset_init (void)
Initialize ILI9341 reset GPIO return: void.
void tft_reset_enable (void)
enable ILI9341 reset return: void
void tft_addr_init (void)
Initialize ILI9341 command/data GPIO return: void.
void tft_reset_disable (void)
disnable ILI9341 reset return: void
void tft_spi_TX (uint8_t *data, int bytes, uint8_t command)
Transmit 8 bit data array.
void tft_spi_TXRX (uint8_t *data, int bytes, uint8_t command)
Transmit and read 8 bit data array.
void tft_spi_RX (uint8_t *data, int bytes, uint8_t command)
read 8 bit data array
MEMSPACE window * tft_init (void)
Initialize TFT.
Detailed Description
ili9341 driver inspired by Adafruit ili9341 code All code in this file has been rewritten by Mike Gore
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
Copyright 2013 Adafruit Industries. All rights reserved.
See also
https://github.com/adafruit/Adafruit-GFX-Library
Line drawing function CERTS
See also
https://github.com/CHERTS/esp8266-devkit/tree/master/Espressif/examples/esp8266_ili9341
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Macro Definition Documentation
#define ABS(x) ((x)<0 ? -(x) : (x))
Definition at line 83 of file ili9341.h.
Referenced by tft_drawFastHLine().
#define FONT_VAR 1
Definition at line 65 of file ili9341.h.
Referenced by font_attr(), tft_font_fixed(), and tft_font_var().
#define MEMSPACE
Definition at line 53 of file ili9341.h.
#define SWAP(a, b) do { a ^= b; b ^= a; a ^= b; } while(0)
Definition at line 82 of file ili9341.h.
Referenced by tft_fillRectXY(), and tft_fillTriangle().
#define TFT_H (MAX_TFT_Y-MIN_TFT_Y+1)
Definition at line 71 of file ili9341.h.
Referenced by tft_init(), and tft_setRotation().
#define tft_RGBto565(r, g, b) ((uint16_t) (((r) & 0xf8) << 8) | (((g) & 0xfc) << 3) | (((b) & 0xf8) >>3))
Pass 8-bit (each) R,G,B, get back 16-bit packed color ILI9341 defaults to MSB/LSB data so we have to reverse it.
Parameters
in r red data
in b blue data
in g green data
Definition at line 80 of file ili9341.h.
Referenced by loop(), setup(), tft_readPixel(), and tft_readRect().
#define TFT_W (MAX_TFT_X-MIN_TFT_X+1)
Definition at line 70 of file ili9341.h.
Referenced by tft_init(), tft_setRotation(), and tft_Vscroll().
#define TFT_XOFF (MIN_TFT_X)
Definition at line 72 of file ili9341.h.
Referenced by tft_init(), and tft_setRotation().
#define TFT_YOFF (MIN_TFT_Y)
Definition at line 73 of file ili9341.h.
Referenced by tft_init(), and tft_setRotation().
#define WEAK_ATR __attribute__((weak))
Definition at line 58 of file ili9341.h.
#define WRAP (WRAP_H | WRAP_V)
Definition at line 68 of file ili9341.h.
#define WRAP_H 2
Definition at line 66 of file ili9341.h.
Referenced by tft_drawChar(), tft_putch(), and tft_window_init().
#define WRAP_V 4
Definition at line 67 of file ili9341.h.
Referenced by tft_drawChar().
Function Documentation
int font_attr (window * win, int c, _fontc * f)
Get font attributes for a font.
Parameters
in *win Window Structure
in c character
in *f font structure
Returns
font number
Definition at line 94 of file font.c.
Referenced by tft_cleareol(), tft_clearline(), tft_drawChar(), tft_get_font_height(), and tft_putch().
int font_H (int font)
Get font height used for line to line spacing.
Parameters
in font font number
Returns
Height in pixels
Definition at line 70 of file font.c.
Referenced by setup(), and tft_set_textpos().
int font_max ()
Definition at line 59 of file font.c.
Referenced by tft_set_font().
int font_W (int font)
Get font Width used for character to character spacing.
Parameters
in font font number
Returns
Width in pixels
Definition at line 80 of file font.c.
Referenced by tft_set_textpos().
void tft_565toRGB (uint16_t color, uint8_t * r, uint8_t * g, uint8_t * b)
Color conversions
====================================Convert 16bit colr into 8-bit (each) R,G,B ILI9341 defaults to MSB/LSB data so we have to reverse it
Parameters
in color 16bit color
out *r red data
out *b blue data
out *g green data
Definition at line 752 of file ili9341.c.
int32_t tft_abs_window (window * win, int16_t x, int16_t y, int16_t w, int16_t h)
=============================================================
====================================
window limits
Set the ili9341 working window by absolute position and size Note: Function clips x,y,w,y
Parameters
in x Starting X offset
in y Starting Y offset
in w Width
in h Height
Returns
(w * h) after clipping
Definition at line 101 of file ili9341.c.
Referenced by tft_rel_window().
void tft_addr_init (void)
Initialize ILI9341 command/data GPIO return: void.
Definition at line 102 of file ili9341_hal.c.
Referenced by tft_init().
void tft_bit_blit (window * win, uint8_t * ptr, int16_t x, int16_t y, int16_t w, int16_t h)
BLIT functions
BLIT a bit array to the display
Parameters
in win* window structure
in *ptr bit array w * h in size
in x BLITX offset
in y BLIT Y offset
in w BLIT Width
in h BLIT Height
Returns
void TODO CLIP window - depends on blit array
Definition at line 237 of file ili9341.c.
Referenced by tft_drawChar().
MEMSPACE void tft_cleareol (window * win)
Character and String functions
====================================Clear display to end of line
Parameters
in win* window structure return: void, win->x = win->w
Definition at line 1138 of file ili9341.c.
Referenced by loop(), and tft_putch().
MEMSPACE void tft_clearline (window * win)
Clear display text line.
Parameters
in win* window structure return: void, win->x = 0
Definition at line 1158 of file ili9341.c.
void tft_Cmd (uint8_t cmd)
Transmit 8 bit command.
=============================================================
Parameters
in cmd display command return: void status is in data array - bytes in size
Definition at line 53 of file ili9341.c.
Referenced by tft_bit_blit(), tft_Cmd_Data_TX(), tft_fillRectWH(), tft_invertDisplay(), tft_readPixel(), tft_readRect(), tft_readRegister(), and tft_writeRect().
void tft_Cmd_Data_TX (uint8_t cmd, uint8_t * data, int bytes)
Transmit 8 bit command and optionally send data buffer.
Parameters
in cmd display command
in *data data buffer to send after command
in bytes data buffer size return: void status is in data array - bytes in size
Definition at line 72 of file ili9341.c.
Referenced by tft_abs_window(), tft_configRegister(), tft_drawPixel(), and tft_setRotation().
uint8_t tft_Data (uint8_t data)
Transmit 8 bit data amd read 8bit data.
Parameters
in data display command return: read result
Definition at line 61 of file ili9341.c.
Referenced by tft_readRegister().
void tft_drawChar (window * win, uint8_t c)
Display a character and optionally wrap the graphic cursor.
See also
tft_putch for main output function Does not handle control characters
Parameters
in *win Window Structure of active window
in c character
Returns
void TODO: To make proportional fonts render even better we should reduce the font gap so that all of the active pixels between two fonts come no nearer then a defined value. Example: consider the characters `Td`, the 'd' can actually be part way INSIDE the T
Definition at line 200 of file font.c.
Referenced by tft_putch().
void tft_drawFastHLine (window * win, int16_t x, int16_t y, int16_t w, uint16_t color)
Fast virtical line drawing.
Parameters
in *win window structure
in x X offset
in y Y offset
in w Width of line
in color Color
Returns
void
Definition at line 1017 of file ili9341.c.
Referenced by tft_drawRect(), tft_drawRoundRect(), and tft_fillTriangle().
void tft_drawFastVLine (window * win, int16_t x, int16_t y, int16_t h, uint16_t color)
Fast virtical line drawing.
Parameters
in *win window structure
in x X offset
in y Y offset
in h Height of line
in color Color
Returns
void
Definition at line 1002 of file ili9341.c.
Referenced by tft_drawRect(), tft_drawRoundRect(), tft_fillCircle(), and tft_fillCircleHelper().
void tft_drawLine (window * win, int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint16_t color)
Draw line From my blit test code testit.c 1984 - 1985 Mike Gore.
Parameters
in win* window structure
in x0 X Start
in y0 Y Start
in x1 X End
in y1 Y End
in color color to set
Returns
void Draw line Draw line from CERTS https://github.com/CHERTS/esp8266-devkit/tree/master/Espressif/examples/esp8266_ili9341
Parameters
in win* window structure
in x0 X Start
in y0 Y Start
in x1 X End
in y1 Y End
in color color to set
Returns
void
Definition at line 1077 of file ili9341.c.
Referenced by tft_drawFastHLine(), tft_drawTriangle(), and wire_draw().
void tft_drawPixel (window * win, int16_t x, int16_t y, int16_t color)
Pixel functions
====================================Draw one pixel set to color in 16bit 565 RGB format We clip the window to the current view
Parameters
in win* window structure
in x X Start
in y Y Start
in color color to set
Returns
void
Definition at line 440 of file ili9341.c.
Referenced by tft_bit_blit(), tft_drawCircle(), tft_drawCircleHelper(), tft_drawFastHLine(), and tft_writeRect().
void tft_fillRectWH (window * win, int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
Partial window Fill with color We clip the window to the current view.
Parameters
in win* window structure
in x X Start
in y Y Start
in w Width
in h Height
in color Fill color
Returns
void
Definition at line 351 of file ili9341.c.
Referenced by tft_cleareol(), tft_clearline(), tft_drawChar(), tft_drawFastHLine(), tft_drawFastVLine(), tft_fillRectXY(), tft_fillRoundRect(), tft_fillWin(), tft_putch(), and tft_Vscroll().
void tft_fillRectXY (window * win, int16_t x, int16_t y, int16_t xl, int16_t yl, uint16_t color)
Fill rectangle with color We clip the window to the current view.
Parameters
in win* window structure
in x X Start
in y Y Start
in xl X End
in yl Y End
in color Fill color
Returns
void
Definition at line 413 of file ili9341.c.
Referenced by tft_drawFastHLine().
void tft_fillWin (window * win, uint16_t color)
Fill functions
====================================Fill window
Parameters
in win* window structure
in color Fill color
Definition at line 336 of file ili9341.c.
Referenced by setup(), tft_init(), and tft_putch().
MEMSPACE void tft_font_fixed (window * win)
Only works if font is proportional type
Parameters
in win* window structure return: void
Definition at line 966 of file ili9341.c.
Referenced by loop().
MEMSPACE void tft_font_var (window * win)
Set current font type to variable.
Parameters
in win* window structure return: void
Definition at line 976 of file ili9341.c.
Referenced by setup().
int tft_get_font_height (window * win)
Get font height.
Parameters
in win* window structure return: font Height or zero on error
Definition at line 984 of file ili9341.c.
MEMSPACE window* tft_init (void)
Initialize TFT.
Returns
diplay ID 9341
Definition at line 168 of file ili9341_hal.c.
Referenced by setup().
MEMSPACE void tft_invertDisplay (int flag)
Invert the display.
Parameters
in flag true or false
Returns
void
Definition at line 764 of file ili9341.c.
void tft_putch (window * win, int c)
put character in current winoow
Parameters
in win* window structure
in c character return: void
Definition at line 1180 of file ili9341.c.
Referenced by _putc_win(), and _putc_win_len().
MEMSPACE uint32_t tft_readId (void)
Read ILI9341 device ID should be 9341 This does not work for really high SPI clock speeds Make sure that when called the clock speed in reduced.
See also
tft_init
Returns
32bit value with DIPLAY ID
Paramter 0 is unused See Read ID4 Command (0xd3) for a description of the parameters
Definition at line 209 of file ili9341.c.
Referenced by tft_init().
uint16_t tft_readPixel (window * win, int16_t x, int16_t y)
Read one pixel and return color in 1bit 565 RGB format We clip the window to the current view Note: Read Memory must be done in a continious write/read operation Chip select can not be deactivated for the transaction.
Parameters
in win* window structure
in x X Start
in y Y Start
Returns
color in 565 format
Definition at line 671 of file ili9341.c.
void tft_readRect (window * win, int16_t x, int16_t y, int16_t w, int16_t h, uint16_t * color)
Definition at line 558 of file ili9341.c.
Referenced by loop(), and tft_Vscroll().
MEMSPACE uint32_t tft_readRegister (uint8_t command, uint8_t parameter)
====================================
====================================================================== SPIRead parameters on SPI bus ILI9341 displays For those displays that do not have the EXTC pin asserted. This undocumented command overrides the restriction for reading command parameters. Notes: SPI configurations See M:[0-3] control bits in ILI9341 documenation
Refer to interface I and II modes. Most ILI9341 displays are using interface I, (Rather the interface II mode)
Parameters
in command command whose parameters we want to read
in parameter parameter number
Returns
16bit value
Definition at line 169 of file ili9341.c.
Referenced by tft_readId().
int32_t tft_rel_window (window * win, int16_t x, int16_t y, int16_t w, int16_t h)
Set the ili9341 working window by relative position and size Note: Function clips x,y,w,y.
Parameters
in win* window structure
in x Starting X offset
in y Starting Y offset
in w Width
in h Height
Returns
bytes w * h after clipping, 0 on error
Definition at line 143 of file ili9341.c.
Referenced by tft_bit_blit(), tft_drawPixel(), tft_fillRectWH(), tft_readPixel(), tft_readRect(), and tft_writeRect().
void tft_reset_disable (void)
disnable ILI9341 reset return: void
Definition at line 110 of file ili9341_hal.c.
Referenced by tft_init().
void tft_reset_enable (void)
enable ILI9341 reset return: void
Definition at line 93 of file ili9341_hal.c.
Referenced by tft_init().
void tft_reset_init (void)
Initialize ILI9341 reset GPIO return: void.
Definition at line 84 of file ili9341_hal.c.
Referenced by tft_init().
MEMSPACE void tft_set_font (window * win, uint16_t index)
Set current font size (per current rotation)
Parameters
in win* window structure
in index font index (for array of fonts) return: void
Definition at line 955 of file ili9341.c.
Referenced by loop(), and setup().
MEMSPACE void tft_set_textpos (window * win, int16_t x, int16_t y)
Set current window text pointer in characters (per current rotation) - overall font bounding box.
Parameters
in win* window structure
in x x offset
in y y oofset return: void
Definition at line 942 of file ili9341.c.
Referenced by loop(), and setup().
MEMSPACE void tft_setpos (window * win, int16_t x, int16_t y)
Set current window text pointer in pixels (per current rotation)
Parameters
in win* window structure
in x x offset
in y y oofset return: void
Definition at line 929 of file ili9341.c.
Referenced by loop().
MEMSPACE void tft_setRotation (uint8_t m)
Set Display rotation, applies to the master window only Set hardware display rotation and memory fill option bits Update software display limits FIXME Work in progress.
do we want to handle exchanging min/max values - rather then set them ?
Returns
void
Definition at line 701 of file ili9341.c.
Referenced by setup(), and tft_init().
MEMSPACE void tft_setTextColor (window * win, uint16_t fg, uint16_t bg)
====================================
Set text forground and background color
Parameters
in win* window structure
in fg forground color
in bg background color
Returns
void
Definition at line 916 of file ili9341.c.
Referenced by setup().
void tft_spi_begin (void)
Obtain SPI bus for TFT display, assert chip select return: void.
Definition at line 70 of file ili9341_hal.c.
Referenced by tft_bit_blit(), tft_Cmd_Data_TX(), tft_fillRectWH(), tft_invertDisplay(), tft_readPixel(), tft_readRect(), tft_readRegister(), and tft_writeRect().
void tft_spi_end (void)
Release SPI bus from TFT display, deassert chip select return: void.
Definition at line 77 of file ili9341_hal.c.
Referenced by tft_bit_blit(), tft_Cmd_Data_TX(), tft_fillRectWH(), tft_invertDisplay(), tft_readPixel(), tft_readRect(), tft_readRegister(), and tft_writeRect().
void tft_spi_init (uint32_t prescale)
Obtain SPI bus for TFT display, assert chip select return: void.
Definition at line 63 of file ili9341_hal.c.
Referenced by tft_init().
void tft_spi_RX (uint8_t * data, int bytes, uint8_t command)
read 8 bit data array
Parameters
in *data data buffer to send
in bytes data buffer size
in command 1 = command, 0 = data return: void
Definition at line 155 of file ili9341_hal.c.
Referenced by tft_readRect().
void tft_spi_TX (uint8_t * data, int bytes, uint8_t command)
Transmit 8 bit data array.
Parameters
in *data data buffer to send
in bytes data buffer size
in command 1 = command, 0 = data return: void
Definition at line 124 of file ili9341_hal.c.
Referenced by tft_bit_blit(), tft_Cmd(), tft_Cmd_Data_TX(), tft_fillRectWH(), and tft_writeRect().
void tft_spi_TXRX (uint8_t * data, int bytes, uint8_t command)
Transmit and read 8 bit data array.
Parameters
in *data data buffer to send
in bytes data buffer size
in command 1 = command, 0 = data return: void
Definition at line 139 of file ili9341_hal.c.
Referenced by tft_Data(), and tft_readPixel().
void tft_Vscroll (window * win, int dir)
Scroll window up by dir lines We start at the top of the window and move down.
Parameters
in win* window structure
in dir direction and count TODO +/- scroll direction
Definition at line 622 of file ili9341.c.
Referenced by tft_drawChar().
MEMSPACE int tft_window_clip (window * win)
Clip window structure to TFT limits.
Parameters
in win* window structure
Returns
0 - or - count of clipped values FIXME check negitive offsets, etc
Definition at line 778 of file ili9341.c.
MEMSPACE int tft_window_clip_args (window * win, int16_t * x, int16_t * y, int16_t * w, int16_t * h)
clip arguments to window limits Arguments position x,y width w and height h to be clipped
Parameters
in *win window structure we will use to clip arguments to.
in *x X argument offset
in *y Y argument offset
in *w W argument width
in *h H argument height
Returns
void FIXME check negitive offsets, etc
Definition at line 833 of file ili9341.c.
Referenced by tft_abs_window(), tft_bit_blit(), and tft_window_init().
MEMSPACE void tft_window_init (window * win, int16_t x, int16_t y, int16_t w, int16_t h)
Initialize window structure we default values FIXME check x+w, y+h absolute limits against TFT limuts.
Parameters
in win* window structure
in x X offset to window start - absolute
in y Y offset to window start - absolute
in w Window width
in h Window Height
Returns
void
Definition at line 886 of file ili9341.c.
Referenced by setup(), and tft_init().
void tft_writeRect (window * win, int16_t x, int16_t y, int16_t w, int16_t h, uint16_t * color)
Write a rectangle pixel array.
Parameters
in win* window structure
in x X offset
in y Y offset
in w Width
in h Height
in *color pixel array in 565 format
Returns
void
Definition at line 468 of file ili9341.c.
Referenced by tft_drawBitmap(), and tft_Vscroll().