esp8266/io.c File Reference
IO driver for ESP8255.
#include `user_config.h`
*
#include <eagle_soc.h>
*
#include <stdint.h>
*
#include <stdarg.h>
*
#include <string.h>
*
#include <math.h>
*
#include `hspi.h`
*
#include `gpio.h`
*
Functions
void MEMSPACE gpio_sfr_mode (int pin)
set GPIO pin to normal I/O mode
void chip_select_init (uint8_t pin)
void chip_select (uint8_t pin)
set chip enable
void chip_deselect (uint8_t pin)
set chip enable
void chip_select_init_all (int pin)
void chip_addr_init ()
void chip_addr (int addr)
void spi_waitReady ()
void spi_cs_enable (uint8_t cs)
SPI CS enable function, wait for previous tranaction to finish!
void spi_cs_disable (uint8_t cs)
SPI CS disable function, wait for previous tranaction to finish!
uint8_t spi_cs_status ()
SPI CS pin status return CS pin status.
void spi_init (uint32_t clock, int pin)
Obtain SPI bus for TFT display, assert chip select return: void.
void spi_begin (uint32_t clock, int pin)
Obtain SPI bus for TFT display, assert chip select return: void.
void spi_end (int pin)
Release SPI bus from TFT display, deassert chip select return: void.
void spi_TX_buffer (const uint8_t *data, int count)
SPI write buffer.
void spi_RX_buffer (const uint8_t *data, int count)
SPI read buffer.
void spi_TXRX_buffer (const uint8_t *data, int count)
SPI write/read buffer.
uint8_t spi_RX ()
SPI read 1 byte.
void spi_TX (uint8_t data)
SPI write 1 byte.
uint8_t spi_TXRX (uint8_t data)
SPI read and write 1 byte.
Variables
uint8_t _cs_pin = 0xff
Detailed Description
IO driver for ESP8255.
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
Please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
void chip_addr (int addr)
Definition at line 224 of file io.c.
void chip_addr_init (void)
Definition at line 201 of file io.c.
Referenced by setup(), and tft_addr_init().
void chip_deselect (uint8_t pin)
set chip enable
Definition at line 178 of file io.c.
Referenced by spi_cs_disable().
void chip_select (uint8_t pin)
set chip enable
Definition at line 172 of file io.c.
Referenced by spi_cs_enable().
void chip_select_init (uint8_t pin)
Definition at line 165 of file io.c.
Referenced by chip_select_init_all(), setup(), and tft_reset_init().
void chip_select_init_all (int pin)
Definition at line 183 of file io.c.
void MEMSPACE gpio_sfr_mode (int pin)
set GPIO pin to normal I/O mode
AVR GPIO MACROs.
Definition at line 37 of file io.c.
void spi_begin (uint32_t clock, int pin)
Obtain SPI bus for TFT display, assert chip select return: void.
Definition at line 323 of file io.c.
Referenced by ADF4351_spi_begin(), mmc_spi_begin(), and tft_spi_begin().
void spi_cs_disable (uint8_t cs)
SPI CS disable function, wait for previous tranaction to finish!
Parameters
in cs GPIO CS pin
Definition at line 285 of file io.c.
Referenced by loop(), spi_end(), and spi_init().
void spi_cs_enable (uint8_t cs)
SPI CS enable function, wait for previous tranaction to finish!
Parameters
in cs GPIO CS pin
Definition at line 269 of file io.c.
Referenced by spi_begin().
uint8_t spi_cs_status (void)
SPI CS pin status return CS pin status.
Definition at line 301 of file io.c.
Referenced by loop().
void spi_end (int pin)
Release SPI bus from TFT display, deassert chip select return: void.
Definition at line 331 of file io.c.
Referenced by ADF4351_spi_end(), mmc_spi_end(), and tft_spi_end().
void spi_init (uint32_t clock, int pin)
Obtain SPI bus for TFT display, assert chip select return: void.
Definition at line 308 of file io.c.
Referenced by ADF4351_spi_init(), mmc_fast(), mmc_slow(), spi_begin(), and tft_spi_init().
uint8_t spi_RX (void)
SPI read 1 byte.
Returns
uint8_t value
Definition at line 381 of file io.c.
void spi_RX_buffer (const uint8_t * data, int count)
SPI read buffer.
Parameters
in *data transmit buffer
in count number of bytes to write
Returns
void
Definition at line 355 of file io.c.
Referenced by mmc_spi_RX_buffer(), and tft_spi_RX().
void spi_TX (uint8_t data)
SPI write 1 byte.
Parameters
in data value to transmit
Returns
void
Definition at line 396 of file io.c.
void spi_TX_buffer (const uint8_t * data, int count)
SPI write buffer.
Parameters
in *data transmit buffer
in count number of bytes to write
Returns
void
Definition at line 341 of file io.c.
Referenced by mmc_spi_TX_buffer(), and tft_spi_TX().
uint8_t spi_TXRX (uint8_t data)
SPI read and write 1 byte.
Parameters
in data value to transmit
Returns
uint8_t value read
Definition at line 410 of file io.c.
Referenced by mmc_spi_TXRX().
void spi_TXRX_buffer (const uint8_t * data, int count)
SPI write/read buffer.
Parameters
in *data transmit/receive buffer
in count number of bytes to write
Returns
void
Definition at line 369 of file io.c.
Referenced by ADF4351_spi_txrx(), and tft_spi_TXRX().
void spi_waitReady (void)
Definition at line 257 of file io.c.
Referenced by spi_cs_disable(), spi_cs_enable(), tft_spi_RX(), tft_spi_TX(), and tft_spi_TXRX().
Variable Documentation
uint8_t _cs_pin = 0xff
Definition at line 266 of file io.c.
Referenced by spi_cs_disable(), spi_cs_enable(), and spi_cs_status().