\hypertarget{Makefile}{\section{Makefile File Reference}
\label{Makefile}\index{Makefile@{Makefile}}
}
\subsection*{Variables}
\begin{DoxyCompactItemize}
\item 
\hyperlink{Makefile_a03169c2c7e2ff706233c78422b0daf3a}{V\-E\-R\-B\-O\-S\-E}
\item 
E\-L fno inline functions \\*
nostdlib mlongcalls mtext \\*
section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- \\*
D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction \\*
sections fdata sections \hyperlink{Makefile_a0b0ec95cdd594ae63274ea3aa92e8bac}{L\-D\-F\-L\-A\-G\-S}
\item 
E\-L fno inline functions \\*
nostdlib mlongcalls mtext \\*
section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- \\*
D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction \\*
sections fdata sections no \\*
check sections u \\*
call\-\_\-user\-\_\-start \hyperlink{Makefile_a1af3a6ecef406b93f1a1db145b2cfd43}{Wl}
\item 
E\-L fno inline functions \\*
nostdlib mlongcalls mtext \\*
section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- \\*
D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction \\*
sections fdata sections no \\*
check sections u \\*
call\-\_\-user\-\_\-start static gc \\*
sections \hyperlink{Makefile_a3d2682475b097eef42d87fa20f765794}{Map}
\item 
E\-L fno inline functions \\*
nostdlib mlongcalls mtext \\*
section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- \\*
D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction \\*
sections fdata sections no \\*
check sections u \\*
call\-\_\-user\-\_\-start static gc \\*
sections \hyperlink{Makefile_a7caa220288c6621dffebfc3a50a851e1}{undefined}
\item 
E\-L fno inline functions \\*
nostdlib mlongcalls mtext \\*
section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- \\*
D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction \\*
sections fdata sections no \\*
check sections u \\*
call\-\_\-user\-\_\-start static gc \\*
sections \hyperlink{Makefile_a6b04d3dc9ff8a69521845b59ef6c33f1}{wrap}
\end{DoxyCompactItemize}


\subsection{Variable Documentation}
\hypertarget{Makefile_a0b0ec95cdd594ae63274ea3aa92e8bac}{\index{Makefile@{Makefile}!L\-D\-F\-L\-A\-G\-S@{L\-D\-F\-L\-A\-G\-S}}
\index{L\-D\-F\-L\-A\-G\-S@{L\-D\-F\-L\-A\-G\-S}!Makefile@{Makefile}}
\subsubsection[{L\-D\-F\-L\-A\-G\-S}]{\setlength{\rightskip}{0pt plus 5cm}E\-L fno inline functions nostdlib mlongcalls mtext section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction sections fdata sections L\-D\-F\-L\-A\-G\-S}}\label{Makefile_a0b0ec95cdd594ae63274ea3aa92e8bac}
{\bfseries Initial value\-:}
\begin{DoxyCode}
= -nostdlib 
    -\hyperlink{Makefile_a1af3a6ecef406b93f1a1db145b2cfd43}{Wl}
\end{DoxyCode}


Definition at line 123 of file Makefile.

\hypertarget{Makefile_a3d2682475b097eef42d87fa20f765794}{\index{Makefile@{Makefile}!Map@{Map}}
\index{Map@{Map}!Makefile@{Makefile}}
\subsubsection[{Map}]{\setlength{\rightskip}{0pt plus 5cm}E\-L fno inline functions nostdlib mlongcalls mtext section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction sections fdata sections no check sections u call\-\_\-user\-\_\-start static gc sections Map\hspace{0.3cm}{\ttfamily [static]}}}\label{Makefile_a3d2682475b097eef42d87fa20f765794}
{\bfseries Initial value\-:}
\begin{DoxyCode}
=map.txt  
    -\hyperlink{Makefile_a1af3a6ecef406b93f1a1db145b2cfd43}{Wl}
\end{DoxyCode}


Definition at line 128 of file Makefile.

\hypertarget{Makefile_a7caa220288c6621dffebfc3a50a851e1}{\index{Makefile@{Makefile}!undefined@{undefined}}
\index{undefined@{undefined}!Makefile@{Makefile}}
\subsubsection[{undefined}]{\setlength{\rightskip}{0pt plus 5cm}E\-L fno inline functions nostdlib mlongcalls mtext section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction sections fdata sections no check sections u call\-\_\-user\-\_\-start static gc sections undefined\hspace{0.3cm}{\ttfamily [static]}}}\label{Makefile_a7caa220288c6621dffebfc3a50a851e1}
{\bfseries Initial value\-:}
\begin{DoxyCode}
=\_xtos\_set\_exception\_handler 
    -\hyperlink{Makefile_a1af3a6ecef406b93f1a1db145b2cfd43}{Wl}
\end{DoxyCode}


Definition at line 129 of file Makefile.

\hypertarget{Makefile_a03169c2c7e2ff706233c78422b0daf3a}{\index{Makefile@{Makefile}!V\-E\-R\-B\-O\-S\-E@{V\-E\-R\-B\-O\-S\-E}}
\index{V\-E\-R\-B\-O\-S\-E@{V\-E\-R\-B\-O\-S\-E}!Makefile@{Makefile}}
\subsubsection[{V\-E\-R\-B\-O\-S\-E}]{\setlength{\rightskip}{0pt plus 5cm}V\-E\-R\-B\-O\-S\-E}}\label{Makefile_a03169c2c7e2ff706233c78422b0daf3a}


Definition at line 15 of file Makefile.

\hypertarget{Makefile_a1af3a6ecef406b93f1a1db145b2cfd43}{\index{Makefile@{Makefile}!Wl@{Wl}}
\index{Wl@{Wl}!Makefile@{Makefile}}
\subsubsection[{Wl}]{\setlength{\rightskip}{0pt plus 5cm}E\-L fno inline functions nostdlib mlongcalls mtext section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction sections fdata sections no check sections u call\-\_\-user\-\_\-start static gc sections Wl}}\label{Makefile_a1af3a6ecef406b93f1a1db145b2cfd43}


Definition at line 123 of file Makefile.

\hypertarget{Makefile_a6b04d3dc9ff8a69521845b59ef6c33f1}{\index{Makefile@{Makefile}!wrap@{wrap}}
\index{wrap@{wrap}!Makefile@{Makefile}}
\subsubsection[{wrap}]{\setlength{\rightskip}{0pt plus 5cm}E\-L fno inline functions nostdlib mlongcalls mtext section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction sections fdata sections no check sections u call\-\_\-user\-\_\-start static gc sections wrap\hspace{0.3cm}{\ttfamily [static]}}}\label{Makefile_a6b04d3dc9ff8a69521845b59ef6c33f1}
{\bfseries Initial value\-:}
\begin{DoxyCode}
=\_xtos\_set\_exception\_handler 
    -\hyperlink{Makefile_a1af3a6ecef406b93f1a1db145b2cfd43}{Wl}
\end{DoxyCode}


Definition at line 130 of file Makefile.

