\hypertarget{Makefile}{\section{Makefile File Reference}
\label{Makefile}\index{Makefile@{Makefile}}
}
\subsection*{Variables}
\begin{DoxyCompactItemize}
\item 
\hyperlink{Makefile_aaa9bbf75d7f8fc94a5c7dd9504b7a178}{B\-U\-I\-L\-D\-\_\-\-B\-A\-S\-E}
\item 
E\-L fno inline functions \\*
nostdlib mlongcalls mtext \\*
section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- \\*
D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction \\*
sections \hyperlink{Makefile_af8b8a61c029c5ab0a5518b7f5421c6ac}{M\-O\-D\-U\-L\-E\-S}
\item 
E\-L fno inline functions \\*
nostdlib mlongcalls mtext \\*
section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- \\*
D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction \\*
sections no check sections u \\*
call\-\_\-user\-\_\-start \hyperlink{Makefile_afb1782b240d70229ae5bc6b111f9794a}{Wl}
\item 
E\-L fno inline functions \\*
nostdlib mlongcalls mtext \\*
section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- \\*
D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction \\*
sections no check sections u \\*
call\-\_\-user\-\_\-start static gc \\*
sections \hyperlink{Makefile_a3f923b64cf6726ab0bfdd17b9aff0a96}{Map}
\item 
E\-L fno inline functions \\*
nostdlib mlongcalls mtext \\*
section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- \\*
D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction \\*
sections no check sections u \\*
call\-\_\-user\-\_\-start static gc \\*
sections \hyperlink{Makefile_a9324bb2c20136255586f3b51593c4291}{undefined} =\-\_\-xtos\-\_\-set\-\_\-exception\-\_\-handler -\/\hyperlink{Makefile_afb1782b240d70229ae5bc6b111f9794a}{Wl}
\end{DoxyCompactItemize}


\subsection{Variable Documentation}
\hypertarget{Makefile_aaa9bbf75d7f8fc94a5c7dd9504b7a178}{\index{Makefile@{Makefile}!B\-U\-I\-L\-D\-\_\-\-B\-A\-S\-E@{B\-U\-I\-L\-D\-\_\-\-B\-A\-S\-E}}
\index{B\-U\-I\-L\-D\-\_\-\-B\-A\-S\-E@{B\-U\-I\-L\-D\-\_\-\-B\-A\-S\-E}!Makefile@{Makefile}}
\subsubsection[{B\-U\-I\-L\-D\-\_\-\-B\-A\-S\-E}]{\setlength{\rightskip}{0pt plus 5cm}B\-U\-I\-L\-D\-\_\-\-B\-A\-S\-E}}\label{Makefile_aaa9bbf75d7f8fc94a5c7dd9504b7a178}


Definition at line 9 of file Makefile.

\hypertarget{Makefile_a3f923b64cf6726ab0bfdd17b9aff0a96}{\index{Makefile@{Makefile}!Map@{Map}}
\index{Map@{Map}!Makefile@{Makefile}}
\subsubsection[{Map}]{\setlength{\rightskip}{0pt plus 5cm}E\-L fno inline functions nostdlib mlongcalls mtext section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction sections no check sections u call\-\_\-user\-\_\-start static gc sections Map\hspace{0.3cm}{\ttfamily [static]}}}\label{Makefile_a3f923b64cf6726ab0bfdd17b9aff0a96}
{\bfseries Initial value\-:}
\begin{DoxyCode}
=map.txt  
-\hyperlink{Makefile_afb1782b240d70229ae5bc6b111f9794a}{Wl}
\end{DoxyCode}


Definition at line 220 of file Makefile.

\hypertarget{Makefile_af8b8a61c029c5ab0a5518b7f5421c6ac}{\index{Makefile@{Makefile}!M\-O\-D\-U\-L\-E\-S@{M\-O\-D\-U\-L\-E\-S}}
\index{M\-O\-D\-U\-L\-E\-S@{M\-O\-D\-U\-L\-E\-S}!Makefile@{Makefile}}
\subsubsection[{M\-O\-D\-U\-L\-E\-S}]{\setlength{\rightskip}{0pt plus 5cm}E\-L fno inline functions nostdlib mlongcalls mtext section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction sections M\-O\-D\-U\-L\-E\-S}}\label{Makefile_af8b8a61c029c5ab0a5518b7f5421c6ac}


Definition at line 179 of file Makefile.

\hypertarget{Makefile_a9324bb2c20136255586f3b51593c4291}{\index{Makefile@{Makefile}!undefined@{undefined}}
\index{undefined@{undefined}!Makefile@{Makefile}}
\subsubsection[{undefined}]{\setlength{\rightskip}{0pt plus 5cm}E\-L fno inline functions nostdlib mlongcalls mtext section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction sections no check sections u call\-\_\-user\-\_\-start static gc sections undefined =\-\_\-xtos\-\_\-set\-\_\-exception\-\_\-handler -\/{\bf Wl}\hspace{0.3cm}{\ttfamily [static]}}}\label{Makefile_a9324bb2c20136255586f3b51593c4291}


Definition at line 221 of file Makefile.

\hypertarget{Makefile_afb1782b240d70229ae5bc6b111f9794a}{\index{Makefile@{Makefile}!Wl@{Wl}}
\index{Wl@{Wl}!Makefile@{Makefile}}
\subsubsection[{Wl}]{\setlength{\rightskip}{0pt plus 5cm}E\-L fno inline functions nostdlib mlongcalls mtext section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction sections no check sections u call\-\_\-user\-\_\-start static gc sections Wl}}\label{Makefile_afb1782b240d70229ae5bc6b111f9794a}


Definition at line 179 of file Makefile.

