\hypertarget{Makefile}{\section{Makefile File Reference}
\label{Makefile}\index{Makefile@{Makefile}}
}
\subsection*{Variables}
\begin{DoxyCompactItemize}
\item 
\hyperlink{Makefile_aaa9bbf75d7f8fc94a5c7dd9504b7a178}{B\-U\-I\-L\-D\-\_\-\-B\-A\-S\-E}
\item 
E\-L fno inline functions \\*
nostdlib mlongcalls mtext \\*
section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- \\*
D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction \\*
sections fdata sections \hyperlink{Makefile_a61c8d9ae20beeb28ac4075403cc4ea41}{M\-O\-D\-U\-L\-E\-S}
\item 
E\-L fno inline functions \\*
nostdlib mlongcalls mtext \\*
section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- \\*
D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction \\*
sections fdata sections no \\*
check sections u \\*
call\-\_\-user\-\_\-start \hyperlink{Makefile_a1af3a6ecef406b93f1a1db145b2cfd43}{Wl}
\item 
E\-L fno inline functions \\*
nostdlib mlongcalls mtext \\*
section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- \\*
D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction \\*
sections fdata sections no \\*
check sections u \\*
call\-\_\-user\-\_\-start static gc \\*
sections \hyperlink{Makefile_a3d2682475b097eef42d87fa20f765794}{Map}
\item 
E\-L fno inline functions \\*
nostdlib mlongcalls mtext \\*
section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- \\*
D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction \\*
sections fdata sections no \\*
check sections u \\*
call\-\_\-user\-\_\-start static gc \\*
sections \hyperlink{Makefile_a7caa220288c6621dffebfc3a50a851e1}{undefined} =\-\_\-xtos\-\_\-set\-\_\-exception\-\_\-handler -\/\hyperlink{Makefile_a1af3a6ecef406b93f1a1db145b2cfd43}{Wl}
\end{DoxyCompactItemize}


\subsection{Variable Documentation}
\hypertarget{Makefile_aaa9bbf75d7f8fc94a5c7dd9504b7a178}{\index{Makefile@{Makefile}!B\-U\-I\-L\-D\-\_\-\-B\-A\-S\-E@{B\-U\-I\-L\-D\-\_\-\-B\-A\-S\-E}}
\index{B\-U\-I\-L\-D\-\_\-\-B\-A\-S\-E@{B\-U\-I\-L\-D\-\_\-\-B\-A\-S\-E}!Makefile@{Makefile}}
\subsubsection[{B\-U\-I\-L\-D\-\_\-\-B\-A\-S\-E}]{\setlength{\rightskip}{0pt plus 5cm}B\-U\-I\-L\-D\-\_\-\-B\-A\-S\-E}}\label{Makefile_aaa9bbf75d7f8fc94a5c7dd9504b7a178}


Definition at line 9 of file Makefile.

\hypertarget{Makefile_a3d2682475b097eef42d87fa20f765794}{\index{Makefile@{Makefile}!Map@{Map}}
\index{Map@{Map}!Makefile@{Makefile}}
\subsubsection[{Map}]{\setlength{\rightskip}{0pt plus 5cm}E\-L fno inline functions nostdlib mlongcalls mtext section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction sections fdata sections no check sections u call\-\_\-user\-\_\-start static gc sections Map\hspace{0.3cm}{\ttfamily [static]}}}\label{Makefile_a3d2682475b097eef42d87fa20f765794}
{\bfseries Initial value\-:}
\begin{DoxyCode}
=map.txt  
-\hyperlink{Makefile_a1af3a6ecef406b93f1a1db145b2cfd43}{Wl}
\end{DoxyCode}


Definition at line 226 of file Makefile.

\hypertarget{Makefile_a61c8d9ae20beeb28ac4075403cc4ea41}{\index{Makefile@{Makefile}!M\-O\-D\-U\-L\-E\-S@{M\-O\-D\-U\-L\-E\-S}}
\index{M\-O\-D\-U\-L\-E\-S@{M\-O\-D\-U\-L\-E\-S}!Makefile@{Makefile}}
\subsubsection[{M\-O\-D\-U\-L\-E\-S}]{\setlength{\rightskip}{0pt plus 5cm}E\-L fno inline functions nostdlib mlongcalls mtext section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction sections fdata sections M\-O\-D\-U\-L\-E\-S}}\label{Makefile_a61c8d9ae20beeb28ac4075403cc4ea41}


Definition at line 183 of file Makefile.

\hypertarget{Makefile_a7caa220288c6621dffebfc3a50a851e1}{\index{Makefile@{Makefile}!undefined@{undefined}}
\index{undefined@{undefined}!Makefile@{Makefile}}
\subsubsection[{undefined}]{\setlength{\rightskip}{0pt plus 5cm}E\-L fno inline functions nostdlib mlongcalls mtext section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction sections fdata sections no check sections u call\-\_\-user\-\_\-start static gc sections undefined =\-\_\-xtos\-\_\-set\-\_\-exception\-\_\-handler -\/{\bf Wl}\hspace{0.3cm}{\ttfamily [static]}}}\label{Makefile_a7caa220288c6621dffebfc3a50a851e1}


Definition at line 227 of file Makefile.

\hypertarget{Makefile_a1af3a6ecef406b93f1a1db145b2cfd43}{\index{Makefile@{Makefile}!Wl@{Wl}}
\index{Wl@{Wl}!Makefile@{Makefile}}
\subsubsection[{Wl}]{\setlength{\rightskip}{0pt plus 5cm}E\-L fno inline functions nostdlib mlongcalls mtext section literals D\-\_\-\-\_\-ets\-\_\-\-\_\- D\-I\-C\-A\-C\-H\-E\-\_\-\-F\-L\-A\-S\-H ffunction sections fdata sections no check sections u call\-\_\-user\-\_\-start static gc sections Wl}}\label{Makefile_a1af3a6ecef406b93f1a1db145b2cfd43}


Definition at line 183 of file Makefile.

