printf/mathio.c File Reference
#include <stdint.h>
*
#include <stdarg.h>
*
#include <string.h>
*
#include `mathio.h`
*
#include <math.h>
*
Functions
MEMSPACE int atodigit (int c, int radix)
Convert ASCII character to radix based digit , or -1.
MEMSPACE long atoh (const char *p)
Convert ASCII hex string to long integer.
MEMSPACE long aton (char *str, int base)
Convert ASCII string to number in a given base.
MEMSPACE long strtol (const char *nptr, char **endptr, int base)
Convert ASCII string to number in a given base.
MEMSPACE int atoi (const char *str)
Convert ASCII string to number in base 10.
MEMSPACE long atol (const char *str)
Convert ASCII string to number in base 10.
Function Documentation
MEMSPACE int atodigit (int c, int radix)
Convert ASCII character to radix based digit , or -1.
Parameters
in c character
in radix radix
Returns
radix based digit , or -1
See also
strtol
Definition at line 26 of file mathio.c.
Referenced by process_args(), and strtol().
MEMSPACE long atoh (const char * p)
Convert ASCII hex string to long integer.
Parameters
in p String to convert.
Returns
long integer result.
See also
strtol() for return overflow and underflow results.
Definition at line 47 of file mathio.c.
MEMSPACE int atoi (const char * str)
Convert ASCII string to number in base 10.
Parameters
in str string
Returns
int value
See also
strtol
Definition at line 125 of file mathio.c.
Referenced by html_status(), main(), parse_http_request(), and ReadBdf().
MEMSPACE long atol (const char * str)
Convert ASCII string to number in base 10.
Parameters
in str string
Returns
long value
See also
strtol
Definition at line 140 of file mathio.c.
MEMSPACE long aton (char * str, int base)
Convert ASCII string to number in a given base.
Parameters
in str string
in base radix
Returns
long value
See also
strtol
Definition at line 61 of file mathio.c.
MEMSPACE long strtol (const char * nptr, char ** endptr, int base)
Convert ASCII string to number in a given base.
Parameters
in nptr string
in endptr pointer to string pointer return value
in base radix
Returns
long value
Definition at line 78 of file mathio.c.
Referenced by atoh(), atoi(), atol(), aton(), main(), and setdate_r().