lib/matrix.c File Reference
matrix functions
#include `user_config.h`
*
#include `matrix.h`
*
Functions
int TestSquare (mat_t MatA)
Credits: https://www.cs.rochester.edu/~brown/Crypto/assts/projects/adj.html.
mat_t MatAlloc (int rows, int cols)
Allocate a matrix.
mat_t MatAllocSQ (int size)
Allocate a matrix.
void MatFree (mat_t matF)
Free a matrix.
mat_t MatLoad (void *V, int rows, int cols)
Load a matrix.
mat_t MatLoadSQ (void *V, int size)
Load a square matrix.
void MatPrint (mat_t matrix)
Print a matrix.
mat_t DeleteRowCol (mat_t MatA, int row, int col)
Create smaller matrix by deleatting specified row and colume Used by Minor and Cofactor.
mat_t Transpose (mat_t MatA)
Transpose matrix.
float Minor (mat_t MatA, int row, int col)
Compute determinate of the minor submatrix Minor submatrix has one less row and column as a result.
float Cofactor (mat_t MatA, int row, int col)
Cofactor is determinate of minor submatrix * (-1)exp(row+col) Minor submatrix has one less row and column as a result.
mat_t Adjugate (mat_t MatA)
Adjugate is transpose of cofactor matrix of A.
float Determinant (mat_t MatA)
Determinant by recursion using Cofactors.
mat_t Invert (mat_t MatA)
Calculate Matrix Inverse.
mat_t PseudoInvert (mat_t MatA)
Calculate Pseudo Matrix Inverse Used for least square fitting of non square matrix with excess solutions Pseudo Inverse matrix(A) = 1/(AT × A) × AT.
mat_t MatMul (mat_t MatA, mat_t MatB)
Multiply two matrix.
Detailed Description
matrix functions
Copyright 2016 Mike Gore, GPL License
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
mat_t Adjugate (mat_t MatA)
Adjugate is transpose of cofactor matrix of A.
See also
https://en.wikipedia.org/wiki/Adjugate_matrix
Parameters
in MatA matrix A
Returns
Adjugate or A
Definition at line 300 of file matrix.c.
Referenced by Invert(), and MatMul().
float Cofactor (mat_t MatA, int row, int col)
Cofactor is determinate of minor submatrix * (-1)exp(row+col) Minor submatrix has one less row and column as a result.
See also
https://en.wikipedia.org/wiki/Cofactor
Parameters
in MatA matrix A
in row row to delete
in col col to delete
Returns
Determinate * (-1)exp(row + col)
Definition at line 286 of file matrix.c.
Referenced by Adjugate(), and Determinant().
mat_t DeleteRowCol (mat_t MatA, int row, int col)
Create smaller matrix by deleatting specified row and colume Used by Minor and Cofactor.
Parameters
in MatA matrix A - row and col must be >= 2
in row row to delete
in col col to delete
Returns
submatrix
Definition at line 191 of file matrix.c.
Referenced by Minor().
float Determinant (mat_t MatA)
Determinant by recursion using Cofactors.
See also
https://en.wikipedia.org/wiki/Determinant
Parameters
in MatA square matrix A
Returns
Determinant or 0
Definition at line 324 of file matrix.c.
Referenced by Invert(), and Minor().
mat_t Invert (mat_t MatA)
Calculate Matrix Inverse.
See also
https://en.wikipedia.org/wiki/Invertible_matrix Method used: Adjugate(MatA) / Det(MatA)
Parameters
in MatA square matrix A input
Returns
Inverse of MatA or error
Definition at line 372 of file matrix.c.
Referenced by MatMul(), PseudoInvert(), and user_help().
mat_t MatAlloc (int rows, int cols)
Allocate a matrix.
Parameters
in size size of square matrix to allocate
Returns
float **
Definition at line 52 of file matrix.c.
Referenced by Adjugate(), DeleteRowCol(), MatAllocSQ(), MatLoad(), MatMul(), and Transpose().
mat_t MatAllocSQ (int size)
Allocate a matrix.
Parameters
in size size of square matrix to allocate
Returns
float **
Definition at line 91 of file matrix.c.
void MatFree (mat_t matF)
Free a matrix.
Parameters
in **Mat Matrix to free
Definition at line 101 of file matrix.c.
Referenced by MatMul(), Minor(), PseudoInvert(), and user_help().
mat_t MatLoad (void * V, int rows, int cols)
Load a matrix.
Parameters
in *V matrix data
in size size of square matrix
Definition at line 134 of file matrix.c.
Referenced by MatLoadSQ(), MatMul(), and user_help().
mat_t MatLoadSQ (void * V, int size)
Load a square matrix.
Parameters
in *V square matrix data
in size size of square matrix
Definition at line 157 of file matrix.c.
Referenced by MatMul().
mat_t MatMul (mat_t MatA, mat_t MatB)
Multiply two matrix.
See also
https://en.wikipedia.org/wiki/Matrix_multiplication_algorithm C = AB, A is n × m matrix, B is m × p matrix C result n × p matrix (dimensions row size of A, column size of B) Cij = Sum(k=1 .. m) Aik * Bik
Parameters
in MatA matrix A
in MatB matrix B
Returns
MatA * MatB Result dimensions is (row size of A, column size of B)
Definition at line 461 of file matrix.c.
Referenced by MatMul(), PseudoInvert(), and user_help().
void MatPrint (mat_t matrix)
Print a matrix.
Parameters
in Mat Matrix to print
Definition at line 167 of file matrix.c.
Referenced by Invert(), MatMul(), and user_help().
float Minor (mat_t MatA, int row, int col)
Compute determinate of the minor submatrix Minor submatrix has one less row and column as a result.
See also
https://en.wikipedia.org/wiki/Minor_(linear_algebra)
Parameters
in MatA matrix A
in row row to delete
in col col to delete
Returns
Determinate
Definition at line 268 of file matrix.c.
Referenced by Cofactor().
mat_t PseudoInvert (mat_t MatA)
Calculate Pseudo Matrix Inverse Used for least square fitting of non square matrix with excess solutions Pseudo Inverse matrix(A) = 1/(AT × A) × AT.
Parameters
in MatA matrix A input - does not have to be square
Returns
Pseudo Inverse of MatA or error
Definition at line 428 of file matrix.c.
Referenced by MatMul(), and user_help().
int TestSquare (mat_t MatA)
Credits: https://www.cs.rochester.edu/~brown/Crypto/assts/projects/adj.html.
Author
Paul Bourke 2002 Test is a matrix is square
Parameters
in MatA matrix A
Returns
1 if ssquare, 0 if not
Definition at line 42 of file matrix.c.
mat_t Transpose (mat_t MatA)
Transpose matrix.
Parameters
in MatA matrix A
Returns
Transpose matrix
Definition at line 241 of file matrix.c.
Referenced by PseudoInvert().