fatfs/mmc_hal.h File Reference
MMC Hardware Layer for FatFs.
#include `user_config.h`
*
Macros
#define mmc_cli() cli() /*< interrupt disable */
#define mmc_sei() sei() /*< interrupt enable */
#define mmc_disk_initialize disk_initialize	/*< disk_initialize() */
#define mmc_disk_status disk_status			/*< disk_status() */
#define mmc_disk_read disk_read /*< disk_read() */
#define mmc_disk_write disk_write			/*< disk_read() */
#define mmc_disk_ioctl disk_ioctl /*< disk_ioctl */
Functions
MEMSPACE void mmc_install_timer (void)
Install MMC timer task: mmc_task()
MEMSPACE void mmc_spi_TX_buffer (const uint8_t *data, int count)
SPI write buffer.
MEMSPACE void mmc_spi_RX_buffer (const uint8_t *data, int count)
SPI read buffer.
MEMSPACE uint8_t mmc_spi_RX (void)
SPI read 1 byte.
MEMSPACE void mmc_spi_TX (uint8_t data)
SPI write 1 byte.
MEMSPACE uint8_t mmc_spi_TXRX (uint8_t data)
SPI read and write 1 byte.
MEMSPACE void mmc_set_ms_timeout (uint16_t ms)
Set MMC timeout timer in Milliseconds.
MEMSPACE int mmc_test_timeout (void)
Wait for timeout.
MEMSPACE int mmc_init (int verbose)
Initialize MMC and FatFs interface, display diagnostics.
MEMSPACE void mmc_spi_init (int32_t clock)
MMC SPI bus init.
MEMSPACE void mmc_slow (void)
MMC set slow SPI bus speed.
MEMSPACE void mmc_fast (void)
MMC fast SPI bus speed.
MEMSPACE void mmc_power_on (void)
MMC power ON initialize.
MEMSPACE void mmc_power_off (void)
MMC power off.
MEMSPACE int mmc_power_status (void)
MMC power status.
MEMSPACE void mmc_cs_enable (void)
MMC CS enable.
MEMSPACE void mmc_cs_disable (void)
MMC CS disable.
MEMSPACE int mmc_ins_status (void)
MMC Card Inserted status.
MEMSPACE int mmc_wp_status (void)
MMC Card Write Protect status.
Detailed Description
MMC Hardware Layer for FatFs.
Edit History
[1.0] [Mike Gore] Initial revision of file.
Copyright 2014 Mike Gore, Inc. All rights reserved.
Definition in file mmc_hal.h.
Macro Definition Documentation
#define mmc_cli() cli() /*< interrupt disable */
Definition at line 35 of file mmc_hal.h.
Referenced by mmc_set_ms_timeout().
#define mmc_disk_initialize disk_initialize	/*< disk_initialize() */
Definition at line 39 of file mmc_hal.h.
#define mmc_disk_ioctl disk_ioctl /*< disk_ioctl */
Definition at line 43 of file mmc_hal.h.
Referenced by mmc_init().
#define mmc_disk_read disk_read /*< disk_read() */
Definition at line 41 of file mmc_hal.h.
#define mmc_disk_status disk_status			/*< disk_status() */
Definition at line 40 of file mmc_hal.h.
#define mmc_disk_write disk_write			/*< disk_read() */
Definition at line 42 of file mmc_hal.h.
#define mmc_sei() sei() /*< interrupt enable */
Definition at line 36 of file mmc_hal.h.
Referenced by mmc_set_ms_timeout().
Function Documentation
MEMSPACE void mmc_cs_disable (void)
MMC CS disable.
MMC SPI chip select
Returns
void
Definition at line 390 of file mmc_hal.c.
Referenced by mmc_deselect().
MEMSPACE void mmc_cs_enable (void)
MMC CS enable.
MMC SPI chip select
Returns
void
Definition at line 372 of file mmc_hal.c.
Referenced by mmc_select().
MEMSPACE void mmc_fast (void)
MMC fast SPI bus speed.
Used during normal file IO phases
Returns
void
Definition at line 309 of file mmc_hal.c.
Referenced by mmc_disk_initialize().
MEMSPACE int mmc_init (int verbose)
Initialize MMC and FatFs interface, display diagnostics.
Parameters
in verbose display initialisation messages
Returns
Definition at line 195 of file mmc_hal.c.
Referenced by fatfs_tests(), open(), and setup().
MEMSPACE int mmc_ins_status (void)
MMC Card Inserted status.
We do not detect card insert status in this project.
Returns
1 card inserted
Definition at line 406 of file mmc_hal.c.
Referenced by mmc_task().
MEMSPACE void mmc_install_timer (void)
Install MMC timer task: mmc_task()
See Also
mmc_task()
Returns
void
Definition at line 74 of file mmc_hal.c.
Referenced by mmc_init().
MEMSPACE void mmc_power_off (void)
MMC power off.
We do not control power to the MMC device in this project.
Returns
void
Definition at line 343 of file mmc_hal.c.
Referenced by mmc_disk_initialize(), and mmc_disk_ioctl().
MEMSPACE void mmc_power_on (void)
MMC power ON initialize.
We do not control power to the MMC device in this project.
Returns
void
Definition at line 320 of file mmc_hal.c.
Referenced by mmc_disk_initialize().
MEMSPACE int mmc_power_status (void)
MMC power status.
We do not control power to the MMC device in this project.
Returns
1 power is alwasy on
Definition at line 360 of file mmc_hal.c.
MEMSPACE void mmc_set_ms_timeout (uint16_t ms)
Set MMC timeout timer in Milliseconds.
Parameters
in ms timeout in Milliseconds
See Also
mmc_test_timeout ()
Returns
void
Definition at line 159 of file mmc_hal.c.
Referenced by mmc_disk_initialize(), rcvr_datablock(), and wait_ready().
MEMSPACE void mmc_slow (void)
MMC set slow SPI bus speed.
Used during card detect phase
Returns
void
Definition at line 297 of file mmc_hal.c.
Referenced by mmc_disk_initialize(), mmc_init(), and mmc_power_on().
MEMSPACE void mmc_spi_init (int32_t clock)
MMC SPI bus init.
Returns
void
Definition at line 275 of file mmc_hal.c.
Referenced by mmc_cs_enable(), mmc_fast(), and mmc_slow().
MEMSPACE uint8_t mmc_spi_RX (void)
SPI read 1 byte.
Returns
uint8_t value
Definition at line 112 of file mmc_hal.c.
MEMSPACE void mmc_spi_RX_buffer (const uint8_t * data, int count)
SPI read buffer.
Parameters
in *data transmit buffer
in count number of bytes to write
Returns
void
Definition at line 100 of file mmc_hal.c.
Referenced by rcvr_datablock().
MEMSPACE void mmc_spi_TX (uint8_t data)
SPI write 1 byte.
Parameters
in data value to transmit
Returns
void
Definition at line 127 of file mmc_hal.c.
Referenced by mmc_deselect(), mmc_disk_initialize(), mmc_disk_ioctl(), mmc_power_off(), mmc_select(), mmc_spi_init(), rcvr_datablock(), send_cmd(), and xmit_datablock().
MEMSPACE void mmc_spi_TX_buffer (const uint8_t * data, int count)
SPI write buffer.
Parameters
in *data transmit buffer
in count number of bytes to write
Returns
void
Definition at line 86 of file mmc_hal.c.
Referenced by xmit_datablock().
MEMSPACE uint8_t mmc_spi_TXRX (uint8_t data)
SPI read and write 1 byte.
Parameters
in data value to transmit
Returns
uint8_t value read
Definition at line 141 of file mmc_hal.c.
Referenced by mmc_disk_initialize(), mmc_disk_ioctl(), rcvr_datablock(), send_cmd(), wait_ready(), and xmit_datablock().
MEMSPACE int mmc_test_timeout (void)
Wait for timeout.
Returns
1 ready
0 timeout
Definition at line 170 of file mmc_hal.c.
Referenced by mmc_disk_initialize(), rcvr_datablock(), and wait_ready().
MEMSPACE int mmc_wp_status (void)
MMC Card Write Protect status.
We do not detect card write protect status in this project.
Returns
0 == not write protected
Definition at line 419 of file mmc_hal.c.
Referenced by mmc_task().