network/network.h File Reference
#include <ip_addr.h>
*
#include <c_types.h>
*
#include <espconn.h>
*
Functions
MEMSPACE void poll_network_message (window *win)
void ntp_setup (void)
MEMSPACE void my_receive (void *arg, char *pdata, unsigned short len)
MEMSPACE void wifi_event_cb (System_Event_t *event_p)
WIFI Event Callback.
MEMSPACE void setup_networking (void)
Code fragments if(!wifi_station_dhcpc_stop()) DEBUG_PRINTF(`ERROR wifi_station_dhcpc_stop() \n `);.
Variables
int network_init
Function Documentation
MEMSPACE void my_receive (void * arg, char * pdata, unsigned short len)
void ntp_setup (void)
Definition at line 88 of file user_main.c.
Referenced by loop().
MEMSPACE void poll_network_message (window * win)
MEMSPACE void setup_networking (void)
Code fragments if(!wifi_station_dhcpc_stop()) DEBUG_PRINTF(`ERROR wifi_station_dhcpc_stop() \n `);.
if(!wifi_set_ip_info(STATION_IF , &info)) DEBUG_PRINTF(`ERROR wifi_set_ip_info()\n`);
if(!wifi_station_connect()) DEBUG_PRINTF(`ERROR wifi_station_connect()\n`);
if(!wifi_station_set_auto_connect(TRUE)) DEBUG_PRINTF(`ERROR wifi_station_set_auto_connect(1)\n`); IP4_ADDR(& info.ip , 192 , 168 , 200 , 123); IP4_ADDR(& info.netmask , 255 , 255 , 255 , 0); IP4_ADDR(& info.gw, 192 , 168 , 200 , 1); if(!wifi_set_ip_info(STATION_IF , &info)) DEBUG_PRINTF(`ERROR wifi_set_ip_info() \n `); if(!wifi_station_set_auto_connect(TRUE)) DEBUG_PRINTF(`ERROR wifi_station_set_auto_connect(1) \n `); Setup Wifi Network Credits: ideas borrowed from David Ogilvy(MetalPhreak)
Returns
void
Definition at line 141 of file network.c.
Referenced by setup().
MEMSPACE void wifi_event_cb (System_Event_t * event_p)
WIFI Event Callback.
Parameters
in *event_p Wifi event structure This callback status code borrowed from David Ogilvy(MetalPhreak)
Returns
void
Definition at line 58 of file network.c.
Referenced by setup_networking().
Variable Documentation
int network_init
Definition at line 42 of file network.c.
Referenced by ntp_setup(), and wifi_event_cb().