printf/pr.c File Reference
Small printf with floating point support.
#include `user_config.h`
*
#include `printf.h`
*
Functions
MEMSPACE window * tft_setpos (int16_t x, int16_t y)
Set current window offset (per current rotation)
MEMSPACE window * tft_setsize (uint16_t size)
MEMSPACE void tft_putch (int c, window *win)
put character in current winoow
MEMSPACE int tft_printf (int x, int y, int size, const char *fmt,...)
tft_printf function
Detailed Description
Small printf with floating point support.
Copyright 2015 Mike Gore, GPL License
See Also
: http://en.wikipedia.org/wiki/Glyph_Bitmap_Distribution_Format
Edit History
[1.0] [Mike Gore] Initial revision of file.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
printf is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file pr.c.
Function Documentation
MEMSPACE int tft_printf (int x, int y, int size, const char * fmt, ...)
tft_printf function
Parameters
in x X offset
in y Y offset
in size font index (index into font array)
in fmt printf forat string
in ... vararg list or arguments
Returns
size of string
Definition at line 42 of file pr.c.
Referenced by test(), tft_drawNumber(), and user_init().
MEMSPACE void tft_putch (int c, window * win)
put character in current winoow
Parameters
in c character
in *win window pointer return: void
Definition at line 873 of file ili9341.c.
Referenced by tft_cleareol(), tft_printf(), and tft_putch().
MEMSPACE window* tft_setpos (int16_t x, int16_t y)
Set current window offset (per current rotation)
Parameters
in x x offset
in y y oofset return: pointer to current windows
Definition at line 410 of file ili9341.c.
Referenced by tft_printf().
MEMSPACE window* tft_setsize (uint16_t size)