printf/printf.h File Reference
Small printf, and verious conversion code with floating point support.
#include <stdint.h>
*
#include <stdarg.h>
*
#include <string.h>
*
#include <math.h>
*
Data Structures
struct _printf_t
Macros
#define MEMSPACE
Typedefs
typedef struct _printf_t printf_t
Functions
MEMSPACE void p_reverse (char *str)
MEMSPACE void p_strupper (char *str)
MEMSPACE double iexp (double num, int exp)
MEMSPACE double scale10 (double num, int *exp)
MEMSPACE int p_itoa (long num, char *str, int max, int prec, int sign)
Convert number to ASCII returns size of string after conversion Note: It is allowed to have more digits converted then prec defines Like itoa but can support leading '+/-/ ' or unsigned and zero padding.
MEMSPACE int p_ntoa (unsigned long num, char *str, int max, int radix, int prec)
Convert number to ASCII Like itoa but can support leading '+/-/ ' or unsigned and zero padding Note: It is allowed to have more digits converted then prec defines.
MEMSPACE int p_ftoa (double val, char *str, int intprec, int prec, int sign)
MEMSPACE int p_etoa (double x, char *str, int prec, int sign)
MEMSPACE void _puts_pad (printf_t *fn, char *s, int width, int count, int left)
MEMSPACE void _printf_fn (printf_t *fn, const char *fmt, va_list va)
vsnprintf function
void _putc_buffer_fn (struct _printf_t *p, char ch)
_putc_buffer_fn low level function writes a character to a buffer
MEMSPACE int vsnprintf (char *str, size_t size, const char *format, va_list va)
vsnprintf function
MEMSPACE int snprintf (char *str, size_t size, const char *format,...)
snprintf function
Detailed Description
Small printf, and verious conversion code with floating point support.
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Macro Definition Documentation
#define MEMSPACE
Definition at line 32 of file printf.h.
Typedef Documentation
typedef struct _printf_t printf_t
Function Documentation
MEMSPACE void _printf_fn (printf_t * fn, const char * fmt, va_list va)
vsnprintf function
Parameters
out fn output character function pointer
in fmt printf forat string
in va va_list arguments
Returns
size of string
Definition at line 607 of file printf.c.
Referenced by tft_printf(), uart0_printf(), vsnprintf(), and vsock_printf().
void _putc_buffer_fn (struct _printf_t * p, char ch)
_putc_buffer_fn low level function writes a character to a buffer
Parameters
in *p structure with pointers and buffer to be written to
in ch character to place in buffer
Returns
void
Definition at line 872 of file printf.c.
Referenced by vsnprintf().
MEMSPACE void _puts_pad (printf_t * fn, char * s, int width, int count, int left)
Definition at line 554 of file printf.c.
Referenced by _printf_fn().
MEMSPACE double iexp (double num, int exp)
Referenced by atol(), p_ntoa(), and strupper().
MEMSPACE int p_etoa (double x, char * str, int prec, int sign)
Referenced by _printf_fn(), and p_ntoa().
MEMSPACE int p_ftoa (double val, char * str, int intprec, int prec, int sign)
Referenced by _printf_fn(), and p_ntoa().
MEMSPACE int p_itoa (long num, char * str, int max, int prec, int sign)
Convert number to ASCII returns size of string after conversion Note: It is allowed to have more digits converted then prec defines Like itoa but can support leading '+/-/ ' or unsigned and zero padding.
Parameters
in num number
out *str string
in max maximum length or string
in prec minumum number of digits, 0 padded if needed (can be zero)
in sign 2: - or +, 1: -, 0: unsigned NOT counted as part of prec length (just like printf)
Returns
long value
Definition at line 222 of file printf.c.
Referenced by _printf_fn().
MEMSPACE int p_ntoa (unsigned long num, char * str, int max, int radix, int prec)
Convert number to ASCII Like itoa but can support leading '+/-/ ' or unsigned and zero padding Note: It is allowed to have more digits converted then prec defines.
Parameters
in num unsigned number
out *str string
in max maximum length or string
in radix Radix may only be 2,8,16
in prec minumum number of digits, zero padded if needed NOT counted as part of prec length (just like printf)
Returns
returns size of string
Definition at line 299 of file printf.c.
Referenced by _printf_fn().
MEMSPACE void p_reverse (char * str)
MEMSPACE void p_strupper (char * str)
MEMSPACE double scale10 (double num, int * exp)
Referenced by p_ntoa(), and strupper().
MEMSPACE int snprintf (char * str, size_t size, const char * format, ...)
snprintf function
Parameters
out str string buffer for result
in size maximum length of converted string
in format printf forat string
in ... list of arguments
Returns
string size
Definition at line 926 of file printf.c.
Referenced by AddFontName(), asctime_r(), html_msg(), ipv4_2str(), ts_to_str(), u5toa(), and wifi_event_cb().
MEMSPACE int vsnprintf (char * str, size_t size, const char * format, va_list va)
vsnprintf function
Parameters
out str string buffer for result
in size maximum length of converted string
in format printf forat string
in va va_list list of arguments
Returns
string size
Definition at line 898 of file printf.c.
Referenced by html_msg(), and snprintf().