esp8266/rtc.c File Reference
#include `user_config.h`
*
#include `time.h`
*
#include `rtc.h`
*
#include <stdlib.h>
*
#include <string.h>
*
Functions
MEMSPACE uint8_t BINtoBCD (uint8_t data)
Convert number >= 0 and <= 99 to BCD.
MEMSPACE uint8_t BCDtoBIN (uint8_t data)
Convert two `digit` BCD number to binary.
MEMSPACE int8_t rtc_run_test ()
Check if the DS1307 device is running.
MEMSPACE int rtc_run (int run)
Set DS1307 run state.
MEMSPACE uint8_t rtc_init (int force, time_t seconds)
Initialize DS1307 rtc if not initialied - or if forced.
MEMSPACE uint8_t rtc_write (tm_t *t)
Set DS1307 RTC from POSIX struct tm * structure.
MEMSPACE uint8_t rtc_read (tm_t *t)
Read DS1307 RTC into POSIX struct tm * structure.
Variables
int rtc_ok = 0
Function Documentation
MEMSPACE uint8_t BCDtoBIN (uint8_t data)
Convert two `digit` BCD number to binary.
Parameters
in data BCD number.
number >= 0 and <= 99 to BCD
Returns
Binary value.
Definition at line 48 of file rtc.c.
Referenced by rtc_read().
MEMSPACE uint8_t BINtoBCD (uint8_t data)
Convert number >= 0 and <= 99 to BCD.
BCD format has each hex nibble has a digit 0 .. 9
Parameters
in data number to convert.
Returns
BCD value
Warning
we assume the number is in range.
Definition at line 36 of file rtc.c.
Referenced by rtc_write().
MEMSPACE uint8_t rtc_init (int force, time_t seconds)
Initialize DS1307 rtc if not initialied - or if forced.
Parameters
in force force initialiation flag.
If 1 then alwasy force initialiation.
in seconds POSIX EPOCH time in seconds.
Returns
1 on success.
0 on fail.
Definition at line 121 of file rtc.c.
Referenced by setdate_r().
MEMSPACE uint8_t rtc_read (tm_t * t)
Read DS1307 RTC into POSIX struct tm * structure.
Parameters
out t struct tm * POSIX time returned.
Returns
1 on sucess.
0 on fail.
Definition at line 238 of file rtc.c.
Referenced by rtc_read().
MEMSPACE int rtc_run (int run)
Set DS1307 run state.
Parameters
in run state.
1 = run.
0 = stop.
-1 = check run state.
Returns
run state 0/1 on success.
-1 on error.
Definition at line 87 of file rtc.c.
Referenced by rtc_init().
MEMSPACE int8_t rtc_run_test (void)
Check if the DS1307 device is running.
display error if read error occurs.
Returns
1 if running.
0 if not running.
-1 on error.
Definition at line 63 of file rtc.c.
MEMSPACE uint8_t rtc_write (tm_t * t)
Set DS1307 RTC from POSIX struct tm * structure.
Parameters
in t POSIX struct tm * time to set.
Returns
1 on sucess.
0 on fail.
Definition at line 189 of file rtc.c.
Referenced by rtc_init().
Variable Documentation
int rtc_ok = 0
Definition at line 25 of file rtc.c.
Referenced by rtc_init().