send.c File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <string.h>
*
#include <unistd.h>
*
#include <fcntl.h>
*
#include <sys/types.h>
*
#include <sys/socket.h>
*
#include <netinet/in.h>
*
#include <arpa/inet.h>
*
#include <netdb.h>
*
#include <errno.h>
*
#include <netinet/if_ether.h>
*
#include <net/if.h>
*
#include <linux/sockios.h>
*
Typedefs
typedef unsigned char uint8_t
typedef unsigned short uint16_t
typedef unsigned int uint32_t
Functions
int escape (char *message, int size)
void send_message (char *message, char *ip, int port, int echoback)
int main (int argc, char *argv[])
Typedef Documentation
typedef unsigned short uint16_t
Definition at line 18 of file send.c.
typedef unsigned int uint32_t
Definition at line 19 of file send.c.
typedef unsigned char uint8_t
Definition at line 17 of file send.c.
Function Documentation
int escape (char * message, int size)
Definition at line 26 of file send.c.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 148 of file send.c.
Referenced by PerspectiveProjection().
void send_message (char * message, char * ip, int port, int echoback)
Definition at line 87 of file send.c.
Referenced by main().