server/server.h File Reference
#include <stdint.h>
*
#include <stdarg.h>
*
#include <string.h>
*
#include <math.h>
*
Macros
#define MEMSPACE
#define WEAK_ATR __attribute__((weak))
Functions
MEMSPACE void servertest_message (window *win)
Network receive task.
MEMSPACE void servertest_receive (void *arg, char *pdata, unsigned short len)
Network receive task.
MEMSPACE void servertest_setup (int port)
Setup Server Task.
Macro Definition Documentation
#define MEMSPACE
Definition at line 40 of file server.h.
#define WEAK_ATR __attribute__((weak))
Definition at line 45 of file server.h.
Function Documentation
MEMSPACE void servertest_message (window * win)
Network receive task.
Parameters
in *win window pointer
Returns
void
Definition at line 53 of file server.c.
Referenced by loop().
MEMSPACE void servertest_receive (void * arg, char * pdata, unsigned short len)
Network receive task.
Parameters
in *arg network callback arg
in *pdata data buffer
in len buffer length
Returns
void
Definition at line 78 of file server.c.
Referenced by servertest_setup().
MEMSPACE void servertest_setup (int port)
Setup Server Task.
Parameters
in port TCP port for service Credits: ideas borrowed from David Ogilvy(MetalPhreak)
Returns
void
Definition at line 97 of file server.c.
Referenced by setup().