lib/std.h File Reference
Part of Small printf, and verious conversion code with floating point support.
#include <stdint.h>
*
#include <stdarg.h>
*
#include <string.h>
*
#include <math.h>
*
Macros
#define MEMSPACE
#define WEAK_ATR __attribute__((weak))
Functions
MEMSPACE int WEAK_ATR atodigit (int c, int radix)
Convert ASCII character to radix based digit , or -1.
MEMSPACE long WEAK_ATR aton (char *str, int base)
Convert ASCII string to number in a given base.
MEMSPACE long WEAK_ATR strtol (const char *nptr, char **endptr, int base)
Convert ASCII string to number in a given base.
MEMSPACE int WEAK_ATR atoi (const char *str)
Convert ASCII string to number in base 10.
MEMSPACE long WEAK_ATR atol (const char *str)
Convert ASCII string to number in base 10.
MEMSPACE double WEAK_ATR iexp (double num, int exp)
MEMSPACE double WEAK_ATR scale10 (double num, int *exp)
MEMSPACE double atof (const char *str)
Detailed Description
Part of Small printf, and verious conversion code with floating point support.
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Macro Definition Documentation
#define MEMSPACE
Definition at line 39 of file std.h.
#define WEAK_ATR __attribute__((weak))
Definition at line 44 of file std.h.
Function Documentation
MEMSPACE int WEAK_ATR atodigit (int c, int radix)
Convert ASCII character to radix based digit , or -1.
Parameters
in c character
in radix radix
Returns
radix based digit , or -1
See also
strtol
Definition at line 39 of file std.c.
Referenced by strtol().
MEMSPACE double atof (const char * str)
Referenced by atol(), and user_tests().
MEMSPACE int WEAK_ATR atoi (const char * str)
Convert ASCII string to number in base 10.
Parameters
in str string
Returns
int value
See also
strtol
Definition at line 124 of file std.c.
MEMSPACE long WEAK_ATR atol (const char * str)
Convert ASCII string to number in base 10.
Parameters
in str string
Returns
long value
See also
strtol
Definition at line 139 of file std.c.
MEMSPACE long WEAK_ATR aton (char * str, int base)
Convert ASCII string to number in a given base.
Parameters
in str string
in base radix
Returns
long value
See also
strtol
Definition at line 60 of file std.c.
MEMSPACE double WEAK_ATR iexp (double num, int exp)
MEMSPACE double WEAK_ATR scale10 (double num, int * exp)
MEMSPACE long WEAK_ATR strtol (const char * nptr, char ** endptr, int base)
Convert ASCII string to number in a given base.
Parameters
in nptr string
in endptr pointer to string pointer return value
in base radix
Returns
long value
Definition at line 77 of file std.c.
Referenced by atoh(), atoi(), atol(), aton(), main(), and setdate_r().