lib/std.c File Reference
#include <stdint.h>
*
#include <stdarg.h>
*
#include <string.h>
*
#include <math.h>
*
#include `std.h`
*
Functions
MEMSPACE int WEAK_ATR atodigit (int c, int radix)
Convert ASCII character to radix based digit , or -1.
MEMSPACE long WEAK_ATR aton (char *str, int base)
Convert ASCII string to number in a given base.
MEMSPACE long WEAK_ATR strtol (const char *nptr, char **endptr, int base)
Convert ASCII string to number in a given base.
MEMSPACE int WEAK_ATR atoi (const char *str)
Convert ASCII string to number in base 10.
MEMSPACE long WEAK_ATR atol (const char *str)
Convert ASCII string to number in base 10.
Function Documentation
MEMSPACE int WEAK_ATR atodigit (int c, int radix)
Convert ASCII character to radix based digit , or -1.
Parameters
in c character
in radix radix
Returns
radix based digit , or -1
See also
strtol
Definition at line 39 of file std.c.
Referenced by strtol().
MEMSPACE int WEAK_ATR atoi (const char * str)
Convert ASCII string to number in base 10.
Parameters
in str string
Returns
int value
See also
strtol
Definition at line 124 of file std.c.
Referenced by html_status(), main(), parse_http_request(), and ReadBdf().
MEMSPACE long WEAK_ATR atol (const char * str)
Convert ASCII string to number in base 10.
Parameters
in str string
Returns
long value
See also
strtol
Definition at line 139 of file std.c.
MEMSPACE long WEAK_ATR aton (char * str, int base)
Convert ASCII string to number in a given base.
Parameters
in str string
in base radix
Returns
long value
See also
strtol
Definition at line 60 of file std.c.
MEMSPACE long WEAK_ATR strtol (const char * nptr, char ** endptr, int base)
Convert ASCII string to number in a given base.
Parameters
in nptr string
in endptr pointer to string pointer return value
in base radix
Returns
long value
Definition at line 77 of file std.c.
Referenced by atoh(), atoi(), atol(), aton(), main(), and setdate_r().