lib/stdlib.h File Reference
Part of Small printf, and verious conversion code with floating point support.
#include <stdint.h>
*
#include <math.h>
*
#include `str.h`
*
Macros
#define MEMSPACE
Functions
MEMSPACE double iexp (double num, int exp)
MEMSPACE double scale10 (double num, int *exp)
MEMSPACE int atodigit (int c, int radix)
Convert ASCII character to radix based digit , or -1.
MEMSPACE long aton (char *str, int base)
Convert ASCII string to number in a given base.
MEMSPACE long strtol (const char *nptr, char **endptr, int base)
Convert ASCII string to number in a given base.
MEMSPACE int atoi (const char *str)
Convert ASCII string to number in base 10.
MEMSPACE long atol (const char *str)
Convert ASCII string to number in base 10.
MEMSPACE double atof (const char *str)
Detailed Description
Part of Small printf, and verious conversion code with floating point support.
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Macro Definition Documentation
#define MEMSPACE
Definition at line 33 of file stdlib.h.
Function Documentation
MEMSPACE int atodigit (int c, int radix)
Convert ASCII character to radix based digit , or -1.
Parameters
in c character
in radix radix
Returns
radix based digit , or -1
See also
strtol
Definition at line 108 of file stdlib.c.
Referenced by strtol().
MEMSPACE double atof (const char * str)
Referenced by atol(), and user_tests().
MEMSPACE int atoi (const char * str)
Convert ASCII string to number in base 10.
Parameters
in str string
Returns
int value
See also
strtol
Definition at line 190 of file stdlib.c.
MEMSPACE long atol (const char * str)
Convert ASCII string to number in base 10.
Parameters
in str string
Returns
long value
See also
strtol
Definition at line 203 of file stdlib.c.
MEMSPACE long aton (char * str, int base)
Convert ASCII string to number in a given base.
Parameters
in str string
in base radix
Returns
long value
See also
strtol
Definition at line 127 of file stdlib.c.
MEMSPACE double iexp (double num, int exp)
MEMSPACE double scale10 (double num, int * exp)
MEMSPACE long strtol (const char * nptr, char ** endptr, int base)
Convert ASCII string to number in a given base.
Parameters
in nptr string
in endptr pointer to string pointer return value
in base radix
Returns
long value
Definition at line 145 of file stdlib.c.
Referenced by atoh(), atoi(), atol(), aton(), main(), and setdate_r().