lib/str.c File Reference
String matching functions.
#include <stdint.h>
*
#include <stdarg.h>
*
#include <string.h>
*
#include <math.h>
*
#include `sys.h`
*
#include `str.h`
*
Functions
char * strcpy (char *dest, const char *src)
char * strncpy (char *dest, const char *src, size_t n)
MEMSPACE uint8_t hexd (char c)
Convert Character into HEX digit.
MEMSPACE long atoh (const char *p)
Convert ASCII hex string to long integer.
MEMSPACE int WEAK_ATR isdigit (int c)
test if a character is a digit
MEMSPACE int WEAK_ATR isupper (int c)
Is a character upper case.
MEMSPACE int WEAK_ATR islower (int c)
Is a character lower case.
MEMSPACE int WEAK_ATR tolower (int c)
Convert character to lower case, only if it is upper case.
MEMSPACE int WEAK_ATR toupper (int c)
Convert character to upper case, only if it is lower case.
MEMSPACE size_t WEAK_ATR strlen (const char *str)
String Length.
MEMSPACE int WEAK_ATR strcmp (const char *str, const char *pat)
Compare two strings.
MEMSPACE int WEAK_ATR strncmp (const char *str, const char *pat, size_t len)
Compare two strings maximum len bytes in size.
MEMSPACE int WEAK_ATR strcasecmp (const char *str, const char *pat)
Compare two strings without case.
MEMSPACE int WEAK_ATR strncasecmp (const char *str, const char *pat, size_t len)
Compare two strings without case maximum len bytes in size.
MEMSPACE void WEAK_ATR reverse (char *str)
Reverse a string in place Example: abcdef -> fedcba.
MEMSPACE void WEAK_ATR strupper (char *str)
UPPERCASE a string.
MEMSPACE char * strnalloc (char *str, int len)
Allocate space for string with maximum size.
MEMSPACE char * stralloc (char *str)
Allocate space for string.
MEMSPACE int MATCH (char *str, char *pat)
Compare two strings.
MEMSPACE int MATCHI (char *str, char *pat)
Compare two strings without case.
MEMSPACE int MATCH_LEN (char *str, char *pat)
Compare two strings limted to length of pattern.
MEMSPACE int MATCHI_LEN (char *str, char *pat)
Compare two strings without case limted to length of pattern.
MEMSPACE char * skipspaces (char *ptr)
Skip white space in a string - tabs and spaces.
MEMSPACE char * nextspace (char *ptr)
Skip to first white space in a string - tabs and spaces.
MEMSPACE char * skipchars (char *str, char *pat)
Skip characters defined in user string.
MEMSPACE void trim_tail (char *str)
Trim White space and control characters from end of string.
MEMSPACE char * get_token (char *str, char *token, int max)
return next token
MEMSPACE int token (char *str, char *pat)
Search for token in a string matching user pattern.
Detailed Description
String matching functions.
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
MEMSPACE long atoh (const char * p)
Convert ASCII hex string to long integer.
Parameters
in p String to convert.
Returns
long integer result.
See also
strtol() for return overflow and underflow results.
Definition at line 60 of file str.c.
MEMSPACE char* get_token (char * str, char * token, int max)
return next token
Skips all non printable ASCII characters before token
Token returns only printable ASCII
Parameters
in str string to search.
out token token to return
in max maximum token size
Returns
pointer past token on success .
NULL if no token found
Definition at line 531 of file str.c.
Referenced by user_tests().
MEMSPACE uint8_t hexd (char c)
Convert Character into HEX digit.
Parameters
in c character.
Returns
HEX digit [0..F] on success.
0xff on fail.
Definition at line 42 of file str.c.
Referenced by process_args().
MEMSPACE int WEAK_ATR isdigit (int c)
test if a character is a digit
Parameters
in c character
Returns
true or false
Definition at line 73 of file str.c.
MEMSPACE int WEAK_ATR islower (int c)
Is a character lower case.
Parameters
in c character.
Returns
1 of lower case, else 0
Definition at line 105 of file str.c.
Referenced by toupper().
MEMSPACE int WEAK_ATR isupper (int c)
Is a character upper case.
Parameters
in c character.
Returns
1 of upper case, else 0
Definition at line 89 of file str.c.
Referenced by tolower().
MEMSPACE int MATCH (char * str, char * pat)
Compare two strings.
Parameters
in str string to match.
in pat pattern to compare.
Returns
string lenth on match.
0 on no match.
Definition at line 354 of file str.c.
MEMSPACE int MATCH_LEN (char * str, char * pat)
Compare two strings limted to length of pattern.
Parameters
in str string to match.
in pat pattern to compare.
Returns
string lenth on match.
0 on no match.
Warning
Matches sub strings so be caeful.
Definition at line 390 of file str.c.
MEMSPACE int MATCHI (char * str, char * pat)
Compare two strings without case.
Parameters
in str string to match.
in pat pattern to compare.
Returns
string lenth on match.
0 on no match.
Definition at line 372 of file str.c.
MEMSPACE int MATCHI_LEN (char * str, char * pat)
Compare two strings without case limted to length of pattern.
Parameters
in str string to match.
in pat pattern to compare.
Returns
string lenth on match.
0 on no match.
Warning
Matches sub strings so be caeful.
Definition at line 416 of file str.c.
Referenced by match_headers().
MEMSPACE char* nextspace (char * ptr)
Skip to first white space in a string - tabs and spaces.
Parameters
in ptr input string
Returns
pointer to first white space character
Definition at line 456 of file str.c.
Referenced by fatfs_tests(), and process_args().
MEMSPACE void WEAK_ATR reverse (char * str)
Reverse a string in place Example: abcdef -> fedcba.
Parameters
in str string
Returns
string length
Definition at line 264 of file str.c.
MEMSPACE char* skipchars (char * str, char * pat)
Skip characters defined in user string.
Parameters
in str string
in pat pattern string
Returns
pointer to string after skipped characters.
Definition at line 478 of file str.c.
MEMSPACE char* skipspaces (char * ptr)
Skip white space in a string - tabs and spaces.
Parameters
in ptr input string
Returns
pointer to first non white space character
Definition at line 439 of file str.c.
Referenced by fatfs_tests(), get_token(), match_headers(), parse_http_request(), and user_tests().
MEMSPACE char* stralloc (char * str)
Allocate space for string.
Copies tring into allocated space.
Parameters
in str user string.
Returns
pointer to alocated string.
NULL on out of memory.
Definition at line 330 of file str.c.
Referenced by main().
MEMSPACE int WEAK_ATR strcasecmp (const char * str, const char * pat)
Compare two strings without case.
Parameters
in str string to match.
in pat pattern to compare.
Returns
0 on match, < 0 implies str sorts before pat, > 0 implies str sorts after pat
Definition at line 218 of file str.c.
Referenced by file_type(), http_value(), and MATCHI().
MEMSPACE int WEAK_ATR strcmp (const char * str, const char * pat)
Compare two strings.
Parameters
in str string to match.
in pat pattern to compare.
Returns
0 on match, < 0 implies str sorts before pat, > 0 implies str sorts after pat
Definition at line 170 of file str.c.
Referenced by FindFontName(), main(), MATCH(), and user_tests().
char* strcpy (char * dest, const char * src)
Referenced by escape(), fatfs_scan_files(), main(), setup_networking(), and stralloc().
MEMSPACE size_t WEAK_ATR strlen (const char * str)
String Length.
Parameters
in str string
Returns
string length
Definition at line 152 of file str.c.
Referenced by MATCH(), MATCH_LEN(), MATCHI(), MATCHI_LEN(), reverse(), stralloc(), token(), and trim_tail().
MEMSPACE char* strnalloc (char * str, int len)
Allocate space for string with maximum size.
Copies tring into allocated space limited to maximum size.
Parameters
in str user string.
in len maximum string length.
Returns
pointer to alocated string.
Definition at line 306 of file str.c.
MEMSPACE int WEAK_ATR strncasecmp (const char * str, const char * pat, size_t len)
Compare two strings without case maximum len bytes in size.
Parameters
in str string to match.
in pat pattern to compare.
in len maximum string length for compare
Returns
0 on match, < 0 implies str sorts before pat, > 0 implies str sorts after pat
Definition at line 241 of file str.c.
Referenced by MATCHI_LEN().
MEMSPACE int WEAK_ATR strncmp (const char * str, const char * pat, size_t len)
Compare two strings maximum len bytes in size.
Parameters
in str string to match.
in pat pattern to compare.
in len maximum string length for compare
Returns
0 on match, < 0 implies str sorts before pat, > 0 implies str sorts after pat
Definition at line 193 of file str.c.
Referenced by MATCH_LEN(), match_token(), and token().
char* strncpy (char * dest, const char * src, size_t n)
Referenced by loop(), main(), strerror_r(), and strnalloc().
MEMSPACE void WEAK_ATR strupper (char * str)
UPPERCASE a string.
Parameters
in str string
Returns
void
Definition at line 285 of file str.c.
MEMSPACE int token (char * str, char * pat)
Search for token in a string matching user pattern.
Skips all non printable ASCII characters before trying match.
Parameters
in str string to search.
in pat pattern to search for.
Returns
string lenth on match.
0 on no match.
Definition at line 573 of file str.c.
Referenced by fatfs_tests(), rcvr_datablock(), ReadBdf(), and user_tests().
MEMSPACE int WEAK_ATR tolower (int c)
Convert character to lower case, only if it is upper case.
Parameters
in c character.
Returns
character or lowercase value or character
Definition at line 121 of file str.c.
MEMSPACE int WEAK_ATR toupper (int c)
Convert character to upper case, only if it is lower case.
Parameters
in c character.
Returns
character or upper case value or character
Definition at line 137 of file str.c.
Referenced by ReadBdf(), strcasecmp(), and strncasecmp().
MEMSPACE void trim_tail (char * str)
Trim White space and control characters from end of string.
Parameters
in str string
Returns
void
Warning
Overwrites White space and control characters with EOS.
Definition at line 508 of file str.c.
Referenced by match_headers().