lib/str.h File Reference
String matching functions.
#include <stdint.h>
*
#include <math.h>
*
Macros
#define MEMSPACE
#define SWAP(a, b) do { a ^= b; b ^= a; a ^= b; } while(0)
#define ABS(x) ((x)<0 ? -(x) : (x))
#define SIGN(x) (((x) == 0) ? 0 : ((x) > 0) ? 1 : -1)
#define MAX(x, y) (((x) > (y)) ? x : y)
#define SPACES ` \t\r`
#define SPACESNL ` \t\n\r`
Functions
MEMSPACE uint8_t hexd (char c)
Convert Character into HEX digit.
MEMSPACE long atoh (const char *p)
Convert ASCII hex string to long integer.
MEMSPACE int isdigit (int c)
test if a character is a digit
MEMSPACE int isupper (int c)
Is a character upper case.
MEMSPACE int islower (int c)
Is a character lower case.
MEMSPACE int tolower (int c)
Convert character to lower case, only if it is upper case.
MEMSPACE int toupper (int c)
Convert character to upper case, only if it is lower case.
MEMSPACE size_t strlen (const char *str)
String Length.
MEMSPACE int strcmp (const char *str, const char *pat)
Compare two strings.
MEMSPACE int strncmp (const char *str, const char *pat, size_t len)
Compare two strings maximum len bytes in size.
MEMSPACE int strcasecmp (const char *str, const char *pat)
Compare two strings without case.
MEMSPACE int strncasecmp (const char *str, const char *pat, size_t len)
Compare two strings without case maximum len bytes in size.
MEMSPACE int MATCH (char *str, char *pat)
Compare two strings.
MEMSPACE int MATCHI (char *str, char *pat)
Compare two strings without case.
MEMSPACE int MATCH_LEN (char *str, char *pat)
Compare two strings limted to length of pattern.
MEMSPACE int MATCHI_LEN (char *str, char *pat)
Compare two strings without case limted to length of pattern.
MEMSPACE void reverse (char *str)
Reverse a string in place Example: abcdef -> fedcba.
MEMSPACE void strupper (char *str)
UPPERCASE a string.
MEMSPACE char * strnalloc (char *str, int len)
Allocate space for string with maximum size.
MEMSPACE char * stralloc (char *str)
Allocate space for string.
MEMSPACE char * skipspaces (char *ptr)
Skip white space in a string - tabs and spaces.
MEMSPACE char * nextspace (char *ptr)
Skip to first white space in a string - tabs and spaces.
MEMSPACE char * skipchars (char *str, char *pat)
Skip characters defined in user string.
MEMSPACE void trim_tail (char *str)
Trim White space and control characters from end of string.
MEMSPACE char * get_token (char *str, char *token, int max)
return next token
MEMSPACE int token (char *str, char *pat)
Search for token in a string matching user pattern.
Detailed Description
String matching functions.
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
Please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Macro Definition Documentation
#define ABS(x) ((x)<0 ? -(x) : (x))
Definition at line 41 of file str.h.
Referenced by tft_drawFastHLine().
#define MAX(x, y) (((x) > (y)) ? x : y)
Definition at line 43 of file str.h.
Referenced by tft_drawFastHLine().
#define MEMSPACE
Definition at line 33 of file str.h.
#define SIGN(x) (((x) == 0) ? 0 : ((x) > 0) ? 1 : -1)
Definition at line 42 of file str.h.
Referenced by t_sscanf(), and tft_drawFastHLine().
#define SPACES ` \t\r`
Definition at line 45 of file str.h.
#define SPACESNL ` \t\n\r`
Definition at line 46 of file str.h.
#define SWAP(a, b) do { a ^= b; b ^= a; a ^= b; } while(0)
Definition at line 40 of file str.h.
Referenced by tft_fillRectXY(), and tft_fillTriangle().
Function Documentation
MEMSPACE long atoh (const char * p)
Convert ASCII hex string to long integer.
Parameters
in p String to convert.
Returns
long integer result.
See also
strtol() for return overflow and underflow results.
Definition at line 53 of file str.c.
MEMSPACE char* get_token (char * str, char * token, int max)
return next token
Skips all non printable ASCII characters before token
Token returns only printable ASCII
Parameters
in str string to search.
out token token to return
in max maximum token size
Returns
pointer past token on success .
NULL if no token found
return next token
Parameters
in *str string
out *token token characters greter then space less then 0x7f
in max maximum length of token
Returns
: string pointer to character after token
Definition at line 507 of file str.c.
MEMSPACE uint8_t hexd (char c)
Convert Character into HEX digit.
Parameters
in c character.
Returns
HEX digit [0..F] on success.
0xff on fail.
Definition at line 35 of file str.c.
Referenced by process_args().
MEMSPACE int isdigit (int c)
test if a character is a digit
Parameters
in c character
Returns
true or false
Definition at line 78 of file printf.c.
Referenced by _printf_fn(), and atol().
MEMSPACE int islower (int c)
Is a character lower case.
Parameters
in c character.
Returns
1 of lower case, else 0
Definition at line 93 of file str.c.
Referenced by toupper().
MEMSPACE int isupper (int c)
Is a character upper case.
Parameters
in c character.
Returns
1 of upper case, else 0
Definition at line 80 of file str.c.
Referenced by tolower().
MEMSPACE int MATCH (char * str, char * pat)
Compare two strings.
Parameters
in str string to match.
in pat pattern to compare.
Returns
string lenth on match.
0 on no match.
Definition at line 245 of file str.c.
MEMSPACE int MATCH_LEN (char * str, char * pat)
Compare two strings limted to length of pattern.
Parameters
in str string to match.
in pat pattern to compare.
Returns
string lenth on match.
0 on no match.
Warning
Matches sub strings so be caeful.
Definition at line 281 of file str.c.
MEMSPACE int MATCHI (char * str, char * pat)
Compare two strings without case.
Parameters
in str string to match.
in pat pattern to compare.
Returns
string lenth on match.
0 on no match.
Definition at line 263 of file str.c.
MEMSPACE int MATCHI_LEN (char * str, char * pat)
Compare two strings without case limted to length of pattern.
Parameters
in str string to match.
in pat pattern to compare.
Returns
string lenth on match.
0 on no match.
Warning
Matches sub strings so be caeful.
Definition at line 307 of file str.c.
Referenced by match_headers().
MEMSPACE char* nextspace (char * ptr)
Skip to first white space in a string - tabs and spaces.
Parameters
in ptr input string
Returns
pointer to first white space character
Definition at line 432 of file str.c.
Referenced by fatfs_tests(), and process_args().
MEMSPACE void reverse (char * str)
Reverse a string in place Example: abcdef -> fedcba.
Parameters
in str string
Returns
string length
Definition at line 98 of file printf.c.
Referenced by p_itoa(), and p_ntoa().
MEMSPACE char* skipchars (char * str, char * pat)
Skip characters defined in user string.
Parameters
in str string
in pat pattern string
Returns
pointer to string after skipped characters.
Definition at line 454 of file str.c.
MEMSPACE char* skipspaces (char * ptr)
Skip white space in a string - tabs and spaces.
Parameters
in ptr input string
Returns
pointer to first non white space character
Definition at line 415 of file str.c.
Referenced by fatfs_tests(), get_token(), match_headers(), parse_http_request(), and user_tests().
MEMSPACE char* stralloc (char * str)
Allocate space for string.
Copies tring into allocated space.
Parameters
in str user string.
Returns
pointer to alocated string.
NULL on out of memory.
Allocate space for string.
Parameters
in *str string to allocate and copy memory for
Returns
: char * pointer to allocated string
Definition at line 393 of file str.c.
MEMSPACE int strcasecmp (const char * str, const char * pat)
Compare two strings without case.
Parameters
in str string to match.
in pat pattern to compare.
Returns
0 on match, < 0 implies str sorts before pat, > 0 implies str sorts after pat
Definition at line 200 of file str.c.
Referenced by file_type(), http_value(), and MATCHI().
MEMSPACE int strcmp (const char * str, const char * pat)
Compare two strings.
Parameters
in str string to match.
in pat pattern to compare.
Returns
0 on match, < 0 implies str sorts before pat, > 0 implies str sorts after pat
Definition at line 152 of file str.c.
Referenced by FindFontName(), main(), MATCH(), and user_tests().
MEMSPACE size_t strlen (const char * str)
String Length.
Parameters
in str string
Returns
string length
Definition at line 62 of file printf.c.
Referenced by _printf_fn(), arg_name(), arg_value(), escape(), fatfs_create(), fatfs_scan_files(), get_date(), html_msg(), main(), MATCH(), match_headers(), MATCH_LEN(), match_token(), MATCHI(), MATCHI_LEN(), mctime(), next_arg(), p_itoa(), p_ntoa(), parse_http_request(), process_args(), ReadBdf(), reverse(), send_message(), stralloc(), token(), trim_tail(), and vsnprintf().
MEMSPACE char* strnalloc (char * str, int len)
Allocate space for string with maximum size.
Copies tring into allocated space limited to maximum size.
Parameters
in str user string.
in len maximum string length.
Returns
pointer to alocated string.
Definition at line 369 of file str.c.
MEMSPACE int strncasecmp (const char * str, const char * pat, size_t len)
Compare two strings without case maximum len bytes in size.
Parameters
in str string to match.
in pat pattern to compare.
in len maximum string length for compare
Returns
0 on match, < 0 implies str sorts before pat, > 0 implies str sorts after pat
Definition at line 221 of file str.c.
Referenced by MATCHI_LEN().
MEMSPACE int strncmp (const char * str, const char * pat, size_t len)
Compare two strings maximum len bytes in size.
Parameters
in str string to match.
in pat pattern to compare.
in len maximum string length for compare
Returns
0 on match, < 0 implies str sorts before pat, > 0 implies str sorts after pat
Definition at line 173 of file str.c.
Referenced by MATCH_LEN(), match_token(), and token().
MEMSPACE void strupper (char * str)
UPPERCASE a string.
Parameters
in str string
Returns
void
Definition at line 117 of file printf.c.
Referenced by _printf_fn().
MEMSPACE int token (char * str, char * pat)
Search for token in a string matching user pattern.
Skips all non printable ASCII characters before trying match.
Parameters
in str string to search.
in pat pattern to search for.
Returns
string lenth on match.
0 on no match.
Definition at line 549 of file str.c.
Referenced by fatfs_tests(), rcvr_datablock(), ReadBdf(), and user_tests().
MEMSPACE int tolower (int c)
Convert character to lower case, only if it is upper case.
Parameters
in c character.
Returns
character or lowercase value or character
Definition at line 106 of file str.c.
MEMSPACE int toupper (int c)
Convert character to upper case, only if it is lower case.
Parameters
in c character.
Returns
character or upper case value or character
Definition at line 119 of file str.c.
Referenced by ReadBdf(), strcasecmp(), and strncasecmp().
MEMSPACE void trim_tail (char * str)
Trim White space and control characters from end of string.
Parameters
in str string
Returns
void
Warning
Overwrites White space and control characters with EOS.
Trim White space and control characters from end of string.
Parameters
in *str string to remove quotes from
Returns
: void
Definition at line 484 of file str.c.