TIMERS Struct Reference
user timer struct
#include <timer.h>
Data Fields
void(* user_timer_handler)(void)
uint8_t timer
Detailed Description
user timer struct
Definition at line 35 of file timer.h.
Field Documentation
uint8_t TIMERS::timer
Definition at line 38 of file timer.h.
Referenced by delete_all_timers(), kill_timer(), and set_timers().
void(* TIMERS::user_timer_handler) (void)
Definition at line 37 of file timer.h.
Referenced by delete_all_timers(), execute_timers(), kill_timer(), and set_timers().
The documentation for this struct was generated from the following file:
lib/timer.h