printf/sup.h File Reference
Part of Small printf, and verious conversion code with floating point support.
#include `user_config.h`
*
Functions
MEMSPACE long strtol (const char *nptr, char **endptr, int base)
Convert ASCII string to number in a given base.
MEMSPACE long atoi (uint8_t *str)
Convert ASCII string to number in base 10.
MEMSPACE double atof (char *str)
MEMSPACE int atodigit (int c, int radix)
Convert ASCII character to radix based digit , or -1.
MEMSPACE long aton (uint8_t *str, int base)
Convert ASCII string to number in a given base.
MEMSPACE void reverse (char *str)
Reverse a string Example: abcdef -> fedcba.
MEMSPACE void strupper (char *str)
Upercase a string.
Detailed Description
Part of Small printf, and verious conversion code with floating point support.
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file sup.h.
Function Documentation
MEMSPACE int atodigit (int c, int radix)
Convert ASCII character to radix based digit , or -1.
Parameters
in c character
in radix radix
Returns
radix based digit , or -1
Definition at line 80 of file sup.c.
Referenced by strtol().
MEMSPACE double atof (char * str)
MEMSPACE long atoi (uint8_t * str)
Convert ASCII string to number in base 10.
Parameters
in str string
in base radix
Returns
long value
Definition at line 160 of file sup.c.
Referenced by html_status(), main(), and ReadBdf().
MEMSPACE long aton (uint8_t * str, int base)
Convert ASCII string to number in a given base.
Parameters
in str string
in base radix
Returns
long value
Definition at line 98 of file sup.c.
MEMSPACE void reverse (char * str)
Reverse a string Example: abcdef -> fedcba.
Parameters
in str string
Returns
string length
Definition at line 45 of file sup.c.
Referenced by t_itoa(), and t_ntoa().
MEMSPACE long strtol (const char * nptr, char ** endptr, int base)
Convert ASCII string to number in a given base.
Parameters
in nptr string
in endptr pointer to string pointer return value
in base radix
Returns
long value
Definition at line 115 of file sup.c.
Referenced by atoi(), aton(), main(), and setdate_r().
MEMSPACE void strupper (char * str)
Upercase a string.
Parameters
in str string
Returns
void
Definition at line 64 of file sup.c.
Referenced by _printf_fn().