utils/sys.h File Reference
System utilities.
#include <stdint.h>
*
#include <stdarg.h>
*
#include <string.h>
*
#include <math.h>
*
Macros
#define MEMSPACE
#define HEAP_START ((uint32_t) & (_heap_start))
#define HEAP_END ((uint32_t) (0x3FFFC000U - 1U))
Functions
MEMSPACE void * malloc (size_t size)
calloc may be aliased to safecalloc
MEMSPACE void * calloc (size_t nmemb, size_t size)
calloc buffer POSIX function
MEMSPACE void free (void *p)
Free buffer POSIX function We only call os_free() is pointer is not null.
MEMSPACE uint32_t freeRam (void)
Return Free memory.
MEMSPACE void PrintRam (void)
Display Free memory and regions.
MEMSPACE void * safecalloc (size_t nmemb, size_t size)
Safe Calloc - Display Error message if Calloc fails.
MEMSPACE void * safemalloc (size_t size)
Safe Malloc - Display Error message if Malloc fails.
MEMSPACE void safefree (void *p)
Safe free - Only free a pointer if it is in malloc memory range. We want to try to catch frees of static or bogus data.
MEMSPACE void reset (void)
reset system
MEMSPACE void wdt_reset (void)
reset watchdog
Variables
void * _heap_start
Detailed Description
System utilities.
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Macro Definition Documentation
#define HEAP_END ((uint32_t) (0x3FFFC000U - 1U))
Definition at line 43 of file sys.h.
Referenced by PrintRam(), and safefree().
#define HEAP_START ((uint32_t) & (_heap_start))
Definition at line 42 of file sys.h.
Referenced by PrintRam(), and safefree().
#define MEMSPACE
Definition at line 38 of file sys.h.
Function Documentation
MEMSPACE void* calloc (size_t nmemb, size_t size)
calloc buffer POSIX function
Parameters
in nmemb number of elements
in size size of elements
Returns
void * buffer
Definition at line 56 of file sys.c.
Referenced by safecalloc(), and safemalloc().
MEMSPACE void free (void * p)
Free buffer POSIX function We only call os_free() is pointer is not null.
Parameters
in *p buffer to free
Returns
void
Definition at line 69 of file sys.c.
Referenced by safefree().
MEMSPACE uint32_t freeRam (void)
Return Free memory.
Returns
free memory in bytes.
See also
malloc().
Definition at line 80 of file sys.c.
MEMSPACE void* malloc (size_t size)
calloc may be aliased to safecalloc
free may be aliased to safefree malloc may be aliased to safecalloc malloc buffer POSIX function
Parameters
in size size of buffer
Returns
void * buffer
Definition at line 43 of file sys.c.
MEMSPACE void PrintRam (void)
Display Free memory and regions.
Returns
void
Definition at line 89 of file sys.c.
Referenced by setup().
MEMSPACE void reset (void)
reset system
Returns
void
Definition at line 159 of file sys.c.
Referenced by uart0_gets_init().
MEMSPACE void* safecalloc (size_t nmemb, size_t size)
Safe Calloc - Display Error message if Calloc fails.
We check if the pointer was in the heap.
Otherwise it may have been statically defined - display error.
Parameters
in nmemb number of elements
in size size of elements
Returns
void.
Definition at line 104 of file sys.c.
MEMSPACE void safefree (void * p)
Safe free - Only free a pointer if it is in malloc memory range. We want to try to catch frees of static or bogus data.
FIXME HEAP_END is not likely exact If it is not exact it is larger or equal so the test is usefull
We check if the pointer was in the heap.
Otherwise it may have been statically defined - display error.
Parameters
in p pointer to free.
Returns
void.
Definition at line 143 of file sys.c.
MEMSPACE void* safemalloc (size_t size)
Safe Malloc - Display Error message if Malloc fails.
We check if the pointer was in the heap.
Otherwise it may have been statically defined - display error.
Parameters
in size size
Returns
void.
Definition at line 121 of file sys.c.
MEMSPACE void wdt_reset (void)
reset watchdog
Returns
void
Definition at line 168 of file sys.c.
Referenced by f_getfree(), f_mkfs(), fatfs_scan_files(), mmc_power_on(), setup(), and wire_draw().
Variable Documentation
void* _heap_start