esp8266/system.c File Reference
Memory and system utilities.
#include `user_config.h`
*
#include `system.h`
*
#include `mathio.h`
*
Macros
#define HEAP_START ((uint32_t) & (_heap_start))
#define HEAP_END ((uint32_t) (0x3FFFC000UL - 1UL))
Functions
MEMSPACE void * malloc (size_t size)
malloc buffer POSIX function
MEMSPACE void * calloc (size_t nmemb, size_t size)
calloc buffer POSIX function
MEMSPACE void free (void *p)
Free buffer POSIX function We only call os_free() is pointer is not null.
MEMSPACE size_t freeRam ()
Return Free memory.
MEMSPACE void PrintRam ()
Display Free memory and regions.
MEMSPACE void * safecalloc (size_t nmemb, size_t size)
Safe Calloc - Display Error message if Calloc fails.
MEMSPACE void * safemalloc (size_t size)
Safe Malloc - Display Error message if Malloc fails.
MEMSPACE void safefree (void *p)
Safe free - Only free a pointer if it is in malloc memory range. We want to try to catch frees of static or bogus data.
MEMSPACE void reset (void)
reset system
MEMSPACE void wdt_reset (void)
reset watchdog
Variables
void * _heap_start
calloc may be aliased to safecalloc
Detailed Description
Memory and system utilities.
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Macro Definition Documentation
#define HEAP_END ((uint32_t) (0x3FFFC000UL - 1UL))
Definition at line 43 of file system.c.
Referenced by free(), PrintRam(), and safefree().
#define HEAP_START ((uint32_t) & (_heap_start))
Definition at line 42 of file system.c.
Referenced by free(), PrintRam(), and safefree().
Function Documentation
MEMSPACE void* calloc (size_t nmemb, size_t size)
calloc buffer POSIX function
Parameters
in nmemb number of elements
in size size of elements
Returns
void * buffer
Definition at line 69 of file system.c.
Referenced by db_calloc(), escape(), main(), and safecalloc().
MEMSPACE void free (void * p)
Free buffer POSIX function We only call os_free() is pointer is not null.
Parameters
in *p buffer to free
Returns
void
Definition at line 87 of file system.c.
Referenced by db_free(), main(), rx_fifo_free(), safefree(), and tx_fifo_free().
MEMSPACE size_t freeRam (void)
Return Free memory.
Returns
free memory in bytes.
See also
malloc().
Definition at line 104 of file system.c.
MEMSPACE void* malloc (size_t size)
malloc buffer POSIX function
Parameters
in size size of buffer
Returns
void * buffer
Definition at line 51 of file system.c.
MEMSPACE void PrintRam (void)
Display Free memory and regions.
Returns
void
Definition at line 113 of file system.c.
Referenced by calloc(), free(), malloc(), safecalloc(), safefree(), setup(), and user_tests().
MEMSPACE void reset (void)
reset system
Returns
void
Definition at line 181 of file system.c.
MEMSPACE void* safecalloc (size_t nmemb, size_t size)
Safe Calloc - Display Error message if Calloc fails.
We check if the pointer was in the heap.
Otherwise it may have been statically defined - display error.
Parameters
in nmemb number of elements
in size size of elements
Returns
void.
Definition at line 128 of file system.c.
Referenced by fatfs_cat(), fdevopen(), html_msg(), MatAlloc(), new_file_descriptor(), ntp_setup(), queue_new(), rwbuf_create(), safemalloc(), servertest_setup(), stralloc(), and strnalloc().
MEMSPACE void safefree (void * p)
Safe free - Only free a pointer if it is in malloc memory range. We want to try to catch frees of static or bogus data.
We check if the pointer was in the heap.
Otherwise it may have been statically defined - display error.
Parameters
in p pointer to free.
Returns
void.
Definition at line 165 of file system.c.
Referenced by fatfs_cat(), fatfs_tests(), free_file_descriptor(), html_msg(), MatFree(), new_file_descriptor(), ntp_setup(), queue_del(), queue_new(), and rwbuf_delete().
MEMSPACE void* safemalloc (size_t size)
Safe Malloc - Display Error message if Malloc fails.
We check if the pointer was in the heap.
Otherwise it may have been statically defined - display error.
Parameters
in size size
Returns
void.
Definition at line 146 of file system.c.
Referenced by fatfs_tests().
MEMSPACE void wdt_reset (void)
reset watchdog
Returns
void
Definition at line 190 of file system.c.
Referenced by fatfs_cat(), fatfs_ls(), fatfs_scan_files(), fgetc(), fputc(), ls(), mmc_test_timeout(), setup(), and wire_draw().
Variable Documentation
void* _heap_start
calloc may be aliased to safecalloc
free may be aliased to safefree malloc may be aliased to safecalloc