display/tft_printf.h File Reference
printf wrapper for ili9341 drivers
Macros
#define _TFT_PRINTF_H
Functions
MEMSPACE int tft_printf (window *win, const char *fmt,...)
tft_printf function
Detailed Description
printf wrapper for ili9341 drivers
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Macro Definition Documentation
#define _TFT_PRINTF_H
Definition at line 27 of file tft_printf.h.
Function Documentation
MEMSPACE int tft_printf (window * win, const char * fmt, ...)
tft_printf function
Parameters
in *win Window Structure
in fmt printf forat string
in ... vararg list or arguments
Returns
size of string
Definition at line 52 of file tft_printf.c.
Referenced by calibrate(), loop(), servertest_message(), setup(), and user_loop().