display/tft_printf.c File Reference
#include `user_config.h`
*
#include <stdint.h>
*
#include <stdarg.h>
*
#include <string.h>
*
#include <math.h>
*
#include `display/ili9341.h`
*
#include `display/tft_printf.h`
*
#include `printf/mathio.h`
*
Functions
static void _putc_win (struct _printf_t *p, char ch)
static void _putc_win_len (struct _printf_t *p, char ch)
MEMSPACE int tft_printf (window *win, const char *fmt,...)
tft_printf function
Function Documentation
static void _putc_win (struct _printf_t * p, char ch) [static]
Definition at line 34 of file tft_printf.c.
Referenced by tft_printf().
static void _putc_win_len (struct _printf_t * p, char ch) [static]
Definition at line 40 of file tft_printf.c.
MEMSPACE int tft_printf (window * win, const char * fmt, ...)
tft_printf function
Parameters
in *win Window Structure
in fmt printf forat string
in ... vararg list or arguments
Returns
size of string
Definition at line 52 of file tft_printf.c.
Referenced by servertest_message(), test_types(), and user_loop().