lib/timetests.c File Reference
Common Linux/POSIX time testing functions.
#include <stdlib.h>
*
#include <string.h>
*
#include <time.h>
*
Functions
MEMSPACE void mysrand (int seed)
MEMSPACE int myrand (int start, int end)
MEMSPACE int timetests (char *str, int check)
Variables
static unsigned int __seed
Detailed Description
Common Linux/POSIX time testing functions.
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
MEMSPACE int myrand (int start, int end)
Definition at line 52 of file timetests.c.
Referenced by timetests().
MEMSPACE void mysrand (int seed)
Definition at line 46 of file timetests.c.
Referenced by timetests().
MEMSPACE int timetests (char * str, int check)
Definition at line 99 of file timetests.c.
Referenced by user_tests().
Variable Documentation
unsigned int __seed [static]
Definition at line 43 of file timetests.c.
Referenced by myrand(), and mysrand().