lib/timer_hal.c File Reference
timer hardware abstartion layer functions
#include <stdint.h>
*
#include <stdarg.h>
*
#include <string.h>
*
#include <math.h>
*
#include `timer.h`
*
#include `time.h`
*
Functions
MEMSPACE void clock_clear ()
clear time and timezone to 0.
MEMSPACE void disable_timers ()
Disable all timer tasks.
MEMSPACE void enable_timers ()
Enable timer tasks.
void execute_timers ()
Execute all user timers at SYSTEM_HZ rate.
MEMSPACE void clock_init ()
Initialize clock task.
void clock_task (void)
1000HZ timer task
MEMSPACE void init_timers ()
Setup all timers tasksi and enable interrupts.
MEMSPACE int clock_getres (clockid_t clk_id, struct timespec *res)
Read clock time resolution into struct timepec *ts - POSIX function.
MEMSPACE void setup_timers_isr ()
Setup main timers ISR - this ISR calls execute_timers() task.
MEMSPACE int clock_settime (clockid_t clk_id, const struct timespec *ts)
Set system clock using seconds and nonoseconds - POSIX function.
MEMSPACE int clock_gettime (clockid_t clk_id, struct timespec *ts)
Generic clock_gettime() function WITHOUT high resolution.
Variables
volatile ts_t __clock
System Clock Time.
tz_t __tzone
System Time Zone.
static int timers_enabled = 0
static int timers_configured = 0
TIMERS timer_irq [MAX_TIMER_CNT]
array or user timers
Detailed Description
timer hardware abstartion layer functions
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Function Documentation
MEMSPACE void clock_clear (void)
clear time and timezone to 0.
See also
clock_settime().
settimezone().
Returns
void.
Definition at line 58 of file timer_hal.c.
Referenced by clock_init().
MEMSPACE int clock_getres (clockid_t clk_id, struct timespec * res)
Read clock time resolution into struct timepec *ts - POSIX function.
Note: We ignore clk_id
Parameters
in clk_id unused hardware clock index.
out res timespec resolution result.
Returns
0 on success.
-1 on error.
Definition at line 189 of file timer_hal.c.
MEMSPACE int clock_gettime (clockid_t clk_id, struct timespec * ts)
Generic clock_gettime() function WITHOUT high resolution.
Read clock time into struct timepec *ts - POSIX function.
Note: We ignore clk_id, and include low level counter offsets when available.
Parameters
in clk_id unused hardware clock index.
out ts timespec result.
Returns
0 on success.
-1 on error.
Definition at line 340 of file timer_hal.c.
Referenced by clock_elapsed_begin(), clock_elapsed_end(), clock_settime(), gettimeofday(), and time().
MEMSPACE void clock_init (void)
Initialize clock task.
Returns
void.
See time.c
Definition at line 121 of file timer_hal.c.
Referenced by init_timers().
MEMSPACE int clock_settime (clockid_t clk_id, const struct timespec * ts)
Set system clock using seconds and nonoseconds - POSIX function.
Parameters
in clk_id Hardware timer index used when there are more then one.
Note: We ignore clk_id for now.
in ts struct timespec input.
Returns
0.
Definition at line 247 of file timer_hal.c.
Referenced by clock_clear(), clock_set(), setdate_r(), and settimeofday().
void clock_task (void)
1000HZ timer task
Returns
void
Definition at line 133 of file timer_hal.c.
Referenced by clock_init(), and init_timers().
MEMSPACE void disable_timers (void)
Disable all timer tasks.
Returns
void
Definition at line 72 of file timer_hal.c.
MEMSPACE void enable_timers (void)
Enable timer tasks.
Returns
void
Definition at line 90 of file timer_hal.c.
Referenced by init_timers().
void execute_timers (void)
Execute all user timers at SYSTEM_HZ rate.
Returns
void
Definition at line 106 of file timer_hal.c.
Referenced by setup_timers_isr().
MEMSPACE void init_timers (void)
Setup all timers tasksi and enable interrupts.
See also
clock_task()
: timer_hal.c for hardware dependent interface
Returns
void
See time.c
See time.c
Definition at line 150 of file timer_hal.c.
Referenced by setup().
MEMSPACE void setup_timers_isr (void)
Setup main timers ISR - this ISR calls execute_timers() task.
Notes:
We attempt to use the largest reload count for a given SYSTEM_HZ interrupt rate. This permits using hardware counter offset to increase resolution to the best possible amount.
Assumptions:
We can divide the CPU frequency EXACTLY with timer/counter having no fractional remander.
See also
ISR().
Returns
void.
Definition at line 208 of file timer_hal.c.
Referenced by init_timers().
Variable Documentation
volatile ts_t __clock
System Clock Time.
Definition at line 34 of file timer_hal.c.
tz_t __tzone
System Time Zone.
Definition at line 37 of file timer_hal.c.
TIMERS timer_irq[MAX_TIMER_CNT]
array or user timers
Definition at line 44 of file timer_hal.c.
int timers_configured = 0 [static]
Definition at line 41 of file timer_hal.c.
Referenced by disable_timers(), enable_timers(), and init_timers().
int timers_enabled = 0 [static]
Definition at line 40 of file timer_hal.c.
Referenced by disable_timers(), enable_timers(), and init_timers().