utils/uart.c File Reference
Uart driver for ESP8266.
#include `user_config.h`
*
Functions
void uart_rx_enable (uint8 uart_no)
Enable receive interrupts for a uart.
void uart_rx_disable (uint8 uart_no)
DIsable receive interrupts for a uart.
void uart_tx_enable (uint8_t uart_no)
Enable transmit interrupts for a uart.
void uart_tx_disable (uint8_t uart_no)
Disable transmit interrupts for a uart.
void tx_fifo_flush (int uart_no)
Flush transmit fifo for a uart.
void rx_fifo_flush (int uart_no)
Flush receive fifo for a uart.
MEMSPACE int tx_fifo_used (int uart_no)
Get the number of bytes used in transmit fifo.
MEMSPACE int tx_fifo_free (int uart_no)
Get the number of bytes free in transmit fifo.
MEMSPACE int tx_fifo_empty (int uart_no)
Test if the transmit fifo is empty.
MEMSPACE int rx_fifo_used (int uart_no)
Get the number of bytes used in receive fifo.
MEMSPACE int rx_fifo_free (int uart_no)
Get the number of bytes free in receive fifo.
MEMSPACE int rx_fifo_empty (int uart_no)
Test if the receive fifo is empty.
MEMSPACE uint8_t tx_fifo_putc (int uart_no, uint8_t c)
Add a byte to the trasmit fifo We assume that tx_fifo_free() was called!
MEMSPACE uint8_t rx_fifo_getc (int uart_no)
Remove a byte from the receive fifo We assume that rx_fifo_used() was called!
MEMSPACE int tx_fifo_write (int uart_no, uint8_t *buf, int size)
Write a data buffer to the transmit fifo Note: This function does not wait/block util there is enough free space to meet the request. So you must check that the return value matches the size.
MEMSPACE int rx_fifo_read (int uart_no, uint8_t *buf, int size)
Read a data buffer from the receive fifo Note: This function does not wait/block util there is enough free space to meet the request. So you must check that the return value matches the size.
LOCAL MEMSPACE void uart_putb (uint8 uart_no, uint8 data)
Blocking I/O functions.
LOCAL MEMSPACE uint8_t uart_getb (int uart_no)
Read a byte from a uart Note: This function waits/blocks util the read can happen.
MEMSPACE void uart_putc (uint8 uart_no, char c)
Write a byte from a uart with NL to CR/NL conversion Note: This function waits/blocks util the write can happen.
MEMSPACE uint8_t uart_getc (int uart_no)
Read a byte from a uart with NL to CR/NL conversion Note: This function waits/blocks util the read can happen.
MEMSPACE void uart0_putc (uint8 c)
Write a byte to uart0 with NL to CR/NL conversion Note: This function waits/blocks util the write can happen.
MEMSPACE uint8_t uart0_getc ()
Read a byte from uart0 with NL to CR/NL conversion Note: This function waits/blocks util the read can happen.
MEMSPACE void uart1_putc (uint8 c)
Write a byte to uart1 with NL to CR/NL conversion Note: This function waits/blocks util the write can happen.
MEMSPACE uint8_t uart1_getc ()
Read a byte from uart1 with NL to CR/NL conversion Note: This function waits/blocks util the read can happen.
void uart_callback (void *p)
Uart interrupt callback function Process all receive and transmit events here.
void uart0_gets_add (uint8_t data)
transfer data into the uart0_gets_receive_queue Provide line buffering for uart0_gets() [in] data: character to add to queue
MEMSPACE void uart0_gets_init (int size)
allocate and initialize uart0_gets data structures Provide line buffering for uart0_gets() [in] size: size of line buffer
MEMSPACE int uart0_gets (char *buf, int max)
uart0_gets non-blocking line buffered gets [in] buf: user buffer to fill [in] max: miximum size of buf
MEMSPACE void uart_config (uint8 uart_no, uint32_t baud, uint8_t data_bits, uint8_t stop_bits, uint8_t parity)
Uart configuration, baud rate, data and stop bits, parity.
MEMSPACE void uart_init (UartBaudRate uart0_br, UartBaudRate uart1_br)
initialize uart0 and uart1 Defaults: 8 = data bits, 1 = stop bits, no parity
MEMSPACE void uart_reattach ()
Reinitialize uart0 and uart1 calls uart_init()
MEMSPACE void UART_SetPrintPort (uint8 uart_no)
Install debug uart.
Variables
queue_t * uart0_gets_receive_queue
uart0 receive queue
char * uart0_gets_line
uart0 gets line bufer
uint8_t uart0_gets_ready = 0
uart0 gets line buffer ready flag
int uart0_gets_size = 0
uar0 gets line buffer size
Detailed Description
Uart driver for ESP8266. Uart driver for ESP8266 based on Esprissif documents.
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
See Also
http://bbs.espressif.com/viewtopic.php?f=21&t=414
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file uart.c.
Function Documentation
MEMSPACE int rx_fifo_empty (int uart_no)
Test if the receive fifo is empty.
Parameters
in uart_no uart number
Returns
1 if empty, 0 otherwise
Definition at line 182 of file uart.c.
Referenced by uart_getb().
void rx_fifo_flush (int uart_no)
Flush receive fifo for a uart.
Parameters
in uart_no uart number
Returns
void
Definition at line 105 of file uart.c.
Referenced by uart_config().
MEMSPACE int rx_fifo_free (int uart_no)
Get the number of bytes free in receive fifo.
Parameters
in uart_no uart number
Returns
bytes free
Definition at line 168 of file uart.c.
MEMSPACE uint8_t rx_fifo_getc (int uart_no)
Remove a byte from the receive fifo We assume that rx_fifo_used() was called!
Parameters
in uart_no uart number
Returns
c, (or 0 if fill user error)
Definition at line 215 of file uart.c.
Referenced by uart_getb().
MEMSPACE int rx_fifo_read (int uart_no, uint8_t * buf, int size)
Read a data buffer from the receive fifo Note: This function does not wait/block util there is enough free space to meet the request. So you must check that the return value matches the size.
Parameters
in uart_no uart number
in *buf output buffer
in size size of output buffer
Returns
number of bytes actually read from the fifo - may not be size!
Definition at line 273 of file uart.c.
MEMSPACE int rx_fifo_used (int uart_no)
Get the number of bytes used in receive fifo.
Parameters
in uart_no uart number
Returns
bytes in use
Definition at line 155 of file uart.c.
Referenced by rx_fifo_getc(), rx_fifo_read(), and uart_callback().
MEMSPACE int tx_fifo_empty (int uart_no)
Test if the transmit fifo is empty.
Parameters
in uart_no uart number
Returns
1 if empty, 0 otherwise
Definition at line 143 of file uart.c.
Referenced by tcp_data_receive_callback(), and uart_callback().
void tx_fifo_flush (int uart_no)
Flush transmit fifo for a uart.
Parameters
in uart_no uart number
Returns
void
Definition at line 94 of file uart.c.
Referenced by uart_config().
MEMSPACE int tx_fifo_free (int uart_no)
Get the number of bytes free in transmit fifo.
Parameters
in uart_no uart number
Returns
bytes free
Definition at line 130 of file uart.c.
Referenced by tx_fifo_putc(), tx_fifo_write(), uart_callback(), and uart_putb().
MEMSPACE uint8_t tx_fifo_putc (int uart_no, uint8_t c)
Add a byte to the trasmit fifo We assume that tx_fifo_free() was called!
Parameters
in uart_no uart number
in c byte to add
Returns
c, (or 0 if full user error)
Definition at line 199 of file uart.c.
Referenced by uart_putb().
MEMSPACE int tx_fifo_used (int uart_no)
Get the number of bytes used in transmit fifo.
Parameters
in uart_no uart number
Returns
bytes in use
Definition at line 118 of file uart.c.
MEMSPACE int tx_fifo_write (int uart_no, uint8_t * buf, int size)
Write a data buffer to the transmit fifo Note: This function does not wait/block util there is enough free space to meet the request. So you must check that the return value matches the size.
Parameters
in uart_no uart number
in *src input buffer
in size size of input buffer
Returns
number of bytes sent
Definition at line 238 of file uart.c.
MEMSPACE uint8_t uart0_getc (void)
Read a byte from uart0 with NL to CR/NL conversion Note: This function waits/blocks util the read can happen.
Returns
byte read
Definition at line 383 of file uart.c.
Referenced by uart_init().
MEMSPACE int uart0_gets (char * buf, int max)
uart0_gets non-blocking line buffered gets [in] buf: user buffer to fill [in] max: miximum size of buf
Returns
0, or number of characters in line
Definition at line 547 of file uart.c.
Referenced by user_task().
void uart0_gets_add (uint8_t data)
transfer data into the uart0_gets_receive_queue Provide line buffering for uart0_gets() [in] data: character to add to queue
Returns
void
Definition at line 491 of file uart.c.
Referenced by uart_callback().
MEMSPACE void uart0_gets_init (int size)
allocate and initialize uart0_gets data structures Provide line buffering for uart0_gets() [in] size: size of line buffer
Returns
void
Definition at line 527 of file uart.c.
Referenced by uart_init().
MEMSPACE void uart0_putc (uint8 c)
Write a byte to uart0 with NL to CR/NL conversion Note: This function waits/blocks util the write can happen.
Parameters
in c byte to write
Returns
void
Definition at line 372 of file uart.c.
Referenced by tcp_data_receive_callback(), uart_init(), and UART_SetPrintPort().
MEMSPACE uint8_t uart1_getc (void)
Read a byte from uart1 with NL to CR/NL conversion Note: This function waits/blocks util the read can happen.
Returns
byte read
Definition at line 407 of file uart.c.
MEMSPACE void uart1_putc (uint8 c)
Write a byte to uart1 with NL to CR/NL conversion Note: This function waits/blocks util the write can happen.
Parameters
in c byte to write
Returns
void
Definition at line 396 of file uart.c.
Referenced by UART_SetPrintPort().
void uart_callback (void * p)
Uart interrupt callback function Process all receive and transmit events here.
Parameters
in *p callback pointer - currently unused
Returns
void
Definition at line 420 of file uart.c.
Referenced by uart_init().
MEMSPACE void uart_config (uint8 uart_no, uint32_t baud, uint8_t data_bits, uint8_t stop_bits, uint8_t parity)
Uart configuration, baud rate, data and stop bits, parity.
Parameters
in uart_no uart number
in baud baud
in data_bits number of data bits, 5 .. 8
in stop_bits number of stop bits, ONE_STOP_BIT|TWO_STOP_BIT
in parity parity, NO_PARITY,ODD_PARITY,EVEN_PARITY
Returns
void
Definition at line 586 of file uart.c.
Referenced by uart_init().
LOCAL MEMSPACE uint8_t uart_getb (int uart_no)
Read a byte from a uart Note: This function waits/blocks util the read can happen.
Parameters
in uart_no uart number
Returns
byte read
Definition at line 319 of file uart.c.
Referenced by uart_getc().
MEMSPACE uint8_t uart_getc (int uart_no)
Read a byte from a uart with NL to CR/NL conversion Note: This function waits/blocks util the read can happen.
Parameters
in uart_no uart number
Returns
byte read
Definition at line 352 of file uart.c.
Referenced by uart0_getc(), and uart1_getc().
MEMSPACE void uart_init (UartBaudRate uart0_br, UartBaudRate uart1_br)
initialize uart0 and uart1 Defaults: 8 = data bits, 1 = stop bits, no parity
Parameters
in uart_no uart number
in baud baud rate for uart 0
in baud baud rate for uart 1
Returns
void
Definition at line 645 of file uart.c.
Referenced by uart_reattach(), and user_init().
LOCAL MEMSPACE void uart_putb (uint8 uart_no, uint8 data)
Blocking I/O functions.
Write a byte to a uart Note: This function waits/blocks util the write can happen
Parameters
in uart_no uart number
in data byte to write
Returns
void
Definition at line 305 of file uart.c.
Referenced by uart_putc().
MEMSPACE void uart_putc (uint8 uart_no, char c)
Write a byte from a uart with NL to CR/NL conversion Note: This function waits/blocks util the write can happen.
Parameters
in uart_no uart number
Returns
void
Definition at line 336 of file uart.c.
Referenced by uart0_printf(), uart0_putc(), and uart1_putc().
MEMSPACE void uart_reattach (void)
Reinitialize uart0 and uart1 calls uart_init()
Returns
void
Definition at line 670 of file uart.c.
void uart_rx_disable (uint8 uart_no)
DIsable receive interrupts for a uart.
Parameters
in uart_no uart number
Returns
void
Definition at line 62 of file uart.c.
void uart_rx_enable (uint8 uart_no)
Enable receive interrupts for a uart.
Parameters
in uart_no uart number
Returns
void
Definition at line 52 of file uart.c.
MEMSPACE void UART_SetPrintPort (uint8 uart_no)
Install debug uart.
Returns
void
Definition at line 683 of file uart.c.
void uart_tx_disable (uint8_t uart_no)
Disable transmit interrupts for a uart.
Parameters
in uart_no uart number
Returns
void
Definition at line 82 of file uart.c.
Referenced by tcp_data_receive_callback(), and uart_callback().
void uart_tx_enable (uint8_t uart_no)
Enable transmit interrupts for a uart.
Parameters
in uart_no uart number
Returns
void
Definition at line 72 of file uart.c.
Referenced by tcp_data_receive_callback(), and uart_callback().
Variable Documentation
char* uart0_gets_line
uart0 gets line bufer
Definition at line 37 of file uart.c.
Referenced by uart0_gets(), uart0_gets_add(), and uart0_gets_init().
uint8_t uart0_gets_ready = 0
uart0 gets line buffer ready flag
Definition at line 39 of file uart.c.
Referenced by uart0_gets(), uart0_gets_add(), and uart0_gets_init().
queue_t* uart0_gets_receive_queue
uart0 receive queue
Definition at line 35 of file uart.c.
int uart0_gets_size = 0
uar0 gets line buffer size
Definition at line 41 of file uart.c.
Referenced by uart0_gets(), uart0_gets_add(), and uart0_gets_init().