fatfs/unicode.c File Reference
FatFS Unicode include file R0.10b (C) ChaN, 2014.
#include `user_config.h`
*
#include `ff.h`
*
Functions
MEMSPACE WCHAR ff_convert (WCHAR wch, UINT dir)
MEMSPACE WCHAR ff_wtoupper (WCHAR wch)
Detailed Description
FatFS Unicode include file R0.10b (C) ChaN, 2014.
Copyright 2014 ChaN.
Definition in file unicode.c.
Function Documentation
MEMSPACE WCHAR ff_convert (WCHAR wch, UINT dir)
Definition at line 15 of file unicode.c.
Referenced by create_name(), f_getlabel(), f_gets(), f_setlabel(), get_fileinfo(), and putc_bfd().
MEMSPACE WCHAR ff_wtoupper (WCHAR wch)
Definition at line 27 of file unicode.c.
Referenced by cmp_lfn(), create_name(), and f_setlabel().