yield/user_task.h File Reference
#include <stdint.h>
*
#include <stdarg.h>
*
#include <string.h>
*
#include <math.h>
*
Macros
#define MEMSPACE
#define WEAK_ATR __attribute__((weak))
Functions
int atexit (void(*func)())
void abort (void)
void esp_yield (void)
void esp_schedule (void)
void yield (void)
void loop_wrapper (void)
void init_done (void)
void user_init (void)
Macro Definition Documentation
#define MEMSPACE
Definition at line 15 of file user_task.h.
#define WEAK_ATR __attribute__((weak))
Definition at line 20 of file user_task.h.
Function Documentation
void abort (void)
Definition at line 56 of file user_task.c.
Referenced by loop_task(), and yield().
int atexit (void(*)() func)
Definition at line 42 of file user_task.c.
void esp_schedule (void)
Definition at line 78 of file user_task.c.
Referenced by init_done(), loop_wrapper(), web_data_connect_callback(), web_data_disconnect_callback(), web_data_receive_callback(), web_data_sent_callback(), and yield().
void esp_yield (void)
Definition at line 66 of file user_task.c.
Referenced by yield().
void init_done (void)
Definition at line 148 of file user_task.c.
Referenced by user_init().
void loop_wrapper (void)
Definition at line 112 of file user_task.c.
Referenced by loop_task().
void user_init (void)
Definition at line 1011 of file user_main.c.
Referenced by setup().
void yield (void)
Definition at line 85 of file user_task.c.
Referenced by optimistic_yield().