user/user_main.c File Reference
Main user and initialization code This initialize the platform and runs the main user task. All display updates and task are called from here.
#include `user_config.h`
*
Macros
#define USER_TASK_DELAY_TIMER 30
#define RUN_TASK 0
#define UserTaskPrio USER_TASK_PRIO_0
#define UserTaskQueueLen 4
#define HighTaskPrio USER_TASK_PRIO_MAX
#define HighTaskQueueLen 1
#define NormalTaskPrio USER_TASK_PRIO_2
#define NormalTaskQueueLen 8
#define IdleTaskPrio USER_TASK_PRIO_0
#define IdleTaskQueueLen 1
Functions
int DEBUG_PRINTF (const char *fmt,...)
void ets_timer_disarm (ETSTimer *ptimer)
void ets_timer_setfn (ETSTimer *ptimer, ETSTimerFunc *pfunction, void *parg)
MEMSPACE LOCAL void init_done_cb (void)
Callback for system_init_done_cb() Sends message to run task.
MEMSPACE LOCAL void HighTask (os_event_t *events)
High Priority Task Queue.
MEMSPACE LOCAL void NormalTask (os_event_t *events)
Normal Priority Task Queue.
MEMSPACE LOCAL void IdleTask (os_event_t *events)
Idle Priority Task Queue.
MEMSPACE LOCAL void UserTask (os_event_t *events)
User Message handler task Runs corrected cube demo from Sem Optionally wireframe Earth viewer.
MEMSPACE LOCAL void sendMsgToUserTask (void *arg)
Message passing function Sends message to run task.
LOCAL void user_task (void)
test task Runs corrected cube demo from Sem Optionally wireframe Earh viewer
MEMSPACE void user_init (void)
main() Initialize user task
void ntp_setup (void)
void user_help ()
MEMSPACE int user_tests (char *str)
help functions test parser
Variables
window * master
window _winstats
window * winstats = &_winstats
window _windemo
window * windemo = &_windemo
window _wintest
window * wintest = &_wintest
window _wintestdemo
window * wintestdemo = &_wintestdemo
int16_t xpos
int16_t ypos
int16_t ip_xpos
int16_t ip_ypos
LOCAL double degree = 0.0
LOCAL double deg_inc = 4
LOCAL double dscale_inc
LOCAL double dscale
LOCAL double dscale_max
LOCAL long count = 0
LOCAL int rad
LOCAL point V
LOCAL point S
LOCAL uint32_t adc_sum = 0
LOCAL int adc_count = 0
double voltage = 0
LOCAL os_timer_t UserTimerHandler
os_event_t UserTaskQueue [UserTaskQueueLen]
os_event_t HighTaskQueue [HighTaskQueueLen]
os_event_t NormalTaskQueue [NormalTaskQueueLen]
os_event_t IdleTaskQueue [IdleTaskQueueLen]
int ntp_init = 0
int signal_loop = 0
Detailed Description
Main user and initialization code This initialize the platform and runs the main user task. All display updates and task are called from here.
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file user_main.c.
Macro Definition Documentation
#define HighTaskPrio USER_TASK_PRIO_MAX
Definition at line 102 of file user_main.c.
Referenced by user_init().
#define HighTaskQueueLen 1
Definition at line 103 of file user_main.c.
Referenced by user_init().
#define IdleTaskPrio USER_TASK_PRIO_0
Definition at line 108 of file user_main.c.
Referenced by IdleTask(), and user_init().
#define IdleTaskQueueLen 1
Definition at line 109 of file user_main.c.
Referenced by user_init().
#define NormalTaskPrio USER_TASK_PRIO_2
Definition at line 105 of file user_main.c.
Referenced by user_init().
#define NormalTaskQueueLen 8
Definition at line 106 of file user_main.c.
Referenced by user_init().
#define RUN_TASK 0
Definition at line 98 of file user_main.c.
Referenced by sendMsgToUserTask(), and UserTask().
#define USER_TASK_DELAY_TIMER 30
Definition at line 97 of file user_main.c.
Referenced by user_init().
#define UserTaskPrio USER_TASK_PRIO_0
Definition at line 99 of file user_main.c.
Referenced by user_init().
#define UserTaskQueueLen 4
Definition at line 100 of file user_main.c.
Referenced by user_init().
Function Documentation
int DEBUG_PRINTF (const char * fmt, ...)
Referenced by bridge_task_init(), cal_dex_dump_hex(), clock_elapsed_end(), clock_init(), display_ts(), dump_stat(), fatfs_cat(), fatfs_cd(), fatfs_copy(), fatfs_create(), fatfs_filinfo_list(), fatfs_help(), fatfs_ls(), fatfs_mkdir(), fatfs_pwd(), fatfs_rm(), fatfs_rmdir(), fatfs_stat(), fatfs_status(), fgetc(), font_attr(), fputc(), hspi_cs_disable(), hspi_cs_enable(), init_done_cb(), init_timers(), mmc_init(), mmc_install_timer(), mmc_select(), mmc_test(), mmc_test_timeout(), ntp_setup(), perror(), put_rc(), set_timers(), setdate_r(), user_help(), user_init(), user_task(), and user_tests().
void ets_timer_disarm (ETSTimer * ptimer)
void ets_timer_setfn (ETSTimer * ptimer, ETSTimerFunc * pfunction, void * parg)
MEMSPACE LOCAL void HighTask (os_event_t * events)
High Priority Task Queue.
Parameters
in events event structure
Returns
void
Definition at line 189 of file user_main.c.
Referenced by user_init().
MEMSPACE LOCAL void IdleTask (os_event_t * events)
Idle Priority Task Queue.
Parameters
in events event structure
Returns
void
Definition at line 209 of file user_main.c.
Referenced by user_init().
MEMSPACE LOCAL void init_done_cb (void)
Callback for system_init_done_cb() Sends message to run task.
Returns
void
Definition at line 178 of file user_main.c.
Referenced by user_init().
MEMSPACE LOCAL void NormalTask (os_event_t * events)
Normal Priority Task Queue.
Parameters
in events event structure
Returns
void
Definition at line 199 of file user_main.c.
Referenced by user_init().
void ntp_setup (void)
Definition at line 119 of file user_main.c.
Referenced by user_task().
MEMSPACE LOCAL void sendMsgToUserTask (void * arg)
Message passing function Sends message to run task.
Returns
void
Definition at line 245 of file user_main.c.
Referenced by user_init().
void user_help ()
Definition at line 430 of file user_main.c.
Referenced by user_tests().
MEMSPACE void user_init (void)
main() Initialize user task
Returns
void
Definition at line 488 of file user_main.c.
LOCAL void user_task (void)
test task Runs corrected cube demo from Sem Optionally wireframe Earh viewer
Returns
void
Definition at line 258 of file user_main.c.
Referenced by UserTask().
MEMSPACE int user_tests (char * str)
help functions test parser
Keywords and arguments are matched against test functions If ther are matched the function along with its argements are called.
Parameters
in str User supplied command line
Returns
1 The ruturn code indicates a command matched.
0 if no rules matched
Definition at line 449 of file user_main.c.
Referenced by user_task().
MEMSPACE LOCAL void UserTask (os_event_t * events)
User Message handler task Runs corrected cube demo from Sem Optionally wireframe Earth viewer.
Parameters
in events event structure
Returns
void
Definition at line 225 of file user_main.c.
Referenced by user_init().
Variable Documentation
window _windemo
Definition at line 47 of file user_main.c.
window _winstats
Definition at line 43 of file user_main.c.
window _wintest
Definition at line 51 of file user_main.c.
window _wintestdemo
Definition at line 55 of file user_main.c.
LOCAL int adc_count = 0
Definition at line 93 of file user_main.c.
Referenced by user_task().
LOCAL uint32_t adc_sum = 0
Definition at line 92 of file user_main.c.
Referenced by user_task().
LOCAL long count = 0
Definition at line 87 of file user_main.c.
Referenced by fread(), ftoa(), fwrite(), hspi_RX(), hspi_TX(), hspi_TXRX(), rx_fifo_getc(), rx_fifo_read(), t_vsnprintf(), tft_putch(), tx_fifo_putc(), tx_fifo_write(), and user_task().
LOCAL double deg_inc = 4
Definition at line 79 of file user_main.c.
Referenced by user_task().
LOCAL double degree = 0.0
Definition at line 77 of file user_main.c.
Referenced by cordic_quad(), and user_task().
LOCAL double dscale
Definition at line 83 of file user_main.c.
Referenced by user_init(), and user_task().
LOCAL double dscale_inc
Definition at line 81 of file user_main.c.
Referenced by user_init(), and user_task().
LOCAL double dscale_max
Definition at line 85 of file user_main.c.
Referenced by user_init(), and user_task().
os_event_t HighTaskQueue[HighTaskQueueLen]
Definition at line 114 of file user_main.c.
Referenced by user_init().
os_event_t IdleTaskQueue[IdleTaskQueueLen]
Definition at line 116 of file user_main.c.
Referenced by user_init().
int16_t ip_xpos
Definition at line 75 of file user_main.c.
Referenced by user_init(), and user_task().
int16_t ip_ypos
Definition at line 75 of file user_main.c.
Referenced by user_init(), and user_task().
window* master
Definition at line 40 of file user_main.c.
os_event_t NormalTaskQueue[NormalTaskQueueLen]
Definition at line 115 of file user_main.c.
Referenced by user_init().
int ntp_init = 0
Definition at line 118 of file user_main.c.
Referenced by ntp_setup().
LOCAL int rad
Definition at line 88 of file user_main.c.
Referenced by cordic_quad(), and user_task().
LOCAL point S
Definition at line 90 of file user_main.c.
int signal_loop = 0
Definition at line 250 of file user_main.c.
Referenced by user_task().
os_event_t UserTaskQueue[UserTaskQueueLen]
Definition at line 113 of file user_main.c.
Referenced by user_init().
LOCAL os_timer_t UserTimerHandler
Definition at line 111 of file user_main.c.
Referenced by user_init().
LOCAL point V
Definition at line 89 of file user_main.c.
Referenced by user_init(), and user_task().
double voltage = 0
Definition at line 94 of file user_main.c.
Referenced by user_task().
window* windemo = &_windemo
Definition at line 48 of file user_main.c.
window* winstats = &_winstats
Definition at line 44 of file user_main.c.
window* wintest = &_wintest
Definition at line 52 of file user_main.c.
window* wintestdemo = &_wintestdemo
Definition at line 56 of file user_main.c.
int16_t xpos
Definition at line 74 of file user_main.c.
Referenced by user_init(), and user_task().
int16_t ypos
Definition at line 74 of file user_main.c.
Referenced by user_task().