yield/user_task.c File Reference
#include `user_config.h`
*
#include `ets_sys.h`
*
#include `os_type.h`
*
#include `osapi.h`
*
#include `mem.h`
*
#include `user_interface.h`
*
Macros
#define CONT_STACKSIZE 4096
#define LOOP_TASK_PRIORITY 0
#define LOOP_QUEUE_SIZE 1
#define OPTIMISTIC_YIELD_TIME_US 16000
Functions
int atexit (void(*func)())
void loop ()
test task Runs corrected cube demo from Sem Optionally wireframe Earh viewer
void setup ()
main() Initialize user task
cont_t g_cont __attribute__ ((aligned(16)))
void abort ()
void esp_yield ()
void esp_schedule ()
void yield ()
void optimistic_yield (uint32_t interval_us)
void loop_wrapper ()
static void loop_task (os_event_t *events)
void init_done ()
void user_init (void)
Variables
struct rst_info resetInfo
static os_event_t g_loop_queue [LOOP_QUEUE_SIZE]
uint32_t g_micros_at_task_start
bool setup_done = false
Macro Definition Documentation
#define CONT_STACKSIZE 4096
Definition at line 26 of file user_task.c.
#define LOOP_QUEUE_SIZE 1
Definition at line 36 of file user_task.c.
Referenced by user_init().
#define LOOP_TASK_PRIORITY 0
Definition at line 35 of file user_task.c.
Referenced by esp_schedule(), and user_init().
#define OPTIMISTIC_YIELD_TIME_US 16000
Definition at line 38 of file user_task.c.
Function Documentation
cont_t g_cont __attribute__ ((aligned(16)))
void abort (void)
Definition at line 56 of file user_task.c.
Referenced by loop_task(), and yield().
int atexit (void(*)() func)
Definition at line 42 of file user_task.c.
void esp_schedule (void)
Definition at line 78 of file user_task.c.
Referenced by init_done(), loop_wrapper(), web_data_connect_callback(), web_data_disconnect_callback(), web_data_receive_callback(), web_data_sent_callback(), and yield().
void esp_yield (void)
Definition at line 66 of file user_task.c.
Referenced by yield().
void init_done (void)
Definition at line 147 of file user_task.c.
Referenced by user_init().
void loop ()
test task Runs corrected cube demo from Sem Optionally wireframe Earh viewer
Returns
void
Definition at line 150 of file user_main.c.
Referenced by loop_wrapper(), and UserTask().
static void loop_task (os_event_t * events) [static]
Definition at line 135 of file user_task.c.
Referenced by user_init().
void loop_wrapper (void)
Definition at line 112 of file user_task.c.
Referenced by loop_task().
void optimistic_yield (uint32_t interval_us)
Definition at line 101 of file user_task.c.
Referenced by mmc_power_on(), mmc_test_timeout(), and wait_send().
void setup (void)
main() Initialize user task
Returns
void
Definition at line 388 of file user_main.c.
Referenced by loop_wrapper(), and user_init().
void user_init (void)
Definition at line 158 of file user_task.c.
void yield (void)
Definition at line 85 of file user_task.c.
Referenced by optimistic_yield().
Variable Documentation
os_event_t g_loop_queue[LOOP_QUEUE_SIZE] [static]
Definition at line 52 of file user_task.c.
uint32_t g_micros_at_task_start
Definition at line 54 of file user_task.c.
struct rst_info resetInfo
Definition at line 40 of file user_task.c.
bool setup_done = false
Definition at line 111 of file user_task.c.