utils/util.h File Reference
Flash read and bit utilities.
Macros
#define SWAP(a, b) do { a ^= b; b ^= a; a ^= b; } while(0)
#define ABS(x) ((x)<0 ? -(x) : (x))
#define SIGN(x) (((x) == 0) ? 0 : ((x) > 0) ? 1 : -1)
#define MAX(x, y) (((x) > (y)) ? x : y)
#define SPACES ` \t\r`
#define SPACESNL ` \t\n\r`
Functions
uint8_t read_flash8 (uint8_t *p)
void cpy_flash (uint8_t *src, uint8_t *dest, int size)
Copy data from Flash to Ram Uses flash_read8() to avoid alighnment problems.
uint16_t read_flash16 (uint8_t *p)
16 bits reads from Flash memory space Uses cpy_flash() to avoid alighnment problems
uint32_t read_flash32 (uint8_t *p)
32 bits reads from Flash memory space Uses cpy_flash() to avoid alighnment problems
uint64_t read_flash64 (uint8_t *p)
64 bits reads from Flash memory space Uses cpy_flash() to avoid alighnment problems
uint32_t read_flash_ptr (uint8_t *p)
Pointer read from Flash memory space Uses cpy_flash() to avoid alighnment problems.
int bittestv (unsigned char *ptr, int off)
Test bit in byte array.
int bittestxy (unsigned char *ptr, int x, int y, int w, int h)
Test bit in w * h size bit array usng x and y offsets.
MEMSPACE void reset (void)
reset system
MEMSPACE void wdt_reset (void)
reset watchdog
MEMSPACE void free (void *p)
Free buffer POSIX function We only call os_free() is pointer is not null.
MEMSPACE void * calloc (size_t nmemb, size_t size)
calloc buffer POSIX function
MEMSPACE void * malloc (size_t size)
malloc buffer POSIX function
MEMSPACE char * skipspaces (char *ptr)
Skip white space in a string - tabs and spaces.
MEMSPACE char * nextspace (char *ptr)
Skip to first white space in a string - tabs and spaces.
MEMSPACE char * skipchars (char *str, char *pat)
Skip characters defined in user string.
MEMSPACE void trim_tail (char *str)
Trim White space and control characters from end of string.
MEMSPACE char * strnalloc (char *str, int len)
Allocate space for string with maximum size.
MEMSPACE char * stralloc (char *str)
Allocate space for string.
MEMSPACE char * get_token (char *str, char *token, int max)
return next token
MEMSPACE int token (char *str, char *pat)
Search for token in a string matching user pattern.
MEMSPACE uint8_t hexd (char c)
Convert Character into HEX digit.
MEMSPACE int isupper (int c)
Is a character upper case.
MEMSPACE int islower (int c)
Is a character lower case.
MEMSPACE int tolower (int c)
Convert character to lower case, only if it is upper case.
MEMSPACE int toupper (int c)
Convert character to upper case, only if it is lower case.
MEMSPACE size_t strlen (const char *str)
MEMSPACE int strcmp (const char *str, const char *pat)
MEMSPACE int strncmp (const char *str, const char *pat, size_t len)
MEMSPACE int strcasecmp (const char *str, const char *pat)
Compare two strings without case.
MEMSPACE int strncasecmp (const char *str, const char *pat, size_t len)
Compare two strings without case maximum len bytes in size.
MEMSPACE int MATCH (char *str, char *pat)
Compare two strings.
MEMSPACE int MATCHI (char *str, char *pat)
Compare two strings without case.
MEMSPACE int MATCH_LEN (char *str, char *pat)
Compare two strings limted to length of pattern.
MEMSPACE int MATCHI_LEN (char *str, char *pat)
Compare two strings without case limted to length of pattern.
Detailed Description
Flash read and bit utilities.
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
Please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file util.h.
Macro Definition Documentation
#define ABS(x) ((x)<0 ? -(x) : (x))
Definition at line 29 of file util.h.
#define MAX(x, y) (((x) > (y)) ? x : y)
Definition at line 31 of file util.h.
#define SIGN(x) (((x) == 0) ? 0 : ((x) > 0) ? 1 : -1)
Definition at line 30 of file util.h.
Referenced by t_sscanf().
#define SPACES ` \t\r`
Definition at line 33 of file util.h.
#define SPACESNL ` \t\n\r`
Definition at line 34 of file util.h.
#define SWAP(a, b) do { a ^= b; b ^= a; a ^= b; } while(0)
Definition at line 28 of file util.h.
Referenced by tft_fillRectXY(), and tft_fillTriangle().
Function Documentation
int bittestv (unsigned char * ptr, int off)
Test bit in byte array.
Parameters
in *ptr byte array
in off bit offset to test
Returns
1 if bit is set, 0 if not
Definition at line 146 of file util.c.
Referenced by bittestxy(), and tft_bit_blit().
int bittestxy (unsigned char * ptr, int x, int y, int w, int h)
Test bit in w * h size bit array usng x and y offsets.
Parameters
in *ptr byte array
in x bit x offset
in y bit y offset
in w bit array wide
in h bit array high
Returns
1 if bit is set, 0 if not
Test bit in w * h size bit array usng x and y offsets.
Parameters
in *ptr byte array
in x bit x offset
in y bit y offset
in w the width of bit array
in h the height of bit array
Returns
1 if bit is set, 0 if not
Definition at line 161 of file util.c.
MEMSPACE void* calloc (size_t nmemb, size_t size)
calloc buffer POSIX function
Parameters
in nmemb number of elements
in size size of elements
Returns
void * buffer
Definition at line 213 of file util.c.
Referenced by db_calloc(), escape(), fatfs_alloc_finfo(), fatfs_cat(), fatfs_copy(), fdevopen(), html_msg(), main(), new_file_descriptor(), queue_new(), rwbuf_create(), stralloc(), strnalloc(), and uart0_gets_init().
void cpy_flash (uint8_t * src, uint8_t * dest, int size)
Copy data from Flash to Ram Uses flash_read8() to avoid alighnment problems.
Parameters
in *src address to read from
out *dest address to write to
in size number of bytes to copy
Returns
void
Definition at line 84 of file util.c.
Referenced by font_attr(), read_flash16(), read_flash32(), read_flash64(), read_flash_ptr(), and wire_draw().
MEMSPACE void free (void * p)
Free buffer POSIX function We only call os_free() is pointer is not null.
Parameters
in *p buffer to free
Returns
void
Definition at line 201 of file util.c.
Referenced by db_free(), fatfs_alloc_finfo(), fatfs_cat(), fatfs_copy(), fatfs_free_filinfo(), ff_memfree(), free_file_descriptor(), html_msg(), main(), new_file_descriptor(), queue_del(), queue_new(), queue_push_buffer(), rwbuf_delete(), rx_fifo_free(), and tx_fifo_free().
MEMSPACE char* get_token (char * str, char * token, int max)
return next token
Skips all non printable ASCII characters before token
Token returns only printable ASCII
Parameters
in str string to search.
out token token to return
in max maximum token size
Returns
pointer past token on success .
NULL if no token found
return next token
Parameters
in *str string
out *token token characters greter then space less then 0x7f
in max maximum length of token
Returns
: string pointer to character after token
Definition at line 380 of file util.c.
MEMSPACE uint8_t hexd (char c)
Convert Character into HEX digit.
Parameters
in c character.
Returns
HEX digit [0..F] on success.
0xff on fail.
Definition at line 459 of file util.c.
Referenced by process_args().
MEMSPACE int islower (int c)
Is a character lower case.
Parameters
in c character.
Returns
1 of lower case, else 0
Definition at line 488 of file util.c.
Referenced by toupper().
MEMSPACE int isupper (int c)
Is a character upper case.
Parameters
in c character.
Returns
1 of upper case, else 0
Definition at line 476 of file util.c.
Referenced by tolower().
MEMSPACE void* malloc (size_t size)
malloc buffer POSIX function
Parameters
in size size of buffer
Returns
void * buffer
Definition at line 224 of file util.c.
Referenced by ff_memalloc().
MEMSPACE int MATCH (char * str, char * pat)
Compare two strings.
Parameters
in str string to match.
in pat pattern to compare.
Returns
string lenth on match.
0 on no match.
Definition at line 627 of file util.c.
MEMSPACE int MATCH_LEN (char * str, char * pat)
Compare two strings limted to length of pattern.
Parameters
in str string to match.
in pat pattern to compare.
Returns
string lenth on match.
0 on no match.
Warning
Matches sub strings so be caeful.
Definition at line 663 of file util.c.
Referenced by rewrite_html_token().
MEMSPACE int MATCHI (char * str, char * pat)
Compare two strings without case.
Parameters
in str string to match.
in pat pattern to compare.
Returns
string lenth on match.
0 on no match.
Definition at line 645 of file util.c.
MEMSPACE int MATCHI_LEN (char * str, char * pat)
Compare two strings without case limted to length of pattern.
Parameters
in str string to match.
in pat pattern to compare.
Returns
string lenth on match.
0 on no match.
Warning
Matches sub strings so be caeful.
Definition at line 689 of file util.c.
Referenced by match_headers().
MEMSPACE char* nextspace (char * ptr)
Skip to first white space in a string - tabs and spaces.
Parameters
in ptr input string
Returns
pointer to first white space character
Definition at line 254 of file util.c.
Referenced by fatfs_tests(), and parse_http_request().
uint16_t read_flash16 (uint8_t * p)
16 bits reads from Flash memory space Uses cpy_flash() to avoid alighnment problems
Parameters
in *p address to read
Returns
uint16_t
Definition at line 98 of file util.c.
uint32_t read_flash32 (uint8_t * p)
32 bits reads from Flash memory space Uses cpy_flash() to avoid alighnment problems
Parameters
in *p address to read
Returns
uint32_t
Definition at line 110 of file util.c.
uint64_t read_flash64 (uint8_t * p)
64 bits reads from Flash memory space Uses cpy_flash() to avoid alighnment problems
Parameters
in *p address to read
Returns
uint64_t
Definition at line 122 of file util.c.
uint8_t read_flash8 (uint8_t * p)
Definition at line 41 of file util.c.
Referenced by bittestv(), and cpy_flash().
uint32_t read_flash_ptr (uint8_t * p)
Pointer read from Flash memory space Uses cpy_flash() to avoid alighnment problems.
Parameters
in *p address to read
Returns
uint32_t
Definition at line 134 of file util.c.
MEMSPACE void reset (void)
reset system
Returns
void
Definition at line 180 of file util.c.
Referenced by uart0_gets_init().
MEMSPACE char* skipchars (char * str, char * pat)
Skip characters defined in user string.
Parameters
in str string
in pat pattern string
Returns
pointer to string after skipped characters.
Definition at line 276 of file util.c.
MEMSPACE char* skipspaces (char * ptr)
Skip white space in a string - tabs and spaces.
Parameters
in ptr input string
Returns
pointer to first non white space character
Definition at line 237 of file util.c.
Referenced by fatfs_tests(), get_token(), match_headers(), parse_http_request(), process_args(), and user_tests().
MEMSPACE char* stralloc (char * str)
Allocate space for string.
Copies tring into allocated space.
Parameters
in str user string.
Returns
pointer to alocated string.
NULL on out of memory.
Allocate space for string.
Parameters
in *str string to allocate and copy memory for
Returns
: char * pointer to allocated string
Definition at line 353 of file util.c.
MEMSPACE int strcasecmp (const char * str, const char * pat)
Compare two strings without case.
Parameters
in str string to match.
in pat pattern to compare.
Returns
0 on match, < 0 implies str sorts before pat, > 0 implies str sorts after pat
Definition at line 584 of file util.c.
Referenced by file_type(), http_value(), and MATCHI().
MEMSPACE int strcmp (const char * str, const char * pat)
Referenced by FindFontName(), main(), MATCH(), and process_requests().
MEMSPACE size_t strlen (const char * str)
Referenced by _printf_fn(), arg_name(), arg_value(), escape(), fatfs_create(), fatfs_scan_files(), get_date(), html_msg(), main(), MATCH(), MATCH_LEN(), match_token(), MATCHI(), MATCHI_LEN(), mctime(), next_arg(), parse_http_request(), read_html_token(), ReadBdf(), reverse(), rewrite_html_token(), send_message(), stralloc(), t_ftoa(), t_itoa(), t_ntoa(), token(), trim_tail(), and vsnprintf().
MEMSPACE char* strnalloc (char * str, int len)
Allocate space for string with maximum size.
Copies tring into allocated space limited to maximum size.
Parameters
in str user string.
in len maximum string length.
Returns
pointer to alocated string.
Definition at line 329 of file util.c.
MEMSPACE int strncasecmp (const char * str, const char * pat, size_t len)
Compare two strings without case maximum len bytes in size.
Parameters
in str string to match.
in pat pattern to compare.
in len maximum string length for compare
Returns
0 on match, < 0 implies str sorts before pat, > 0 implies str sorts after pat
Definition at line 605 of file util.c.
Referenced by MATCHI_LEN().
MEMSPACE int strncmp (const char * str, const char * pat, size_t len)
Referenced by MATCH_LEN(), match_token(), and token().
MEMSPACE int token (char * str, char * pat)
Search for token in a string matching user pattern.
Skips all non printable ASCII characters before trying match.
Parameters
in str string to search.
in pat pattern to search for.
Returns
string lenth on match.
0 on no match.
Definition at line 424 of file util.c.
Referenced by fatfs_tests(), rcvr_datablock(), ReadBdf(), and user_tests().
MEMSPACE int tolower (int c)
Convert character to lower case, only if it is upper case.
Parameters
in c character.
Returns
character or lowercase value or character
Definition at line 501 of file util.c.
MEMSPACE int toupper (int c)
Convert character to upper case, only if it is lower case.
Parameters
in c character.
Returns
character or upper case value or character
Definition at line 513 of file util.c.
Referenced by ReadBdf(), strcasecmp(), and strncasecmp().
MEMSPACE void trim_tail (char * str)
Trim White space and control characters from end of string.
Parameters
in str string
Returns
void
Warning
Overwrites White space and control characters with EOS.
Trim White space and control characters from end of string.
Parameters
in *str string to remove quotes from
Returns
: void
Definition at line 306 of file util.c.
MEMSPACE void wdt_reset (void)
reset watchdog
Returns
void
Definition at line 189 of file util.c.
Referenced by f_getfree(), f_mkfs(), fatfs_scan_files(), mmc_power_on(), setup(), and wire_draw().