web/web.c File Reference
Small web server for esp8266.
#include `user_config.h`
*
#include <stdint.h>
*
#include <stdarg.h>
*
#include <string.h>
*
#include <math.h>
*
#include `display/ili9341.h`
*
#include `web/web.h`
*
Macros
#define MAX_MSG 1024
max size of ERROR/REDIRECT/STATUS Message buffer
#define CGI_TOKEN_SIZE 128
max size of CGI token
#define BUFFER_SIZE 1000
max size of read/write socket buffers Note: reducing this size below 1500 will slow down transfer a great deal
Functions
MEMSPACE void led_on (int led)
MEMSPACE void led_off (int led)
Turn off virtual LED.
static MEMSPACE void tcp_accept (espconn_t *esp_config, esp_tcp *esp_tcp_config, uint16_t port, void(*connect_callback)(struct espconn *))
Accept an incomming connection, setup connect_callback.
MEMSPACE void rwbuf_rinit (rwbuf_t *p)
Initialize socket read status and read index.
MEMSPACE void rwbuf_winit (rwbuf_t *p)
Initialize socket send status and write index.
MEMSPACE void display_ipv4 (char *msg, uint8_t *ip, int port)
Display IPV4 address.
MEMSPACE void rwbuf_delete (rwbuf_t *p)
Delete socket read/write buffers.
MEMSPACE rwbuf_t * rwbuf_create ()
Create socket read/write buffer for a connection.
MEMSPACE rwbuf_t * find_connection (espconn_t *conn, int *index, char *msg)
Find a read/write socket buffer for an espconn connection.
MEMSPACE rwbuf_t * create_connection (espconn_t *conn)
Allocate read/write socket buffers and add it to the working pool.
MEMSPACE void delete_connection (rwbuf_t *p)
Delete a rwbuf_t entry using its index.
MEMSPACE MEMSPACE int write_byte (rwbuf_t *p, int c)
Write a byte (buffered) using the rwbuf_t socket buffers for this connection If the buffers are full the socket is written using espconn_send.
MEMSPACE int wait_send (rwbuf_t *p)
Wait for buffer to send for this connection If the buffers have any data in them it is written using espconn_send.
MEMSPACE void write_flush (rwbuf_t *p)
Flush the the socket write buffers for this connection If the buffers have any data in them it is written using espconn_send.
MEMSPACE void write_len (rwbuf_t *p, char *str, int len)
Write data using buffered write_byte function.
MEMSPACE void write_str (rwbuf_t *p, char *str)
Write string using buffered write_byte function.
static MEMSPACE void _write_byte_fn (struct _printf_t *pr, char c)
low level vsock_printf function that calls socket write_byte
MEMSPACE int vsock_printf (rwbuf_t *p, const char *fmt, va_list va)
vsock_printf function
MEMSPACE int sock_printf (rwbuf_t *p, const char *fmt,...)
sock_printf function
MEMSPACE int html_msg (rwbuf_t *p, int status, char type, char *fmt,...)
Send an HTML status message to socket.
MEMSPACE char * meminit (mem_t *p, char *ptr, int size)
in memory memory gets function
MEMSPACE char * memgets (mem_t *p)
Memory gets function We ASSUME we can replace any
 with a \0.
MEMSPACE char * mime_type (int type)
return strung pointer for mime type index
MEMSPACE int file_type (char *name)
Determin mimetype using file name extension.
MEMSPACE char * html_status (int status)
Convert html status into string using http_status table.
MEMSPACE void init_hinfo (hinfo_t *hi)
MEMSPACE int match_headers (char *str, char **p)
Match GET/POST message headers.
MEMSPACE char * process_args (hinfo_t *hi, char *ptr)
Process GET argments or POST message name/value data. HTML encoding is done in place often reducting the size of the result. Convert name=value pairs into null terminated strings. Names and values are each terminated with an EOS by replaceing '?', '&', '=' characters seen while scaning.
MEMSPACE char * first_arg (hinfo_t *hi)
Find first POST/GET argument.
MEMSPACE char * next_arg (hinfo_t *hi)
Find next POST/GET argument We have to skip a name and a value.
MEMSPACE char * arg_name (hinfo_t *hi)
Return the argument name for current argument.
MEMSPACE char * arg_value (hinfo_t *hi)
Return the argument value for current argument.
MEMSPACE char * http_value (hinfo_t *hi, char *str)
Lookup and argument name and return its value.
MEMSPACE int is_header (char *str, char **p)
Does the string look like a header token with a ':' ?
MEMSPACE char * nextbreak (char *ptr)
Find next space or ? character.
MEMSPACE void u5toa (char *ptr, uint16_t num)
Print a decimal number into a string without an EOS.
MEMSPACE void html_head (rwbuf_t *p, int status, char type, int len)
Write HTTP Contenet-Type/Content-Length header.
MEMSPACE int parse_http_request (rwbuf_t *p, hinfo_t *hi)
Get arguments for a GET or POST request.
static MEMSPACE void web_data_receive_callback (void *arg, char *data, unsigned short length)
Network receive callback function.
static MEMSPACE void web_data_sent_callback (void *arg)
Network sent callback function.
static MEMSPACE void web_data_disconnect_callback (void *arg)
Network disconnect callback function.
static MEMSPACE void web_data_reconnect_callback (void *arg, int8_t err)
Network disconnect callback function.
static MEMSPACE void web_data_connect_callback (espconn_t *conn)
incomming connection setup callbacks
MEMSPACE int is_cgitoken_char (int c)
test to see if a character is a valid member of the CGI token character set CGI tokens have the following syntax @ They start with `@_` and end with `_@` `@_` must be first two characters of string May have upper and lower case letters, numbers and '-'
MEMSPACE int find_cgitoken_start (char *str)
Find start of CGI token in a string CGI tokens have the following syntax @ They start with `@_` and end with `_@` `@_` must be first two characters of string May have upper and lower case letters, numbers and '-' param[in] *str: string to search.
MEMSPACE int is_cgitoken (char *str)
Does the string have a CGI TOKEN at the beginning ? CGI tokens have the following syntax @ They start with `@_` and end with `_@` `@_` must be first two characters of string May have upper and lower case letters, numbers and '-'.
MEMSPACE int rewrite_cgi_token (rwbuf_t *p, char *src)
Replace CGI token with CGI result CGI tokens have the following syntax @ They start with `@_` and end with `_@` `@_` must be first two characters of string May have upper and lower case letters, numbers and '-'.
static MEMSPACE void process_requests (rwbuf_t *p)
Process an incoming HTTP request.
MEMSPACE void web_task ()
Process ALL incoming HTTP requests.
MEMSPACE void web_init_connections ()
MEMSPACE void web_init (int port)
Setup WEB server and accept connections.
Variables
window * winmsg
window * wintop
rwbuf_t * web_connections [MAX_CONNECTIONS]
socket buffers for this connection
espconn_t WebConn
Master espconn structure of the web server.
static esp_tcp WebTcp
Master network configuration for the web server.
header_t msg_headers []
HTTP headers we understand.
char * http_status []
HTTP status code messages.
mime_t mimes []
MIME types.
static MEMSPACE _led = 0
Turn on virtual LED.
int connections
Detailed Description
Small web server for esp8266.
Copyright 2015 Mike Gore, GPL License
You are free to use this code under the terms of GPL
please retain a copy of this notice in any code you use it in.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This software is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Macro Definition Documentation
#define BUFFER_SIZE 1000
max size of read/write socket buffers Note: reducing this size below 1500 will slow down transfer a great deal
Definition at line 43 of file web.c.
Referenced by rwbuf_create().
#define CGI_TOKEN_SIZE 128
max size of CGI token
Definition at line 40 of file web.c.
#define MAX_MSG 1024
max size of ERROR/REDIRECT/STATUS Message buffer
Definition at line 38 of file web.c.
Referenced by html_msg().
Function Documentation
static MEMSPACE void _write_byte_fn (struct _printf_t * pr, char c) [static]
low level vsock_printf function that calls socket write_byte
Parameters
in *pr printf structure and user buffer for this socket
in c character to write
Returns
void
Definition at line 710 of file web.c.
Referenced by vsock_printf().
MEMSPACE char* arg_name (hinfo_t * hi)
Return the argument name for current argument.
Parameters
in *hi hinfo_t structure with arguments
Returns
argument name
Definition at line 1217 of file web.c.
Referenced by http_value(), and parse_http_request().
MEMSPACE char* arg_value (hinfo_t * hi)
Return the argument value for current argument.
Parameters
in *hi hinfo_t structure with arguments
Returns
argument value
Definition at line 1265 of file web.c.
Referenced by http_value(), and parse_http_request().
MEMSPACE rwbuf_t* create_connection (espconn_t * conn)
Allocate read/write socket buffers and add it to the working pool.
Parameters
in conn espconn pointer for this connection
Returns
rwbuf_t pointer to created structure
Definition at line 471 of file web.c.
Referenced by web_data_connect_callback().
MEMSPACE void delete_connection (rwbuf_t * p)
Delete a rwbuf_t entry using its index.
Parameters
in p rwbuf_t pointer
Definition at line 517 of file web.c.
Referenced by web_data_disconnect_callback().
MEMSPACE void display_ipv4 (char * msg, uint8_t * ip, int port)
Display IPV4 address.
Parameters
in msg user supplied message
in ip IP address as uint8_t [4]
in port Port number
Returns
void
Definition at line 277 of file web.c.
Referenced by delete_connection(), find_connection(), web_data_connect_callback(), web_data_disconnect_callback(), web_data_receive_callback(), web_data_reconnect_callback(), and web_data_sent_callback().
MEMSPACE int file_type (char * name)
Determin mimetype using file name extension.
Parameters
in *name name to test
Returns
index into mimetype table
Definition at line 915 of file web.c.
MEMSPACE int find_cgitoken_start (char * str)
Find start of CGI token in a string CGI tokens have the following syntax @ They start with `@_` and end with `_@` `@_` must be first two characters of string May have upper and lower case letters, numbers and '-' param[in] *str: string to search.
Returns
offset of start of token, or -1 if not found
Definition at line 1909 of file web.c.
MEMSPACE rwbuf_t* find_connection (espconn_t * conn, int * index, char * msg)
Find a read/write socket buffer for an espconn connection.
Parameters
in conn espconn pointer for this connection
in *index return index into pool of rwbuf_t connections
in *msg user debug message
Returns
rwbuf_t pointer to found connection with *index set, or NULL with *index == -1 on failure
Definition at line 396 of file web.c.
Referenced by web_data_disconnect_callback(), web_data_receive_callback(), web_data_reconnect_callback(), and web_data_sent_callback().
MEMSPACE char* first_arg (hinfo_t * hi)
Find first POST/GET argument.
Parameters
in *hi hinfo_t structure with arguments
Returns
argument value pair
Definition at line 1154 of file web.c.
Referenced by http_value(), and parse_http_request().
MEMSPACE void html_head (rwbuf_t * p, int status, char type, int len)
Write HTTP Contenet-Type/Content-Length header.
Parameters
in *p rwbuf_t pointer to socket buffer
in status html status message index
in type mimetype index
in len length of message
Returns
void
Definition at line 1437 of file web.c.
MEMSPACE int html_msg (rwbuf_t * p, int status, char type, char * fmt, ...)
Send an HTML status message to socket.
Parameters
in p socket buffer structure
in status index into http_status table
in type mime type index
in fmt printf format string
in ... list of arguments
Returns
bytes written, 0 on wrror
Definition at line 772 of file web.c.
MEMSPACE char* html_status (int status)
Convert html status into string using http_status table.
Parameters
in status html status number
Returns
http_status entry mathing status, or 500 Internal Server Error
Definition at line 949 of file web.c.
Referenced by html_head(), and html_msg().
MEMSPACE char* http_value (hinfo_t * hi, char * str)
Lookup and argument name and return its value.
Parameters
in *hi hinfo_t structure with arguments
in *str string to lookup
Returns
argument value
Definition at line 1341 of file web.c.
MEMSPACE void init_hinfo (hinfo_t * hi)
Initilize hinfo_t structure
Parameters
in *hi hinfo_t structure pointer to initialize
Returns
hinfo_t structure pointer to initialize
Definition at line 974 of file web.c.
Referenced by parse_http_request().
MEMSPACE int is_cgitoken (char * str)
Does the string have a CGI TOKEN at the beginning ? CGI tokens have the following syntax @ They start with `@_` and end with `_@` `@_` must be first two characters of string May have upper and lower case letters, numbers and '-'.
/**
Returns
size of token or -1 on fail
Definition at line 1936 of file web.c.
MEMSPACE int is_cgitoken_char (int c)
test to see if a character is a valid member of the CGI token character set CGI tokens have the following syntax @ They start with `@_` and end with `_@` `@_` must be first two characters of string May have upper and lower case letters, numbers and '-'
Parameters
in c character to test
Returns
1 if the character is a CGI token or 0 if not
Definition at line 1884 of file web.c.
MEMSPACE int is_header (char * str, char ** p)
Does the string look like a header token with a ':' ?
Parameters
in *str string to test
in **p string pointer to set on match
Returns
1 if it looks like a header, otherwise 0
Definition at line 1370 of file web.c.
Referenced by parse_http_request().
MEMSPACE void led_off (int led)
Turn off virtual LED.
Parameters
in led led to turn off
Returns
void
Definition at line 194 of file web.c.
MEMSPACE void led_on (int led)
Definition at line 184 of file web.c.
MEMSPACE int match_headers (char * str, char ** p)
Match GET/POST message headers.
Parameters
in *str string to patch
in **p points past matched string on sucess
Returns
header index or -1 on no match
Definition at line 996 of file web.c.
Referenced by parse_http_request().
MEMSPACE char* memgets (mem_t * p)
Memory gets function We ASSUME we can replace any
 with a \0.
Parameters
in p structure with size and offset used by mem_gets()
Returns
pointer to string
Definition at line 871 of file web.c.
Referenced by parse_http_request().
MEMSPACE char* meminit (mem_t * p, char * ptr, int size)
in memory memory gets function
Parameters
in p structure with size and offset used by mem_gets()
in ptr start of memory area
in size size of memory area
Returns
pointer to start of memory area (ptr)
Definition at line 852 of file web.c.
Referenced by parse_http_request().
MEMSPACE char* mime_type (int type)
return strung pointer for mime type index
Parameters
in type index into mim_type table
Returns
pointer to string, if out of range uses index PTYPE_ERR
Definition at line 902 of file web.c.
Referenced by html_head(), and html_msg().
MEMSPACE char* next_arg (hinfo_t * hi)
Find next POST/GET argument We have to skip a name and a value.
Parameters
in *hi hinfo_t structure with arguments
Returns
argument value pair
Definition at line 1166 of file web.c.
Referenced by http_value(), and parse_http_request().
MEMSPACE char* nextbreak (char * ptr)
Find next space or ? character.
Parameters
in *ptr string to search
Returns
first space or ? character
Definition at line 1395 of file web.c.
Referenced by parse_http_request().
MEMSPACE int parse_http_request (rwbuf_t * p, hinfo_t * hi)
Get arguments for a GET or POST request.
Parameters
in *p rwbuf_t pointer to socket buffer
in *hi header structure of parsed result
Returns
0 on error, 1 on success
We must respond with Connection: keep-alive now
Definition at line 1454 of file web.c.
MEMSPACE char* process_args (hinfo_t * hi, char * ptr)
Process GET argments or POST message name/value data. HTML encoding is done in place often reducting the size of the result. Convert name=value pairs into null terminated strings. Names and values are each terminated with an EOS by replaceing '?', '&', '=' characters seen while scaning.
Parameters
in *hi hinfo_t structure to fill
in *ptr GET arguments or PUT message body.
Returns
*ptr pointer that points to just past the header area.
Definition at line 1035 of file web.c.
Referenced by parse_http_request().
static MEMSPACE void process_requests (rwbuf_t * p) [static]
Process an incoming HTTP request.
Parameters
in *p rwbuf_t pointer to socket buffer
Returns
void
FIXME if we want to support keep-alive we have to change this
Definition at line 2022 of file web.c.
MEMSPACE int rewrite_cgi_token (rwbuf_t * p, char * src)
Replace CGI token with CGI result CGI tokens have the following syntax @ They start with `@_` and end with `_@` `@_` must be first two characters of string May have upper and lower case letters, numbers and '-'.
Parameters
in *p socket stream
in *str string with token, example @
Returns
length of replaced text or 0 if no CGI handler was matched
Definition at line 1978 of file web.c.
MEMSPACE rwbuf_t* rwbuf_create (void)
Create socket read/write buffer for a connection.
Returns
void
Definition at line 332 of file web.c.
Referenced by create_connection().
MEMSPACE void rwbuf_delete (rwbuf_t * p)
Delete socket read/write buffers.
Parameters
in p rwbuf_t pointer to buffer to delete
Returns
void
Definition at line 294 of file web.c.
Referenced by delete_connection(), rwbuf_create(), and web_data_sent_callback().
MEMSPACE void rwbuf_rinit (rwbuf_t * p)
Initialize socket read status and read index.
Parameters
in p rwbuf_t pointer
Returns
void
Definition at line 246 of file web.c.
Referenced by rwbuf_create(), rwbuf_delete(), and web_data_receive_callback().
MEMSPACE void rwbuf_winit (rwbuf_t * p)
Initialize socket send status and write index.
Parameters
in p rwbuf_t pointer
Returns
void
Definition at line 260 of file web.c.
Referenced by rwbuf_create(), rwbuf_delete(), and web_data_sent_callback().
MEMSPACE int sock_printf (rwbuf_t * p, const char * fmt, ...)
sock_printf function
Parameters
in p socket buffer structure
in fmt printf format string
in ... list of arguments
Returns
bytes written
Definition at line 749 of file web.c.
Referenced by html_head().
static MEMSPACE void tcp_accept (espconn_t * esp_config, esp_tcp * esp_tcp_config, uint16_t port, void(*)(struct espconn *) connect_callback) [static]
Accept an incomming connection, setup connect_callback.
Parameters
in *esp_config ESP8266 network type an mode configuration structure
in *esp_tcp_config network protocol structure
in port network port to listen on
in connect_callback connection callback function pointer
Returns
void
Definition at line 210 of file web.c.
MEMSPACE void u5toa (char * ptr, uint16_t num)
Print a decimal number into a string without an EOS.
Parameters
in *ptr buffer to write number to
in num number to convet
Returns
void
Definition at line 1416 of file web.c.
Referenced by html_msg().
MEMSPACE int vsock_printf (rwbuf_t * p, const char * fmt, va_list va)
vsock_printf function
Parameters
in p socket buffer structure
in fmt printf format string
in va va_list of arguments
Returns
bytes written
Definition at line 727 of file web.c.
Referenced by sock_printf().
MEMSPACE int wait_send (rwbuf_t * p)
Wait for buffer to send for this connection If the buffers have any data in them it is written using espconn_send.
Parameters
in *p rwbuf_t pointer for this socket buffer
Returns
1 on success, 0 on error
Definition at line 602 of file web.c.
Referenced by write_flush().
static MEMSPACE void web_data_connect_callback (espconn_t * conn) [static]
incomming connection setup callbacks
Parameters
in *conn espconn structure pointer
Returns
void
Definition at line 1837 of file web.c.
static MEMSPACE void web_data_disconnect_callback (void * arg) [static]
Network disconnect callback function.
Parameters
in *arg connection pointer
Definition at line 1781 of file web.c.
Referenced by web_data_connect_callback().
static MEMSPACE void web_data_receive_callback (void * arg, char * data, unsigned short length) [static]
Network receive callback function.
Parameters
in *arg connection pointer
in *data Data received
in length Length of data received
Returns
void
Definition at line 1654 of file web.c.
Referenced by web_data_connect_callback().
static MEMSPACE void web_data_reconnect_callback (void * arg, int8_t err) [static]
Network disconnect callback function.
Parameters
in *arg connection pointer FIXME TODO
Definition at line 1817 of file web.c.
Referenced by web_data_connect_callback().
static MEMSPACE void web_data_sent_callback (void * arg) [static]
Network sent callback function.
Parameters
in *arg connection pointer
Returns
void
Definition at line 1726 of file web.c.
Referenced by web_data_connect_callback().
MEMSPACE void web_init (int port)
Setup WEB server and accept connections.
Parameters
in port port number to run web server on
Returns
void
Definition at line 2367 of file web.c.
Referenced by setup().
MEMSPACE void web_init_connections (void)
Definition at line 2352 of file web.c.
MEMSPACE void web_task (void)
Process ALL incoming HTTP requests.
See also
process_requests()
Returns
void
Definition at line 2315 of file web.c.
Referenced by loop_wrapper().
MEMSPACE MEMSPACE int write_byte (rwbuf_t * p, int c)
Write a byte (buffered) using the rwbuf_t socket buffers for this connection If the buffers are full the socket is written using espconn_send.
Parameters
in *p rwbuf_t pointer for this socket buffer
in c character to write
Definition at line 547 of file web.c.
Referenced by _write_byte_fn(), write_len(), and write_str().
MEMSPACE void write_flush (rwbuf_t * p)
Flush the the socket write buffers for this connection If the buffers have any data in them it is written using espconn_send.
Parameters
in *p rwbuf_t pointer for this socket buffer
Returns
void
Definition at line 640 of file web.c.
Referenced by write_byte().
MEMSPACE void write_len (rwbuf_t * p, char * str, int len)
Write data using buffered write_byte function.
Parameters
in *p rwbuf_t pointer for this socket buffer
in *str data buffer to write
in len number of bytes to write
Returns
void
Definition at line 684 of file web.c.
Referenced by html_msg().
MEMSPACE void write_str (rwbuf_t * p, char * str)
Write string using buffered write_byte function.
Parameters
in *p rwbuf_t pointer for this socket buffer
in *str 0 terminated string to write
Returns
void
Definition at line 697 of file web.c.
Variable Documentation
MEMSPACE _led = 0 [static]
Turn on virtual LED.
Parameters
in led led to turn on
Returns
void
Definition at line 182 of file web.c.
int connections
Definition at line 2307 of file web.c.
Referenced by user_loop(), and user_tests().
char* http_status[]
HTTP status code messages.
Definition at line 84 of file web.c.
Referenced by html_status().
mime_t mimes[]
Initial value:
= {
    { PTYPE_TEXT, "text/plain", ".text", ".txt" },
    { PTYPE_HTML, "text/html", ".htm", ".html" },
    { PTYPE_PDF, "application/pdf", ".pdf",NULL},
    { PTYPE_CSS, "text/css", ".css", NULL },
    { PTYPE_CGI, "text/html", ".cgi", NULL },
    { PTYPE_JS, "text/plain", ".js", NULL },
    { PTYPE_XML, "text/plain", ".xml", NULL },
    { PTYPE_ICO, "mage/vnd.microsoft.icon", ".ico", NULL },
    { PTYPE_GIF, "image/gif", ".gif", NULL },
    { PTYPE_JPEG, "image/jpeg", ".jpg", ".jpeg" },
    { PTYPE_MPEG, "video/mpeg", ".mpg", ".mpeg" },
    { PTYPE_FLASH, "application/x-shockwave-flash", ".swf", NULL },
    { PTYPE_ERR, "text/html", NULL , NULL }
}
MIME types.
Definition at line 158 of file web.c.
header_t msg_headers[]
Initial value:
= {
    { "GET", TOKEN_GET },
    { "PUT", TOKEN_PUT },
    { "POST", TOKEN_POST },
    { "HEAD", TOKEN_HEAD },
    { "Host:", TOKEN_HOST },
    { "User-Agent:", TOKEN_USER_AGENT },
    { "HTTPS:", TOKEN_HTTPS},
    { "DNT:", TOKEN_DNT},
    { "Accept:", TOKEN_ACCEPT },
    { "Accept-Language:", TOKEN_ACCEPT_LANGUAGE },
    { "Accept-Encoding:", TOKEN_ACCEPT_ENCODING },
    { "Connection:", TOKEN_CONNECTION },
    { "Referer:", TOKEN_REFERER },
    { "Content-Length:", TOKEN_CONTENT_LENGTH },
    { "Content-Type:", TOKEN_CONTENT_TYPE },
    { "Cache-Control:", TOKEN_CACHE_CONTROL },
    { NULL, -1}
}
HTTP headers we understand.
Definition at line 59 of file web.c.
rwbuf_t* web_connections[MAX_CONNECTIONS]
socket buffers for this connection
Definition at line 48 of file web.c.
espconn_t WebConn
Master espconn structure of the web server.
Definition at line 51 of file web.c.
Referenced by find_connection(), and rwbuf_delete().
esp_tcp WebTcp [static]
Master network configuration for the web server.
Definition at line 53 of file web.c.
window* winmsg
window * wintop