wire/wire.h File Reference
Display wireframe object The code handles fixed, proportional and bounding box format fonts.
Data Structures
struct wire_p
struct wire_e
Macros
#define WIRE_ONE 16384 /* 1.0 */
#define WIRE_SEP 32766 /* pen up */
#define WIRE_END 32767 /* END */
#define WIRE_2FP(a) ((double) (a) / (double) (WIRE_ONE))
#define FP2_WIRE(a) ((wire_t) (WIRE_ONE * (a)))
Typedefs
typedef short int wire_t
Functions
void wire2fp (wire_p *in, point *out)
void scale2display (point *p, int *x, int *y)
void wire_draw (const wire_p *wire, const wire_e *edge, point *view, double scale, uint16_t color)
Detailed Description
Display wireframe object The code handles fixed, proportional and bounding box format fonts.
wireframe viewer
Copyright 2015 Mike Gore, GPL License
Edit History
[1.0] [Mike Gore] Initial revision of file.
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
wireframe.c is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file wire.h.
Macro Definition Documentation
#define FP2_WIRE(a) ((wire_t) (WIRE_ONE * (a)))
Definition at line 44 of file wire.h.
#define WIRE_2FP(a) ((double) (a) / (double) (WIRE_ONE))
Definition at line 43 of file wire.h.
Referenced by wire2fp().
#define WIRE_END 32767 /* END */
Definition at line 42 of file wire.h.
Referenced by main(), and wire_draw().
#define WIRE_ONE 16384 /* 1.0 */
Definition at line 40 of file wire.h.
Referenced by main().
#define WIRE_SEP 32766 /* pen up */
Definition at line 41 of file wire.h.
Referenced by main(), and wire_draw().
Typedef Documentation
typedef short int wire_t
Definition at line 28 of file wire.h.
Function Documentation
void scale2display (point * p, int * x, int * y)
Definition at line 55 of file wire.c.
Referenced by wire_draw().
void wire2fp (wire_p * in, point * out)
Definition at line 40 of file wire.c.
Referenced by wire_draw().
void wire_draw (const wire_p * wire, const wire_e * edge, point * view, double scale, uint16_t color)
Definition at line 70 of file wire.c.
Referenced by test().