wire/wire.c File Reference
Display wireframe object Can process either connected point lists or points and edges.
#include `user_config.h`
*
#include `ili9341.h`
*
#include <math.h>
*
#include `cordic.h`
*
#include `wire.h`
*
Functions
void wire2fp (wire_p *in, point *out)
void scale2display (point *p, int *x, int *y)
void wire_draw (const wire_p *wire, const wire_e *edge, point *view, double scale, uint16_t color)
Detailed Description
Display wireframe object Can process either connected point lists or points and edges.
Edit History
[1.0] [Mike Gore] Initial revision of file.
wireframe viewer
Copyright 2015 Mike Gore, GPL License
This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
wireframe.c is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Definition in file wire.c.
Function Documentation
void scale2display (point * p, int * x, int * y)
Definition at line 55 of file wire.c.
Referenced by wire_draw().
void wire2fp (wire_p * in, point * out)
Definition at line 40 of file wire.c.
Referenced by wire_draw().
void wire_draw (const wire_p * wire, const wire_e * edge, point * view, double scale, uint16_t color)
Definition at line 70 of file wire.c.
Referenced by test().