
/**
 @file font.c

 @brief Font display for ili9341 driver
 Displays fonts generated by bdffont2c BDF to C code converter
 BDF = Glyph Bitmap Distribution Format
 The code handles fixed, proportional and bounding box format fonts
 @see http://en.wikipedia.org/wiki/Glyph_Bitmap_Distribution_Format

 @par Copyright &copy; 2015 Mike Gore, GPL License
 @par You are free to use this code under the terms of GPL
   please retain a copy of this notice in any code you use it in.

This is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option)
any later version.

This software is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/


#include <user_config.h>

/// @brief save fonts in flash
#define MEMSPACE_FONT ICACHE_FLASH_ATTR

/// @brief we need to use addition width,height and offset sepcifications
/// This is NOT required for full fonts with fixed atributes
// #define FONTSPECS

/// @brief Generated Font table
//// Note the generated tables always include
//// Font specifications: widt, height, offsets, font type, etc
//// Font information: name, copyright, style information
//// FONSPECS and FONTINFO defines controls actual usage.
#include "fonts.h"
// All the fonts - defined in fonts.h
extern _font *allfonts[];

/// @brief  Get font attributes for a font
/// @param[in] *win: Window Structure
/// @param[in] c: character
/// @param[in] *f: font structure
/// @return  void
int font_attr(window *win, int c, _fontc *f)
{
    int offset;
    int num;
    unsigned char *ptr;
	int gap;

// check font
    _font *z = allfonts[win->font];
    _fontspecs s;

    num = c - z->First;
    if(num < 0 || num >= z->Glyphs)
        return(-1);

    f->ptr = z->bitmap;

// If we have font specifications use them
    if(z->specs)
    {
        f->Width = z->Width;
        f->Height = z->Height;

// Copy the full font specification into ram for easy access
// This does not use much memory as it does not include the bitmap
        cpy_flash((uint8_t *)&(z->specs[num]), (uint8_t *)&s,sizeof(_fontspecs));

        f->w = s.Width;
        f->h = s.Height;
        f->x = s.X;
        f->y = s.Y;

        offset = s.Offset;
        f->ptr += offset;

		gap = (z->Width+3)/4;
		if(gap <= 1)
			gap++;
// Override only if we have specs
// FIXME - if the width is faked (proportional font with fixed flag on)  - it may be too small!
// We need to save was font originally fixed in the font data
        f->fixed = win->fixed;
        if(f->fixed)
            f->gap = f->Width + gap;
        else
            f->gap = f->w + gap;
    }

    else   // No Specs, Create the font specification using main font size spec
    {
        f->Width = z->Width;
        f->Height = z->Height;

		gap = (z->Width+3)/4;
		if(gap <= 1)
			gap++;

        f->w = z->Width;
        f->h = z->Height;
        f->x = 0;
        f->y = 0;

// FIXME - if the width is faked (proportional font with fixed flag on)  - it may be too small!
// We need to save was font originally fixed in the font data
        f->fixed = win->fixed;
        if(f->fixed)
            f->gap = f->Width + gap;
        else
            f->gap = f->w + gap;

        offset = ((z->Width * z->Height)+7)/8; /* round to byte boundry */
        f->ptr += (offset * num);

    }

#ifdef ILI9341_DEBUG
    ets_uart_printf("c: %02x font:%d w:%d h:%d x:%d y:%d gap:%d, W:%d, H:%d\r\n",
        0xff & c, 0xff & win->font, f->w, f->h, f->x, f->y, f->gap, f->Width, f->Height);
#endif
    return(win->font);
}


/// @brief  Display a character using font tables
/// @param[in] *win: Window Structure
/// @param[in] c: character
/// @return  void
int tft_drawChar(window *win, uint8_t c)
{
    _fontc f;
    int ret;
    int yskip;

    ret = font_attr(win, c, &f);
    if(ret < 0)
        return (0);

    if(!f.h || !f.w)
        return (0);

// Alternate clear - all pixels inside the font bounding box
    if(f.h != f.Height ||  f.w != f.Width || f.x != 0 || f.y != 0)
        tft_fillRectWH(win, win->x, win->y, f.Width, f.Height, win->bg);

// top of bit bounding box ( first row with a 1 bit in it)
    yskip = f.Height - (f.y+f.h);

    tft_bit_blit(win, f.ptr, win->x+f.x, win->y+yskip, f.w, f.h, win->fg, win->bg);

    return (f.gap);
}
