/**
 @file font.h

 @brief Font display for ili9341 driver
 Displays fonts generated by bdffont2c BDF to C code converter
 BDF = Glyph Bitmap Distribution Format
 The code handles fixed, proportional and bounding box format fonts
 @see http://en.wikipedia.org/wiki/Glyph_Bitmap_Distribution_Format

 @par Copyright &copy; 2015 Mike Gore, GPL License
 @par You are free to use this code under the terms of GPL
   please retain a copy of this notice in any code you use it in.

This is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option)
any later version.

This software is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/


/**
 * BDF = Glyph Bitmap Distribution Format
 * See: http://en.wikipedia.org/wiki/Glyph_Bitmap_Distribution_Format
 */
#ifndef _VFONT_H_
#define _VFONT_H_

//#include "stdint.h"

typedef struct {
	int16_t xoff;   /* X offset */
	int16_t yff;    /* Y offset */
	int16_t w;      /* Width */
	int16_t h;      /* Height */
	int16_t xinc;   /* Distance to Next Character by X */
	int16_t yinc;   /* Distance to Next Character by Y */
	int16_t hby;    /* gm.horiBearingY */
	int16_t vby;    /* gm.vertBearingY */
	int16_t contours; /* Contours */ 
	int16_t v[];    /* Data */
} path_t;

#endif                                            //_VFONT_H_
