/**
 @file earth2wireframe.c


 @brief Convert Earth wireframe in Lon, Lat pairs
 Each group (a set of Lon, Lat pairs) is separated by one or 
 more blank lines, # are comments and ignored

 @par Copyright &copy; 2015 Mike Gore, GPL License
 @par Edit History
 - [1.0]   [Mike Gore]  Initial revision of file.

 This is free software: you can redistribute it and/or modify it under the
 terms of the GNU General Public License as published by the Free Software
 Foundation, either version 3 of the License, or (at your option)
 any later version.

 earth2wireframe is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <unistd.h>
#include <libgen.h>


#include "../wire/wire.h"

/// @brief Convert of Radians
/// @param[in] deg: degrees
/// @return radians
double deg2rad(double  deg)
{
	return (deg * 0.0174532925);
}

/// @brief Convert earth wireframe data to C structure
///		Usage: %s -f filename [-p]\n",argv[0]);
///		-f filename is the lot,lat dataset pairs
///		-p          disable mapxyz typedef
int main(int argc, char *argv[])
{
	double xx,yy,zz;
	double scale;
	double lat,lon;
	double lat_rad,lon_rad;
	short int x,y,z;
	int i;
	int len;
	int prototype = 1;
	char *p, *name;
	FILE *FP;
	char buff[256];

	char cwd[512];

	name = NULL;

	getcwd(cwd, 510);

	for(i=1; i<argc;++i)
	{
		p = argv[i];
		if(*p != '-')
			continue;
		++p;
		if(*p == 'f')
		{
			name = argv[++i];
		}
	}
	if(!name)
	{
		printf("Usage: %s -f filename [-p]\n",argv[0]);
		printf("-f filename is the lot,lat dataset pairs\n");
	}

	printf("#ifndef _EARTH_DATA_H_\n");
	printf("#define _EARTH_DATA_H_\n");

	printf("/* Mike Gore 2015, Earth Wireframe C Table */\n");
	printf("/* Generated by program:[%s/%s] */\n", cwd, basename(argv[0]));
	printf("/* Source: %s */\n", name);

	printf("MEMSPACE_RO wire_p earth_data[] = {\n");
    fflush(stdout);

	FP = fopen(name,"r");
	if(FP == NULL)
	{
		fprintf(stderr,"Can not open: [%s]\n", name);
		exit (1);
	}

	while( fgets(buff, sizeof(buff)-2, FP))
    {
		len = strlen(buff);	
		// remove any white space characters at the end of the line
		while(len && buff[len-1] < ' ')
			buff[--len] = 0;

		if(!len)
		{
			if(lon == WIRE_SEP)
				continue;
		}
		if(*buff == '#')
		{
			if(lon == WIRE_SEP)
				continue;
			printf("/* %s */\n", buff);
		}

		lon = WIRE_SEP;
		lat = WIRE_SEP;
		
		// degrees
		if(len)
			sscanf(buff, "%lf %lf", &lon, &lat);

        // radians
        lon_rad = deg2rad(lon);
        lat_rad = deg2rad(lat);

        //printf("%f, %f\n", lon,lat);
        //printf("%f, %f\n", lon_rad,lat_rad);
        //fflush(stdout);

        if(!len || lon == WIRE_SEP || lat == WIRE_SEP)
        {
            // this point is the end of a vector - not plotted
            x = WIRE_SEP;
            y = WIRE_SEP;
            z = WIRE_SEP;
            printf("\t{%d,%d,%d}, /* sep */\n", 
				(int)x ,(int)y ,(int)z 
				);
            //printf("\t{%f,%f,%f},\n", x,y,z);
            fflush(stdout);
        }
        else
        {
			x = (cos(lat_rad) * cos(lon_rad)) * WIRE_ONE;
            y = (cos(lat_rad) * sin(lon_rad)) * WIRE_ONE;
            z = sin(lat_rad) * WIRE_ONE;
            // reverse is
            // lat = asin(z / R)
            // lon = atan2(y, x)
            printf("\t{%d,%d,%d}, /* %f, %f */\n", 
				(int)x ,(int)y ,(int)z ,
				lon, lat);
            //printf("\t{%f,%f,%f},\n", x,y,z);
            fflush(stdout);
        }
                                                                    
    }
	fclose(FP);
    // this point is the end of a vector - not plotted
    x = WIRE_SEP;
    y = WIRE_SEP;
    z = WIRE_SEP;
	printf("\t{%d,%d,%d}, /* sep */\n", 
		(int)x ,(int)y ,(int)z 
		);
    fflush(stdout);
    // this point is the end of the data set
    x = WIRE_END;
    y = WIRE_END;
    z = WIRE_END;
	printf("\t{%d,%d,%d}, /* END */\n", 
		(int)x ,(int)y ,(int)z 
		);
    printf("};\n");
    fflush(stdout);
	printf("#else /* _EARTH_DATA_H */\n");
	printf("	extern MEMSPACE_RO wire_p earth_data[];\n");
	printf("#endif /* _EARTH_DATA_H_ */\n");
	return(0);
}

