/**
 @file earth2wireframe.c


 @brief Convert Earth wireframe in Lon, Lat pairs
 Each group (a set of Lon, Lat pairs) is separated by one or 
 more blank lines, # are comments and ignored

 @par Copyright &copy; 2015 Mike Gore, GPL License
 @par Edit History
 - [1.0]   [Mike Gore]  Initial revision of file.

 This is free software: you can redistribute it and/or modify it under the
 terms of the GNU General Public License as published by the Free Software
 Foundation, either version 3 of the License, or (at your option)
 any later version.

 earth2wireframe is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <unistd.h>
#include <libgen.h>

typedef short int MAP_T;

#define MAP_ONE  16384 /* 1.0 */
#define MAPSEP (MAP_ONE*2-2)
#define MAPEND (MAP_ONE*2-1)

// Convert MAP fixed point to double
#define MAP2FP(a)  ( (double) (a) / (double) (MAP_ONE)) 
// double to MAP fixed point 
#define FP2MAP(a)  ((MAP_T) (MAP_ONE * (a)))

/// @brief Convert of Radians
/// @param[in] deg: degrees
/// @return radians
double deg2rad(double  deg)
{
	return (deg * 0.0174532925);
}

/// @brief Convert earth wireframe data to C structure
///		Usage: %s -f filename [-p]\n",argv[0]);
///		-f filename is the lot,lat dataset pairs
///		-p          disable mapxyz typedef
int main(int argc, char *argv[])
{
	double xx,yy,zz;
	double scale;
	double lat,lon;
	double lat_rad,lon_rad;
	short int x,y,z;
	int i;
	int len;
	int prototype = 1;
	char *p, *name;
	FILE *FP;
	char buff[256];

	char cwd[512];

	name = NULL;

	getcwd(cwd, 510);

	for(i=1; i<argc;++i)
	{
		p = argv[i];
		if(*p != '-')
			continue;
		++p;
		if(*p == 'f')
		{
			name = argv[++i];
		}
		if(*p == 'p')
		{
			prototype = 0;
		}
	}
	if(!name)
	{
		printf("Usage: %s -f filename [-p]\n",argv[0]);
		printf("-f filename is the lot,lat dataset pairs\n");
		printf("-p          disable mapxyz typedef\n");
	}

	printf("#ifndef _EARTH_INC_H_\n");
	printf("#define _EARTH_INC_H_\n");

	printf("//Mike Gore 2015, Earth Wireframe C Table\n");
	printf("//Generated by program:[%s/%s]\n", cwd, basename(argv[0]));
	printf("/* Source: %s */\n", name);
	printf("typedef short int MAP_T;\n");
	printf("#define MAP_ONE  %d /* 1.0 */\n", MAP_ONE);
	printf("#define MAPSEP %d  /* pen up */\n", MAPSEP);
	printf("#define MAPEND %d  /* END */\n", MAPEND);
	printf("#define MAP2FP(a)  ( (double) (a) / (double) (MAP_ONE))\n");
	printf("#define FP2MAP(a)  ((MAP_T) (MAP_ONE * (a)))\n");
    if(prototype)
	{
		printf("typedef struct {\n");
		printf("  MAP_T x;\n");
		printf("  MAP_T y;\n");
		printf("  MAP_T z;\n");
		printf("} mapxyz;\n");
	}

	printf("#ifdef MAP_DATA\n");
	printf(" MEMSPACE_RO mapxyz map[] = {\n");
    fflush(stdout);

	FP = fopen(name,"r");
	if(FP == NULL)
	{
		fprintf(stderr,"Can not open: [%s]\n", name);
		exit (1);
	}

	while( fgets(buff, sizeof(buff)-2, FP))
    {
		len = strlen(buff);	
		// remove any white space characters at the end of the line
		while(len && buff[len-1] < ' ')
			buff[--len] = 0;

		if(!len)
		{
			if(lon == MAPSEP)
				continue;
		}
		if(*buff == '#')
		{
			if(lon == MAPSEP)
				continue;
			printf("/* %s */\n", buff);
		}

		lon = MAPSEP;
		lat = MAPSEP;
		
		// degrees
		if(len)
			sscanf(buff, "%lf %lf", &lon, &lat);

        // radians
        lon_rad = deg2rad(lon);
        lat_rad = deg2rad(lat);

        //printf("%f, %f\n", lon,lat);
        //printf("%f, %f\n", lon_rad,lat_rad);
        //fflush(stdout);

        if(!len || lon == MAPSEP || lat == MAPSEP)
        {
            // this point is the end of a vector - not plotted
            x = MAPSEP;
            y = MAPSEP;
            z = MAPSEP;
            printf("\t{%d,%d,%d}, /* sep */\n", 
				(int)x ,(int)y ,(int)z 
				);
            //printf("\t{%f,%f,%f},\n", x,y,z);
            fflush(stdout);
        }
        else
        {
			x = (cos(lat_rad) * cos(lon_rad)) * MAP_ONE;
            y = (cos(lat_rad) * sin(lon_rad)) * MAP_ONE;
            z = sin(lat_rad) * MAP_ONE;
            // reverse is
            // lat = asin(z / R)
            // lon = atan2(y, x)
            printf("\t{%d,%d,%d}, /* %f, %f */\n", 
				(int)x ,(int)y ,(int)z ,
				lon, lat);
            //printf("\t{%f,%f,%f},\n", x,y,z);
            fflush(stdout);
        }
                                                                    
    }
	fclose(FP);
    // this point is the end of a vector - not plotted
    x = MAPSEP;
    y = MAPSEP;
    z = MAPSEP;
	printf("\t{%d,%d,%d}, /* sep */\n", 
		(int)x ,(int)y ,(int)z 
		);
    fflush(stdout);
    // this point is the end of the data set
    x = MAPEND;
    y = MAPEND;
    z = MAPEND;
	printf("\t{%d,%d,%d}, /* END */\n", 
		(int)x ,(int)y ,(int)z 
		);
    printf("};\n");
    fflush(stdout);
	printf("#else /* MAP_DATA */\n");
	printf("   extern const mapxyz map[];\n");
	printf("#endif /* MAP_DATA */\n");
	printf("#endif /* _EARTH_INC_H_ */\n");
	return(0);
}

